# Generated by Django 5.0.6 on 2024-06-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesdevelopment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categoriesdevelopment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='components',
            name='title',
        ),
        migrations.RemoveField(
            model_name='designs',
            name='title',
        ),
        migrations.RemoveField(
            model_name='models3d',
            name='title',
        ),
        migrations.RemoveField(
            model_name='section',
            name='title',
        ),
        migrations.AddField(
            model_name='categoriesdevelopment',
            name='description_en',
            field=models.TextField(default=1, verbose_name='Description (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriesdevelopment',
            name='description_es',
            field=models.TextField(default=1, verbose_name='Description (Spanish)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriesdevelopment',
            name='title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Title (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoriesdevelopment',
            name='title_es',
            field=models.CharField(default=1, max_length=255, verbose_name='Title (Spanish)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='components',
            name='title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Title (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='components',
            name='title_es',
            field=models.CharField(default=1, max_length=255, verbose_name='Title (Spanish)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designs',
            name='title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Title (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designs',
            name='title_es',
            field=models.CharField(default=1, max_length=255, verbose_name='Title (Spanish)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='models3d',
            name='title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Title (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='models3d',
            name='title_es',
            field=models.CharField(default=1, max_length=255, verbose_name='Title (Spanish)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Title (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='title_es',
            field=models.CharField(default=1, max_length=255, verbose_name='Title (Spanish)'),
            preserve_default=False,
        ),
    ]
