# Generated by Django 5.0.6 on 2026-03-18 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_requirement_comment_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('module_or_screen', models.CharField(blank=True, default='', max_length=200)),
                ('suggested_priority', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('evaluating', 'En evaluación'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('needs_clarification', 'Requiere aclaración'), ('out_of_scope', 'Fuera de alcance')], default='pending', max_length=25)),
                ('admin_response', models.TextField(blank=True, default='')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated additional cost in project currency.', max_digits=12, null=True)),
                ('estimated_time', models.CharField(blank=True, default='', help_text='Estimated time to implement (e.g. "2 semanas").', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
                ('linked_requirement', models.ForeignKey(blank=True, help_text='Requirement created from this change request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_change_request', to='accounts.requirement')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='accounts.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comments are visible only to admins.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.changerequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_request_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
