# Generated by Django 5.0.6 on 2026-03-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_change_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Optimized automatically on upload (WhatsApp-like compression).', null=True, upload_to='change_requests/'),
        ),
    ]
