# Generated by Django 5.0.6 on 2026-03-18 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_change_request_screenshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('critical', 'Crítica'), ('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], default='medium', max_length=20)),
                ('steps_to_reproduce', models.JSONField(blank=True, default=list, help_text='Numbered list of steps to reproduce the bug.')),
                ('expected_behavior', models.TextField(blank=True, default='')),
                ('actual_behavior', models.TextField(blank=True, default='')),
                ('environment', models.CharField(choices=[('production', 'Producción'), ('staging', 'Staging'), ('dev', 'Desarrollo')], default='production', max_length=20)),
                ('device_browser', models.CharField(blank=True, default='', max_length=200)),
                ('is_recurring', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('reported', 'Reportado'), ('confirmed', 'Confirmado'), ('fixing', 'En corrección'), ('qa', 'En QA'), ('resolved', 'Resuelto'), ('not_reproducible', 'No reproducible'), ('wont_fix', 'No se corregirá'), ('duplicate', 'Duplicado')], default='reported', max_length=25)),
                ('admin_response', models.TextField(blank=True, default='')),
                ('screenshot', models.ImageField(blank=True, help_text='Optimized automatically on upload (WhatsApp-like compression).', null=True, upload_to='bug_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_bug', models.ForeignKey(blank=True, help_text='Original bug if this is a duplicate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='accounts.bugreport')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to='accounts.project')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comments are visible only to admins.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_comments', to=settings.AUTH_USER_MODEL)),
                ('bug_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.bugreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
