# Generated by Django 5.0.6 on 2026-03-18 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_deliverable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bug_reported', 'Bug reportado'), ('bug_status_changed', 'Estado de bug actualizado'), ('cr_created', 'Solicitud de cambio creada'), ('cr_status_changed', 'Solicitud de cambio actualizada'), ('cr_converted', 'Solicitud convertida en requerimiento'), ('requirement_moved', 'Requerimiento movido'), ('requirement_approved', 'Requerimiento aprobado'), ('deliverable_uploaded', 'Entregable subido'), ('deliverable_new_version', 'Nueva versión de entregable'), ('comment_added', 'Nuevo comentario'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField(blank=True, default='')),
                ('related_object_type', models.CharField(blank=True, default='', help_text='Model name: project, change_request, bug_report, deliverable, requirement', max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, help_text='Project context for deep-linking.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
