# Generated by Django 5.0.6 on 2026-03-18 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification'),
        ('content', '0047_add_hosting_billing_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text='Linked business proposal for cost/hosting derivation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_projects', to='content.businessproposal'),
        ),
        migrations.CreateModel(
            name='HostingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral')], default='monthly', max_length=20)),
                ('base_monthly_amount', models.DecimalField(decimal_places=2, help_text='Monthly hosting cost before discount (COP).', max_digits=12)),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='Discount % based on plan (0, 10, 20).')),
                ('effective_monthly_amount', models.DecimalField(decimal_places=2, help_text='Monthly cost after discount (COP).', max_digits=12)),
                ('billing_amount', models.DecimalField(decimal_places=2, help_text='Total amount charged per billing cycle (COP).', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida'), ('cancelled', 'Cancelada'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('start_date', models.DateField(help_text='Date from which the subscription is active and billable.')),
                ('next_billing_date', models.DateField(blank=True, help_text='Next date a payment is due.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hosting_subscription', to='accounts.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('paid', 'Pagado'), ('failed', 'Fallido'), ('overdue', 'Vencido')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('wompi_transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('wompi_payment_link_id', models.CharField(blank=True, default='', max_length=100)),
                ('wompi_payment_link_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.hostingsubscription')),
            ],
            options={
                'ordering': ['-billing_period_start'],
            },
        ),
    ]
