# Generated by Django 5.0.6 on 2026-03-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_requirement_configuration_flow_remove_hours_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_image',
            field=models.CharField(blank=True, default='', help_text='Path to cover gallery image (e.g. NASA Archive/imgi_21_nasa_the_blue_marble.jpg).', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_cover_image',
            field=models.ImageField(blank=True, help_text='User-uploaded custom cover image.', null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_color',
            field=models.CharField(blank=True, default='', help_text='Hex color for UI theme (e.g. #002921).', max_length=7),
        ),
    ]
