# Generated by Django 5.0.6 on 2026-04-01 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_bugreport_deliverable_notification_paymenthistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenthistory',
            new_name='accounts_pa_payment_ba06ab_idx',
            old_name='accounts_pa_payment_6e1c8e_idx',
        ),
        migrations.AddField(
            model_name='bugreport',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bugreport',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from default lists; row kept for audit.'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from default lists; row kept for audit.'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from default lists; row kept for audit.'),
        ),
        migrations.AddField(
            model_name='hostingsubscription',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostingsubscription',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from subscription lists; row kept for audit.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from default payment lists; row kept for audit.'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Hidden from default lists; row kept for audit.'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.hostingsubscription'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='accounts.payment'),
        ),
    ]
