# Generated by Django 5.0.6 on 2026-04-03 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_archived_soft_delete_protect_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModelEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('key_fields', models.TextField(blank=True, default='', help_text='Comma-separated key fields for this entity.')),
                ('source_entity_name', models.CharField(blank=True, db_index=True, default='', help_text='Original entity name from proposal JSON, used for idempotent sync.', max_length=300)),
                ('synced_from_proposal', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Hidden from default lists; row kept for audit.')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_model_entities', to='accounts.deliverable')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='datamodelentity',
            constraint=models.UniqueConstraint(condition=models.Q(('source_entity_name', ''), _negated=True), fields=('deliverable', 'source_entity_name'), name='uniq_data_model_entity_deliverable_source'),
        ),
    ]
