# Generated by Django 5.0.6 on 2026-04-03 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_data_model_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDataModelEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('key_fields', models.TextField(blank=True, default='', help_text='Comma-separated key fields for this entity.')),
                ('relationship', models.CharField(blank=True, default='', help_text='Relationship description (e.g. "1:N with Order").', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_data_model_entities', to='accounts.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
