# Generated by Django 5.0.6 on 2026-05-17 02:55

import django.db.models.deletion
from django.db import migrations, models


def backfill_phases_from_deliverables(apps, schema_editor):
    """For each existing Project, find the first proposal linked via a
    Deliverable and create a ProjectPhase row (order=1). Projects with no
    linked proposal are left without phases — admin can attach them via the
    new wizard post-deploy."""
    Project = apps.get_model('accounts', 'Project')
    ProjectPhase = apps.get_model('accounts', 'ProjectPhase')
    BusinessProposal = apps.get_model('content', 'BusinessProposal')

    for project in Project.objects.all():
        bp = BusinessProposal.objects.filter(
            deliverable__project_id=project.id,
        ).order_by('deliverable_id').first()
        if bp is None:
            continue
        ProjectPhase.objects.get_or_create(
            project=project, business_proposal=bp,
            defaults={'order': 1},
        )


def reverse_backfill(apps, schema_editor):
    ProjectPhase = apps.get_model('accounts', 'ProjectPhase')
    ProjectPhase.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_backfill_user_profiles'),
        ('content', '0122_email_template_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_phases', to='content.businessproposal')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='accounts.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.UniqueConstraint(fields=('project', 'business_proposal'), name='unique_proposal_per_project'),
        ),
        migrations.RunPython(backfill_phases_from_deliverables, reverse_backfill),
    ]
