# Generated by Django 5.0.6 on 2026-05-17 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_project_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='source_requirement',
            field=models.ForeignKey(blank=True, help_text='Requirement this bug is about (client picked when filing).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports_about', to='accounts.requirement'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='source_requirement',
            field=models.ForeignKey(blank=True, help_text='Requirement this change request is about (client picked when filing).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_about', to='accounts.requirement'),
        ),
    ]
