# Generated by Django 5.2.13 on 2026-05-19 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_project_phase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilterTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(choices=[('proposal', 'Proposal'), ('client', 'Client'), ('diagnostic', 'Diagnostic'), ('view_map', 'View Map')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filter_tabs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['view', 'order', 'created_at'],
                'indexes': [models.Index(fields=['user', 'view', 'order'], name='accounts_sa_user_id_7c84b6_idx')],
            },
        ),
    ]
