# Generated by Django 5.0.6 on 2026-05-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_requirement_uniq_requirement_deliverable_flow_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='hosting_start_date',
            field=models.DateField(blank=True, help_text="Date when this phase's hosting billing begins (set by admin).", null=True),
        ),
    ]
