# Generated by Django 5.0.6 on 2026-05-20 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_projectphase_hosting_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='phase',
            field=models.ForeignKey(blank=True, help_text='Phase this bug report belongs to (auto-assigned from source_requirement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_bug_reports', to='accounts.projectphase'),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='phase',
            field=models.ForeignKey(blank=True, help_text='Phase this change request belongs to (auto-assigned from source_requirement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_change_requests', to='accounts.projectphase'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='source',
            field=models.CharField(blank=True, choices=[('api', 'API'), ('wompi_link', 'Wompi payment link'), ('webhook', 'Wompi webhook'), ('wompi_verify', 'Wompi verify'), ('system', 'System'), ('manual', 'Manual (admin)')], default='', max_length=32),
        ),
    ]
