# Generated by Django 5.0.6 on 2026-05-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_add_phase_fk_to_cr_and_bug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingsubscription',
            name='card_brand',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='hostingsubscription',
            name='card_exp_month',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='hostingsubscription',
            name='card_exp_year',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='hostingsubscription',
            name='card_last_four',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='hostingsubscription',
            name='wompi_payment_source_id',
            field=models.CharField(blank=True, default='', help_text='Wompi payment source ID for stored-card recurring billing.', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='charge_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of automatic charge attempts made for this payment.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_charge_error',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='payment',
            name='next_retry_at',
            field=models.DateField(blank=True, help_text='Earliest date the auto-billing task may retry this payment.', null=True),
        ),
    ]
