# Generated by Django 5.0.6 on 2026-05-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_hostingsubscription_card_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='hosting_activated_at',
            field=models.DateField(blank=True, help_text='Date this phase was incorporated into the recurring subscription billing. Null = not yet billed (the billing cron will onboard it once hosting_start_date arrives).', null=True),
        ),
    ]
