# Generated by Django 5.0.6 on 2026-05-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_saved_filter_tab'),
        ('accounts', '0032_projectphase_hosting_activated_at'),
    ]

    operations = [
    ]
