# Generated by Django 5.2.13 on 2026-07-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_remove_monthly_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfiltertab',
            name='view',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('client', 'Client'), ('diagnostic', 'Diagnostic'), ('view_map', 'View Map'), ('accounting_income', 'Accounting Income'), ('accounting_expense', 'Accounting Expense'), ('accounting_hosting', 'Accounting Hosting'), ('accounting_pocket', 'Accounting Pocket'), ('accounting_recurring', 'Accounting Recurring'), ('accounting_history', 'Accounting History')], db_index=True, max_length=20),
        ),
    ]
