# Generated by Django 5.2.13 on 2026-07-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_savedfiltertab_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='True after the client confirms ownership of their email via an OTP code.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='purpose',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('password_reset', 'Password Reset'), ('email_validation', 'Email Validation')], default='onboarding', max_length=20),
        ),
    ]
