# Generated by Django 5.2.13 on 2026-07-04 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='content_overridden',
            field=models.BooleanField(default=False, help_text='Admin manually edited descriptive fields; a proposal re-sync will not overwrite title/description/flow/configuration/priority.'),
        ),
        migrations.CreateModel(
            name='ProjectScopeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_item_id', models.CharField(blank=True, db_index=True, default='', help_text="Stable commercial item id ('item-<group>-<slug>') from the proposal, used for idempotent sync and requirement linking.", max_length=300)),
                ('origin', models.CharField(choices=[('group', 'Grupo'), ('additional', 'Módulo adicional')], default='group', max_length=20)),
                ('group_id', models.CharField(blank=True, db_index=True, default='', help_text="Raw group id, e.g. 'views'/'components'/'features'/'admin_module'.", max_length=200)),
                ('group_title', models.CharField(blank=True, default='', max_length=300)),
                ('group_icon', models.CharField(blank=True, default='', max_length=50)),
                ('group_order', models.PositiveIntegerField(default=0)),
                ('group_is_visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('item_order', models.PositiveIntegerField(default=0)),
                ('synced_from_proposal', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Hidden from default lists; row kept for audit.')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_items', to='accounts.projectphase')),
            ],
            options={
                'ordering': ['group_order', 'item_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='requirement',
            name='scope_item',
            field=models.ForeignKey(blank=True, help_text='Primary client-facing scope item (from the first linked_item_id) used to group this card on the board.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='accounts.projectscopeitem'),
        ),
        migrations.AddConstraint(
            model_name='projectscopeitem',
            constraint=models.UniqueConstraint(condition=models.Q(('source_item_id', ''), _negated=True), fields=('phase', 'source_item_id'), name='uniq_scope_item_phase_source'),
        ),
    ]
