# Generated by Django 5.2.13 on 2026-07-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_project_scope_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When set, this client is marked inactive and hidden from the default panel client lists. Independent from auth.User.is_active, which is False for client shells.', null=True),
        ),
    ]
