# Generated by Django 5.2.13 on 2026-08-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_drop_solo_esperados_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='billing_code',
            field=models.CharField(blank=True, help_text='Short code for per-client collection-account numbering (PA-{CODE}-{NNN}). Auto-derived on first use; store None, never "".', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nit',
            field=models.CharField(blank=True, default='', help_text='Tax id for company clients; preferred over cedula on billing documents.', max_length=32),
        ),
    ]
