# Generated by Django 5.2.13 on 2026-08-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_userprofile_billing_code_userprofile_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfiltertab',
            name='view',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('client', 'Client'), ('diagnostic', 'Diagnostic'), ('view_map', 'View Map'), ('accounting_income', 'Accounting Income'), ('accounting_expense', 'Accounting Expense'), ('accounting_hosting', 'Accounting Hosting'), ('accounting_pocket', 'Accounting Pocket'), ('accounting_recurring', 'Accounting Recurring'), ('accounting_ads', 'Accounting Ads'), ('accounting_history', 'Accounting History'), ('accounting_cards', 'Accounting Cards')], db_index=True, max_length=20),
        ),
    ]
