# Generated by Django 5.2.13 on 2026-08-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_savedfiltertab_collections_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfiltertab',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedfiltertab',
            name='is_seeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedfiltertab',
            name='view',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('client', 'Client'), ('diagnostic', 'Diagnostic'), ('view_map', 'View Map'), ('accounting_income', 'Accounting Income'), ('accounting_expense', 'Accounting Expense'), ('accounting_hosting', 'Accounting Hosting'), ('accounting_pocket', 'Accounting Pocket'), ('accounting_recurring', 'Accounting Recurring'), ('accounting_ads', 'Accounting Ads'), ('accounting_history', 'Accounting History'), ('accounting_history_sends', 'Accounting History — Sends'), ('accounting_history_changes', 'Accounting History — Changes'), ('accounting_cards', 'Accounting Cards'), ('accounting_collections', 'Accounting Collections')], db_index=True, max_length=32),
        ),
    ]
