# Generated by Django 5.2.13 on 2026-08-18 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_pocket_attribution_filter_tabs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfiltertab',
            name='builtin_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='savedfiltertab',
            constraint=models.UniqueConstraint(condition=models.Q(('builtin_key__gt', '')), fields=('user', 'view', 'builtin_key'), name='uniq_saved_filter_tab_builtin_key'),
        ),
    ]
