# Generated by Django 5.2.13 on 2026-08-19 17:16

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def assert_no_duplicate_non_blank_sync_keys(apps, schema_editor):
    constraints = (
        ('DataModelEntity', ('deliverable_id',), 'source_entity_name'),
        ('Deliverable', ('project_id',), 'source_epic_key'),
        ('ProjectScopeItem', ('phase_id',), 'source_item_id'),
        ('Requirement', ('phase_id',), 'source_flow_key'),
        ('SavedFilterTab', ('user_id', 'view'), 'builtin_key'),
    )

    for model_name, scope_fields, key_field in constraints:
        model = apps.get_model('accounts', model_name)
        duplicate = (
            model.objects.exclude(**{key_field: ''})
            .values(*scope_fields, key_field)
            .annotate(row_count=Count('pk'))
            .filter(row_count__gt=1)
            .order_by(*scope_fields, key_field)
            .first()
        )
        if duplicate:
            raise RuntimeError(
                f'Cannot enforce {model_name}.{key_field} uniqueness: '
                f'duplicate non-blank key found in scope {duplicate!r}.'
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_savedfiltertab_builtin_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            assert_no_duplicate_non_blank_sync_keys,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='datamodelentity',
            name='uniq_data_model_entity_deliverable_source',
        ),
        migrations.RemoveConstraint(
            model_name='deliverable',
            name='uniq_deliverable_project_epic_key',
        ),
        migrations.RemoveConstraint(
            model_name='projectscopeitem',
            name='uniq_scope_item_phase_source',
        ),
        migrations.RemoveConstraint(
            model_name='requirement',
            name='uniq_requirement_phase_flow_key',
        ),
        migrations.RemoveConstraint(
            model_name='savedfiltertab',
            name='uniq_saved_filter_tab_builtin_key',
        ),
        migrations.AddConstraint(
            model_name='datamodelentity',
            constraint=models.UniqueConstraint(models.F('deliverable'), django.db.models.functions.comparison.NullIf(models.F('source_entity_name'), models.Value('')), name='uniq_data_model_entity_deliverable_source'),
        ),
        migrations.AddConstraint(
            model_name='deliverable',
            constraint=models.UniqueConstraint(models.F('project'), django.db.models.functions.comparison.NullIf(models.F('source_epic_key'), models.Value('')), name='uniq_deliverable_project_epic_key'),
        ),
        migrations.AddConstraint(
            model_name='projectscopeitem',
            constraint=models.UniqueConstraint(models.F('phase'), django.db.models.functions.comparison.NullIf(models.F('source_item_id'), models.Value('')), name='uniq_scope_item_phase_source'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(models.F('phase'), django.db.models.functions.comparison.NullIf(models.F('source_flow_key'), models.Value('')), name='uniq_requirement_phase_flow_key'),
        ),
        migrations.AddConstraint(
            model_name='savedfiltertab',
            constraint=models.UniqueConstraint(models.F('user'), models.F('view'), django.db.models.functions.comparison.NullIf(models.F('builtin_key'), models.Value('')), name='uniq_saved_filter_tab_builtin_key'),
        ),
    ]
