# Generated by Django 5.2.17 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_hosting_nine_month_terms'),
        ('content', '0212_seed_communications_mcp'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_state',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'catalog': 'projects'},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='current_projects',
                to='content.documentstate',
            ),
        ),
        migrations.AddField(
            model_name='project',
            name='state_review_required',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text=(
                    'True until a migrated legacy status is confirmed by a user.'
                ),
            ),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(
                choices=[
                    ('development', 'En desarrollo'),
                    ('active', 'Activo'),
                    ('paused', 'Pausado'),
                    ('suspended', 'Suspendido'),
                    ('completed', 'Completado'),
                    ('decommissioned', 'Dado de baja'),
                    ('archived', 'Archivado'),
                ],
                default='development',
                help_text=(
                    'Compatibility mirror of current_state.system_key. New writes '
                    'must use the project state-transition service.'
                ),
                max_length=20,
            ),
        ),
    ]
