# Generated by Django 6.1 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_add_communication_saved_filter_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='document_navigation_mode',
            field=models.CharField(
                choices=[('project', 'Proyectos'), ('client', 'Clientes')],
                default='project',
                help_text=(
                    'Grouping last selected by this account in the document manager.'
                ),
                max_length=10,
            ),
        ),
    ]
