# Generated by Django 6.1 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_userprofile_document_navigation_mode'),
        ('content', '0229_remove_paused_project_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(
                choices=[
                    ('development', 'En desarrollo'),
                    ('active', 'Activo'),
                    ('suspended', 'Suspendido'),
                    ('completed', 'Completado'),
                    ('decommissioned', 'Dado de baja'),
                    ('archived', 'Archivado'),
                ],
                default='development',
                help_text=(
                    'Compatibility mirror of current_state.system_key. New '
                    'writes must use the project state-transition service.'
                ),
                max_length=20,
            ),
        ),
    ]
