# Generated by Django 6.1 on 2026-08-30 14:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_userprofile_document_navigation_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationPanelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation_mode', models.CharField(choices=[('project', 'Proyectos'), ('client', 'Clientes')], default='project', max_length=10)),
                ('thread_order', models.CharField(choices=[('recent', 'Recientes'), ('oldest', 'Antiguos'), ('title', 'Título')], default='recent', max_length=10)),
                ('page_size', models.PositiveSmallIntegerField(choices=[(10, '10'), (20, '20'), (50, '50')], default=20)),
                ('default_channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Correo')], default='whatsapp', max_length=10)),
                ('show_manual_help', models.BooleanField(default=True)),
                ('navigation_width', models.PositiveSmallIntegerField(default=288, validators=[django.core.validators.MinValueValidator(240), django.core.validators.MaxValueValidator(400)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_panel_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
