# Generated by Django on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_remove_paused_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='document_manager_enabled',
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text=(
                    'Whether this project has an entity space in the document '
                    'manager. Disabling it never deletes an existing folder or '
                    'document.'
                ),
            ),
        ),
    ]
