# Generated by Django 6.1 on 2026-08-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_communicationpanelpreference'),
        ('accounts', '0059_project_document_manager_enabled'),
    ]

    operations = []
