# Generated by Django on 2026-08-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_merge_document_manager_communications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='document_manager_enabled',
        ),
    ]
