# Generated by Django 6.1 on 2026-09-04 23:43

from urllib.parse import urlsplit

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _hostname(value):
    if not value:
        return ''
    try:
        return (urlsplit(value).hostname or '').lower()
    except ValueError:
        return ''


def classify_legacy_project_access(apps, schema_editor):
    """Move legacy credentials only when their environment is unambiguous."""
    Project = apps.get_model('accounts', 'Project')
    ProjectAdminAccess = apps.get_model('accounts', 'ProjectAdminAccess')

    for project in Project.objects.exclude(
        admin_url='', admin_username='', admin_password_encrypted='',
    ).iterator():
        admin_host = _hostname(project.admin_url)
        if not admin_host:
            continue

        matching_environments = []
        if _hostname(project.production_url) == admin_host:
            matching_environments.append('production')
        if _hostname(project.staging_url) == admin_host:
            matching_environments.append('staging')
        if len(matching_environments) != 1:
            continue

        ProjectAdminAccess.objects.create(
            project_id=project.pk,
            environment=matching_environments[0],
            admin_url=project.admin_url,
            admin_username=project.admin_username,
            admin_password_encrypted=project.admin_password_encrypted,
        )
        Project.objects.filter(pk=project.pk).update(
            admin_url='',
            admin_username='',
            admin_password_encrypted='',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_client_archived_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAccessNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_encrypted', models.TextField()),
                ('is_sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_access_notes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_notes', to='accounts.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_access_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAdminAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('production', 'Producción'), ('staging', 'Staging')], max_length=20)),
                ('admin_url', models.URLField(blank=True, default='', max_length=500)),
                ('admin_username', models.CharField(blank=True, default='', max_length=150)),
                ('admin_password_encrypted', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_accesses', to='accounts.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_admin_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['environment'],
                'constraints': [models.UniqueConstraint(fields=('project', 'environment'), name='unique_project_admin_access_environment')],
            },
        ),
        migrations.RunPython(
            classify_legacy_project_access,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
