import {
  ArchiveBoxArrowDownIcon,
  ArrowDownIcon,
  ArrowDownTrayIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowPathRoundedSquareIcon,
  ArrowRightEndOnRectangleIcon,
  ArrowRightIcon,
  ArrowTopRightOnSquareIcon,
  ArrowUpIcon,
  ArrowUpTrayIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  ArrowsPointingInIcon,
  ArrowsPointingOutIcon,
  ArrowsRightLeftIcon,
  ArrowsUpDownIcon,
  BackspaceIcon,
  BanknotesIcon,
  Bars3Icon,
  BarsArrowDownIcon,
  BarsArrowUpIcon,
  BellAlertIcon,
  BellSlashIcon,
  CalendarDaysIcon,
  CalculatorIcon,
  ChartBarIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  CheckCircleIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardDocumentIcon,
  ClipboardDocumentListIcon,
  CloudArrowDownIcon,
  CloudArrowUpIcon,
  ClockIcon,
  Cog6ToothIcon,
  DocumentArrowDownIcon,
  DocumentArrowUpIcon,
  DocumentDuplicateIcon,
  DocumentPlusIcon,
  DocumentTextIcon,
  EllipsisVerticalIcon,
  EnvelopeIcon,
  EyeIcon,
  EyeSlashIcon,
  FlagIcon,
  FolderArrowDownIcon,
  FolderIcon,
  FunnelIcon,
  HandThumbDownIcon,
  HandThumbUpIcon,
  InboxStackIcon,
  LinkIcon,
  LinkSlashIcon,
  ListBulletIcon,
  MagnifyingGlassIcon,
  MagnifyingGlassMinusIcon,
  MagnifyingGlassPlusIcon,
  MinusCircleIcon,
  MoonIcon,
  NoSymbolIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  PauseCircleIcon,
  PencilIcon,
  PencilSquareIcon,
  PlayCircleIcon,
  PlusIcon,
  ReceiptPercentIcon,
  RocketLaunchIcon,
  SparklesIcon,
  Square2StackIcon,
  SunIcon,
  TagIcon,
  TrashIcon,
  UserPlusIcon,
  WindowIcon,
  WrenchScrewdriverIcon,
  XCircleIcon,
  XMarkIcon,
} from '@heroicons/vue/24/outline'

const defineAction = (icon, iconName, label) => Object.freeze({ icon, iconName, label })

/**
 * Canonical visual vocabulary for executable actions inside `/panel/**`.
 *
 * This catalog owns visual identity and the default Spanish name only. Business
 * state, handlers, routes, descriptions and variants remain with the consumer.
 */
export const PANEL_ACTIONS = Object.freeze({
  create: defineAction(PlusIcon, 'PlusIcon', 'Crear'),
  copy: defineAction(DocumentDuplicateIcon, 'DocumentDuplicateIcon', 'Copiar'),
  duplicate: defineAction(Square2StackIcon, 'Square2StackIcon', 'Duplicar'),
  edit: defineAction(PencilSquareIcon, 'PencilSquareIcon', 'Editar'),
  rename: defineAction(PencilIcon, 'PencilIcon', 'Renombrar'),
  delete: defineAction(TrashIcon, 'TrashIcon', 'Eliminar'),
  remove: defineAction(MinusCircleIcon, 'MinusCircleIcon', 'Quitar'),
  close: defineAction(XMarkIcon, 'XMarkIcon', 'Cerrar'),
  clear: defineAction(BackspaceIcon, 'BackspaceIcon', 'Limpiar'),
  more: defineAction(EllipsisVerticalIcon, 'EllipsisVerticalIcon', 'Acciones'),

  download: defineAction(ArrowDownTrayIcon, 'ArrowDownTrayIcon', 'Descargar'),
  export: defineAction(DocumentArrowDownIcon, 'DocumentArrowDownIcon', 'Exportar'),
  upload: defineAction(ArrowUpTrayIcon, 'ArrowUpTrayIcon', 'Subir'),
  import: defineAction(DocumentArrowUpIcon, 'DocumentArrowUpIcon', 'Importar'),
  paste: defineAction(ClipboardDocumentIcon, 'ClipboardDocumentIcon', 'Pegar'),
  attach: defineAction(PaperClipIcon, 'PaperClipIcon', 'Adjuntar'),
  move: defineAction(FolderArrowDownIcon, 'FolderArrowDownIcon', 'Mover'),
  send: defineAction(PaperAirplaneIcon, 'PaperAirplaneIcon', 'Enviar'),
  resend: defineAction(ArrowPathRoundedSquareIcon, 'ArrowPathRoundedSquareIcon', 'Reenviar'),
  'email-history': defineAction(EnvelopeIcon, 'EnvelopeIcon', 'Ver correos'),
  communications: defineAction(InboxStackIcon, 'InboxStackIcon', 'Ver comunicaciones'),
  notes: defineAction(ChatBubbleBottomCenterTextIcon, 'ChatBubbleBottomCenterTextIcon', 'Notas'),
  message: defineAction(ChatBubbleOvalLeftEllipsisIcon, 'ChatBubbleOvalLeftEllipsisIcon', 'Enviar mensaje'),
  'log-activity': defineAction(ClipboardDocumentListIcon, 'ClipboardDocumentListIcon', 'Registrar actividad'),
  'open-external': defineAction(ArrowTopRightOnSquareIcon, 'ArrowTopRightOnSquareIcon', 'Abrir en otra pestaña'),
  link: defineAction(LinkIcon, 'LinkIcon', 'Vincular'),
  unlink: defineAction(LinkSlashIcon, 'LinkSlashIcon', 'Desvincular'),

  archive: defineAction(ArchiveBoxArrowDownIcon, 'ArchiveBoxArrowDownIcon', 'Archivar'),
  restore: defineAction(ArrowUturnLeftIcon, 'ArrowUturnLeftIcon', 'Restaurar'),
  activate: defineAction(PlayCircleIcon, 'PlayCircleIcon', 'Activar'),
  deactivate: defineAction(PauseCircleIcon, 'PauseCircleIcon', 'Desactivar'),
  mute: defineAction(BellSlashIcon, 'BellSlashIcon', 'Silenciar'),
  unmute: defineAction(BellAlertIcon, 'BellAlertIcon', 'Reactivar'),
  complete: defineAction(CheckCircleIcon, 'CheckCircleIcon', 'Completar'),
  void: defineAction(NoSymbolIcon, 'NoSymbolIcon', 'Anular'),
  publish: defineAction(CloudArrowUpIcon, 'CloudArrowUpIcon', 'Publicar'),
  unpublish: defineAction(CloudArrowDownIcon, 'CloudArrowDownIcon', 'Retirar publicación'),
  'change-status': defineAction(ArrowsRightLeftIcon, 'ArrowsRightLeftIcon', 'Cambiar estado'),
  settle: defineAction(BanknotesIcon, 'BanknotesIcon', 'Liquidar'),
  generate: defineAction(DocumentPlusIcon, 'DocumentPlusIcon', 'Generar documento'),
  regenerate: defineAction(SparklesIcon, 'SparklesIcon', 'Regenerar'),
  'billing-cycles': defineAction(ClockIcon, 'ClockIcon', 'Ciclos de pago'),
  'write-off': defineAction(XCircleIcon, 'XCircleIcon', 'Marcar como perdido'),
  negotiate: defineAction(ChatBubbleLeftRightIcon, 'ChatBubbleLeftRightIcon', 'Negociar'),
  approve: defineAction(HandThumbUpIcon, 'HandThumbUpIcon', 'Aprobar'),
  reject: defineAction(HandThumbDownIcon, 'HandThumbDownIcon', 'Rechazar'),
  launch: defineAction(RocketLaunchIcon, 'RocketLaunchIcon', 'Lanzar'),
  finish: defineAction(FlagIcon, 'FlagIcon', 'Finalizar'),
  'discount-offer': defineAction(ReceiptPercentIcon, 'ReceiptPercentIcon', 'Enviar oferta'),
  analyze: defineAction(WrenchScrewdriverIcon, 'WrenchScrewdriverIcon', 'Analizar'),

  view: defineAction(EyeIcon, 'EyeIcon', 'Ver'),
  hide: defineAction(EyeSlashIcon, 'EyeSlashIcon', 'Ocultar'),
  search: defineAction(MagnifyingGlassIcon, 'MagnifyingGlassIcon', 'Buscar'),
  'zoom-in': defineAction(MagnifyingGlassPlusIcon, 'MagnifyingGlassPlusIcon', 'Acercar'),
  'zoom-out': defineAction(MagnifyingGlassMinusIcon, 'MagnifyingGlassMinusIcon', 'Alejar'),
  filter: defineAction(FunnelIcon, 'FunnelIcon', 'Filtrar'),
  refresh: defineAction(ArrowPathIcon, 'ArrowPathIcon', 'Actualizar'),
  retry: defineAction(ArrowUturnRightIcon, 'ArrowUturnRightIcon', 'Reintentar'),
  stats: defineAction(ChartBarIcon, 'ChartBarIcon', 'Ver estadísticas'),
  calendar: defineAction(CalendarDaysIcon, 'CalendarDaysIcon', 'Abrir calendario'),
  calculate: defineAction(CalculatorIcon, 'CalculatorIcon', 'Calcular'),
  list: defineAction(ListBulletIcon, 'ListBulletIcon', 'Ver listado'),
  settings: defineAction(Cog6ToothIcon, 'Cog6ToothIcon', 'Configuración'),
  tags: defineAction(TagIcon, 'TagIcon', 'Gestionar etiquetas'),
  folders: defineAction(FolderIcon, 'FolderIcon', 'Carpetas'),
  documents: defineAction(DocumentTextIcon, 'DocumentTextIcon', 'Documentos'),
  previous: defineAction(ChevronLeftIcon, 'ChevronLeftIcon', 'Anterior'),
  next: defineAction(ChevronRightIcon, 'ChevronRightIcon', 'Siguiente'),
  expand: defineAction(ChevronDownIcon, 'ChevronDownIcon', 'Expandir'),
  collapse: defineAction(ChevronUpIcon, 'ChevronUpIcon', 'Contraer'),
  'move-up': defineAction(ArrowUpIcon, 'ArrowUpIcon', 'Mover arriba'),
  'move-down': defineAction(ArrowDownIcon, 'ArrowDownIcon', 'Mover abajo'),
  sort: defineAction(ArrowsUpDownIcon, 'ArrowsUpDownIcon', 'Ordenar'),
  'sort-ascending': defineAction(BarsArrowUpIcon, 'BarsArrowUpIcon', 'Orden ascendente'),
  'sort-descending': defineAction(BarsArrowDownIcon, 'BarsArrowDownIcon', 'Orden descendente'),
  'enter-fullscreen': defineAction(ArrowsPointingOutIcon, 'ArrowsPointingOutIcon', 'Pantalla completa'),
  'exit-fullscreen': defineAction(ArrowsPointingInIcon, 'ArrowsPointingInIcon', 'Salir de pantalla completa'),

  'open-navigation': defineAction(Bars3Icon, 'Bars3Icon', 'Abrir navegación'),
  'collapse-sidebar': defineAction(ChevronDoubleLeftIcon, 'ChevronDoubleLeftIcon', 'Contraer barra lateral'),
  'expand-sidebar': defineAction(ChevronDoubleRightIcon, 'ChevronDoubleRightIcon', 'Expandir barra lateral'),
  'enable-dark-theme': defineAction(MoonIcon, 'MoonIcon', 'Activar tema oscuro'),
  'enable-light-theme': defineAction(SunIcon, 'SunIcon', 'Activar tema claro'),
  'open-platform': defineAction(WindowIcon, 'WindowIcon', 'Abrir plataforma'),
  'add-user': defineAction(UserPlusIcon, 'UserPlusIcon', 'Agregar usuario'),
  'login-as': defineAction(ArrowRightEndOnRectangleIcon, 'ArrowRightEndOnRectangleIcon', 'Ingresar como usuario'),
  back: defineAction(ArrowLeftIcon, 'ArrowLeftIcon', 'Volver'),
  forward: defineAction(ArrowRightIcon, 'ArrowRightIcon', 'Continuar'),
})

export const PANEL_ACTION_KEYS = Object.freeze(Object.keys(PANEL_ACTIONS))

export function getPanelAction(action) {
  const definition = PANEL_ACTIONS[action]
  if (!definition) throw new Error(`[panelActions] Unknown panel action: ${action}`)
  return definition
}

export function createPanelActionItem(action, options = {}) {
  if (Object.hasOwn(options, 'icon') || Object.hasOwn(options, 'iconName')) {
    throw new Error(`[panelActions] ${action} cannot override its canonical icon`)
  }
  const definition = getPanelAction(action)
  return { action, label: definition.label, ...options }
}
