export const viewCatalogSections = [
  {
    id: 'public-site',
    label: 'Sitio publico',
    description: 'Vistas publicas de marketing, contenido y paginas legales.',
    views: [
      {
        label: 'Inicio',
        url: '/',
        group: 'Landing y marketing',
        file: 'frontend/pages/index.vue',
        reference: 'vista publica de inicio',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Landing de apps',
        url: '/landing-apps',
        group: 'Landing y marketing',
        file: 'frontend/pages/landing-apps.vue',
        reference: 'vista publica de landing de apps',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Landing de software',
        url: '/landing-software',
        group: 'Landing y marketing',
        file: 'frontend/pages/landing-software.vue',
        reference: 'vista publica de landing de software',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Landing de diseno web',
        url: '/landing-web-design',
        group: 'Landing y marketing',
        file: 'frontend/pages/landing-web-design.vue',
        reference: 'vista publica de landing de diseno web',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Sobre nosotros',
        url: '/about-us',
        group: 'Landing y marketing',
        file: 'frontend/pages/about-us.vue',
        reference: 'vista publica de sobre nosotros',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Contacto',
        url: '/contact',
        group: 'Contacto',
        file: 'frontend/pages/contact.vue',
        reference: 'vista publica de contacto',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Contacto exitoso',
        url: '/contact-success',
        group: 'Contacto',
        file: 'frontend/pages/contact-success.vue',
        reference: 'vista publica de confirmacion de contacto',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Portafolio',
        url: '/portfolio-works',
        group: 'Portafolio',
        file: 'frontend/pages/portfolio-works/index.vue',
        reference: 'vista publica de portafolio',
        audience: 'public',
        viewType: 'list',
      },
      {
        label: 'Detalle de portafolio',
        url: '/portfolio-works/:slug',
        group: 'Portafolio',
        file: 'frontend/pages/portfolio-works/[slug].vue',
        reference: 'vista publica de detalle de portafolio',
        audience: 'public',
        viewType: 'detail',
      },
      {
        label: 'Blog',
        url: '/blog',
        group: 'Blog',
        file: 'frontend/pages/blog/index.vue',
        reference: 'vista publica de blog',
        audience: 'public',
        viewType: 'list',
      },
      {
        label: 'Detalle de blog',
        url: '/blog/:slug',
        group: 'Blog',
        file: 'frontend/pages/blog/[slug].vue',
        reference: 'vista publica de articulo del blog',
        audience: 'public',
        viewType: 'detail',
      },
      {
        label: 'Politica de privacidad',
        url: '/privacy-policy',
        group: 'Legal',
        file: 'frontend/pages/privacy-policy.vue',
        reference: 'vista publica de politica de privacidad',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Terminos y condiciones',
        url: '/terms-and-conditions',
        group: 'Legal',
        file: 'frontend/pages/terms-and-conditions.vue',
        reference: 'vista publica de terminos y condiciones',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Callback de LinkedIn',
        url: '/auth/linkedin/callback',
        group: 'Sistema',
        file: 'frontend/pages/auth/linkedin/callback.vue',
        reference: 'vista de callback de autenticacion de LinkedIn',
        audience: 'public',
        viewType: 'auth',
      },
      {
        label: 'Fallback / ruta no encontrada',
        url: '/:slug*',
        group: 'Sistema',
        file: 'frontend/pages/[...slug].vue',
        reference: 'vista fallback para rutas no encontradas',
        audience: 'public',
        viewType: 'readonly',
      },
    ],
  },
  {
    id: 'public-proposals',
    label: 'Propuestas publicas',
    description: 'Vistas que ve el cliente al abrir una propuesta compartida.',
    views: [
      {
        label: 'Propuesta publica',
        url: '/proposal/:uuid',
        group: 'Propuestas',
        file: 'frontend/pages/proposal/[uuid]/index.vue',
        reference: 'vista publica de propuesta',
        notes: 'Admite ?mode=detailed, ?mode=executive y ?mode=technical para abrir modos especificos.',
        audience: 'public',
        viewType: 'detail',
      },
    ],
  },
  {
    id: 'public-diagnostics',
    label: 'Diagnósticos públicos',
    description: 'Vistas que ve el cliente al abrir un diagnóstico compartido.',
    views: [
      {
        label: 'Diagnóstico público',
        url: '/diagnostic/:uuid',
        group: 'Diagnósticos',
        file: 'frontend/pages/diagnostic/[uuid]/index.vue',
        reference: 'vista publica de diagnostico',
        audience: 'public',
        viewType: 'detail',
      },
    ],
  },
  {
    id: 'admin-panel',
    label: 'Panel administrativo',
    description: 'Vistas internas del panel para gestionar propuestas, contenido, documentos y usuarios admin.',
    views: [
      {
        label: 'Login del panel',
        url: '/panel/login',
        group: 'Acceso y dashboard',
        file: 'frontend/pages/panel/login.vue',
        reference: 'vista de login del panel',
        audience: 'admin',
        viewType: 'auth',
      },
      {
        label: 'Dashboard del panel',
        url: '/panel',
        group: 'Acceso y dashboard',
        file: 'frontend/pages/panel/index.vue',
        reference: 'vista dashboard del panel',
        audience: 'admin',
        viewType: 'dashboard',
      },
      {
        label: 'Mapa de vistas',
        url: '/panel/views',
        group: 'Referencia',
        file: 'frontend/pages/panel/views.vue',
        reference: 'vista de mapa de vistas del panel',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'Listado de propuestas',
        url: '/panel/proposals',
        group: 'Propuestas',
        file: 'frontend/pages/panel/proposals/index.vue',
        reference: 'vista listado de propuestas del panel',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Crear propuesta',
        url: '/panel/proposals/create',
        group: 'Propuestas',
        file: 'frontend/pages/panel/proposals/create.vue',
        reference: 'vista de creacion de propuesta del panel',
        audience: 'admin',
        viewType: 'create',
      },
      {
        label: 'Editar / detalle de propuesta',
        url: '/panel/proposals/:id/edit',
        group: 'Propuestas',
        file: 'frontend/pages/panel/proposals/[id]/edit.vue',
        reference: 'vista de edicion/detalle de propuesta del panel',
        notes: 'Usa el id interno de la propuesta, no el uuid publico.',
        audience: 'admin',
        viewType: 'edit',
      },
      {
        label: 'Valores por defecto (propuestas y diagnósticos)',
        url: '/panel/defaults',
        group: 'Configuración',
        file: 'frontend/pages/panel/defaults.vue',
        reference: 'vista unificada de valores por defecto con switch propuesta/diagnóstico',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'Design System Styleguide',
        url: '/panel/styleguide',
        group: 'Referencia',
        file: 'frontend/pages/panel/styleguide.vue',
        reference: 'catálogo visual de tokens semánticos y componentes base (BaseInput, BaseButton, BaseModal, etc.) en light y dark',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'Plantillas de email de propuestas',
        url: '/panel/proposals/email-templates',
        group: 'Propuestas',
        file: 'frontend/pages/panel/proposals/email-templates.vue',
        reference: 'stub de redirección hacia los defaults unificados',
        audience: 'admin',
        viewType: 'redirect',
        notes: 'Redirige a /panel/defaults?mode=proposal&tab=emails.',
      },
      {
        label: 'Entregabilidad de email',
        url: '/panel/proposals/email-deliverability',
        group: 'Propuestas',
        file: 'frontend/pages/panel/proposals/email-deliverability.vue',
        reference: 'vista de entregabilidad de email de propuestas',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'Defaults de propuestas',
        url: '/panel/proposals/defaults',
        group: 'Propuestas',
        file: 'frontend/pages/panel/proposals/defaults.vue',
        reference: 'stub de redirección hacia los defaults unificados',
        audience: 'admin',
        viewType: 'redirect',
        notes: 'Redirige a /panel/defaults?mode=proposal.',
      },
      {
        label: 'Clientes',
        url: '/panel/clients',
        group: 'Clientes',
        file: 'frontend/pages/panel/clients/index.vue',
        reference: 'vista de clientes del panel',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Blog del panel',
        url: '/panel/blog',
        group: 'Blog',
        file: 'frontend/pages/panel/blog/index.vue',
        reference: 'vista listado de blog del panel',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Crear post de blog',
        url: '/panel/blog/create',
        group: 'Blog',
        file: 'frontend/pages/panel/blog/create.vue',
        reference: 'vista de creacion de post de blog',
        audience: 'admin',
        viewType: 'create',
      },
      {
        label: 'Editar post de blog',
        url: '/panel/blog/:id/edit',
        group: 'Blog',
        file: 'frontend/pages/panel/blog/[id]/edit.vue',
        reference: 'vista de edicion de post de blog',
        audience: 'admin',
        viewType: 'edit',
      },
      {
        label: 'Calendario de blog',
        url: '/panel/blog/calendar',
        group: 'Blog',
        file: 'frontend/pages/panel/blog/calendar.vue',
        reference: 'vista de calendario de blog',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'LinkedIn del panel',
        url: '/panel/linkedin',
        group: 'LinkedIn',
        file: 'frontend/pages/panel/linkedin/index.vue',
        reference: 'modulo de posts de LinkedIn (crear, programar, publicar)',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Portafolio del panel',
        url: '/panel/portfolio',
        group: 'Portafolio',
        file: 'frontend/pages/panel/portfolio/index.vue',
        reference: 'vista listado de portafolio del panel',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Crear item de portafolio',
        url: '/panel/portfolio/create',
        group: 'Portafolio',
        file: 'frontend/pages/panel/portfolio/create.vue',
        reference: 'vista de creacion de item de portafolio',
        audience: 'admin',
        viewType: 'create',
      },
      {
        label: 'Editar item de portafolio',
        url: '/panel/portfolio/:id/edit',
        group: 'Portafolio',
        file: 'frontend/pages/panel/portfolio/[id]/edit.vue',
        reference: 'vista de edicion de item de portafolio',
        audience: 'admin',
        viewType: 'edit',
      },
      {
        label: 'Paquetes de horas',
        url: '/panel/hour-packages',
        group: 'Paquetes de horas',
        file: 'frontend/pages/panel/hour-packages/index.vue',
        reference: 'catalogo de paquetes de desarrollo por horas por nacionalidad (COL/MEX/USA)',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Crear paquete de horas',
        url: '/panel/hour-packages/create',
        group: 'Paquetes de horas',
        file: 'frontend/pages/panel/hour-packages/create.vue',
        reference: 'vista de creacion de paquete de horas',
        audience: 'admin',
        viewType: 'create',
      },
      {
        label: 'Editar paquete de horas',
        url: '/panel/hour-packages/:id/edit',
        group: 'Paquetes de horas',
        file: 'frontend/pages/panel/hour-packages/[id]/edit.vue',
        reference: 'vista de edicion de paquete de horas',
        audience: 'admin',
        viewType: 'edit',
      },
      {
        label: 'Documentos PDF',
        url: '/panel/documents',
        group: 'Documentos',
        file: 'frontend/pages/panel/documents/index.vue',
        reference: 'vista listado de documentos PDF',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Crear documento PDF',
        url: '/panel/documents/create',
        group: 'Documentos',
        file: 'frontend/pages/panel/documents/create.vue',
        reference: 'vista de creacion de documento PDF',
        audience: 'admin',
        viewType: 'create',
      },
      {
        label: 'Editar documento PDF',
        url: '/panel/documents/:id/edit',
        group: 'Documentos',
        file: 'frontend/pages/panel/documents/[id]/edit.vue',
        reference: 'vista de edicion de documento PDF',
        audience: 'admin',
        viewType: 'edit',
      },
      {
        label: 'Admins del panel',
        url: '/panel/admins',
        group: 'Configuración',
        file: 'frontend/pages/panel/admins/index.vue',
        reference: 'vista de administradores del panel',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'Emails',
        url: '/panel/emails',
        group: 'Emails',
        file: 'frontend/pages/panel/emails/index.vue',
        reference: 'vista de envío de emails con branding del panel',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'Diagnosticos de aplicaciones',
        url: '/panel/diagnostics',
        group: 'Diagnósticos',
        file: 'frontend/pages/panel/diagnostics/index.vue',
        reference: 'vista listado de diagnosticos de aplicaciones del panel',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Crear diagnostico',
        url: '/panel/diagnostics/create',
        group: 'Diagnósticos',
        file: 'frontend/pages/panel/diagnostics/create.vue',
        reference: 'vista de creacion de diagnostico de aplicacion',
        audience: 'admin',
        viewType: 'create',
      },
      {
        label: 'Editar / detalle de diagnostico',
        url: '/panel/diagnostics/:id/edit',
        group: 'Diagnósticos',
        file: 'frontend/pages/panel/diagnostics/[id]/edit.vue',
        reference: 'vista de edicion/detalle de diagnostico del panel',
        audience: 'admin',
        viewType: 'edit',
      },
      {
        label: 'Defaults de diagnostico',
        url: '/panel/diagnostics/defaults',
        group: 'Diagnósticos',
        file: 'frontend/pages/panel/diagnostics/defaults.vue',
        reference: 'stub de redirección hacia los defaults unificados',
        audience: 'admin',
        viewType: 'redirect',
        notes: 'Redirige a /panel/defaults?mode=diagnostic.',
      },
      {
        label: 'Tasks',
        url: '/panel/tasks',
        group: 'Tareas',
        file: 'frontend/pages/panel/tasks/index.vue',
        reference: 'vista de tablero kanban de tareas internas del panel',
        audience: 'admin',
        viewType: 'list',
      },
    ],
  },
  {
    id: 'panel-accounting',
    label: 'Contabilidad (panel)',
    description: 'Modulo contable interno de la empresa, solo superusuarios.',
    views: [
      {
        label: 'Contabilidad — Resumen',
        url: '/panel/accounting',
        group: 'Panorama',
        file: 'frontend/pages/panel/accounting/index.vue',
        reference: 'vista dashboard del modulo contable del panel',
        audience: 'admin',
        viewType: 'dashboard',
      },
      {
        label: 'Contabilidad — Ingresos',
        url: '/panel/accounting/incomes',
        group: 'Movimientos',
        file: 'frontend/pages/panel/accounting/incomes.vue',
        reference: 'vista de ingresos esperados y liquidos del modulo contable',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Contabilidad — Gastos',
        url: '/panel/accounting/expenses',
        group: 'Movimientos',
        file: 'frontend/pages/panel/accounting/expenses.vue',
        reference: 'vista de gastos del modulo contable',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Contabilidad — Hostings',
        url: '/panel/accounting/hostings',
        group: 'Recurrentes y hostings',
        file: 'frontend/pages/panel/accounting/hostings.vue',
        reference: 'vista de hostings activos por cliente del modulo contable',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Contabilidad — Bolsillo',
        url: '/panel/accounting/pocket',
        group: 'Movimientos',
        file: 'frontend/pages/panel/accounting/pocket.vue',
        reference: 'vista del bolsillo ProjectApp con movimientos y saldo',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Contabilidad — Recurrentes',
        url: '/panel/accounting/recurring',
        group: 'Recurrentes y hostings',
        file: 'frontend/pages/panel/accounting/recurring.vue',
        reference: 'vista de pagos frecuentes mensuales del modulo contable',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Contabilidad — Ads',
        url: '/panel/accounting/ads',
        group: 'Movimientos',
        file: 'frontend/pages/panel/accounting/ads.vue',
        reference: 'vista del registro de gastos en ads del modulo contable',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Contabilidad — Tarjetas',
        url: '/panel/accounting/cards',
        group: 'Movimientos',
        file: 'frontend/pages/panel/accounting/cards.vue',
        reference: 'vista de cortes semanales de tarjetas de credito del modulo contable',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Contabilidad — Historial',
        url: '/panel/accounting/history',
        group: 'Panorama',
        file: 'frontend/pages/panel/accounting/history.vue',
        reference: 'vista del log historico de cambios del modulo contable',
        audience: 'admin',
        viewType: 'readonly',
      },
      {
        label: 'Contabilidad — Configuración',
        url: '/panel/accounting/settings',
        group: 'Panorama',
        file: 'frontend/pages/panel/accounting/settings.vue',
        reference: 'vista de configuracion de notificaciones del modulo contable',
        audience: 'admin',
        viewType: 'config',
      },
    ],
  },
  {
    id: 'panel-mcps',
    label: 'MCPs (panel)',
    description: 'Gestion de conectores MCP para Claude, solo superusuarios.',
    views: [
      {
        label: 'MCPs — Conectores',
        url: '/panel/mcps',
        group: 'Conectores',
        file: 'frontend/pages/panel/mcps/index.vue',
        reference: 'vista de gestion de conectores MCP del panel',
        audience: 'admin',
        viewType: 'config',
      },
    ],
  },
  {
    id: 'client-platform',
    label: 'Plataforma de clientes',
    description: 'Vistas del portal autenticado para clientes y administradores de proyecto.',
    views: [
      {
        label: 'Entrada de plataforma',
        url: '/platform',
        group: 'Acceso',
        file: 'frontend/pages/platform/index.vue',
        reference: 'vista de entrada de plataforma',
        audience: 'client',
        viewType: 'auth',
      },
      {
        label: 'Login de plataforma',
        url: '/platform/login',
        group: 'Acceso',
        file: 'frontend/pages/platform/login.vue',
        reference: 'vista de login de plataforma',
        audience: 'client',
        viewType: 'auth',
      },
      {
        label: 'Verificacion de plataforma',
        url: '/platform/verify',
        group: 'Acceso',
        file: 'frontend/pages/platform/verify.vue',
        reference: 'vista de verificacion de plataforma',
        audience: 'client',
        viewType: 'auth',
      },
      {
        label: 'Completar perfil',
        url: '/platform/complete-profile',
        group: 'Acceso',
        file: 'frontend/pages/platform/complete-profile.vue',
        reference: 'vista de completar perfil de plataforma',
        audience: 'client',
        viewType: 'auth',
      },
      {
        label: 'Notificaciones',
        url: '/platform/notifications',
        group: 'Cuenta',
        file: 'frontend/pages/platform/notifications.vue',
        reference: 'vista de notificaciones de plataforma',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Perfil',
        url: '/platform/profile',
        group: 'Cuenta',
        file: 'frontend/pages/platform/profile.vue',
        reference: 'vista de perfil de plataforma',
        audience: 'client',
        viewType: 'config',
      },
      {
        label: 'Proyectos',
        url: '/platform/projects',
        group: 'Proyectos',
        file: 'frontend/pages/platform/projects/index.vue',
        reference: 'vista listado de proyectos de plataforma',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Detalle de proyecto',
        url: '/platform/projects/:id',
        group: 'Proyectos',
        file: 'frontend/pages/platform/projects/[id]/index.vue',
        reference: 'vista de detalle de proyecto de plataforma',
        audience: 'client',
        viewType: 'detail',
      },
      {
        label: 'Tablero de proyecto',
        url: '/platform/projects/:id/board',
        group: 'Proyectos',
        file: 'frontend/pages/platform/projects/[id]/board.vue',
        reference: 'vista de tablero de proyecto',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Bugs de proyecto',
        url: '/platform/projects/:id/bugs',
        group: 'Proyectos',
        file: 'frontend/pages/platform/projects/[id]/bugs.vue',
        reference: 'vista de bugs de proyecto',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Cambios de proyecto',
        url: '/platform/projects/:id/changes',
        group: 'Proyectos',
        file: 'frontend/pages/platform/projects/[id]/changes.vue',
        reference: 'vista de cambios de proyecto',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Cuentas de cobro de proyecto',
        url: '/platform/projects/:id/collection-accounts',
        group: 'Proyectos',
        file: 'frontend/pages/platform/projects/[id]/collection-accounts.vue',
        reference: 'vista de cuentas de cobro de proyecto',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Modelo de datos de proyecto',
        url: '/platform/projects/:id/data-model',
        group: 'Proyectos',
        file: 'frontend/pages/platform/projects/[id]/data-model.vue',
        reference: 'vista de modelo de datos de proyecto',
        audience: 'client',
        viewType: 'detail',
      },
      {
        label: 'Entregables de proyecto',
        url: '/platform/projects/:id/deliverables',
        group: 'Proyectos',
        file: 'frontend/pages/platform/projects/[id]/deliverables/index.vue',
        reference: 'vista de entregables de proyecto',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Detalle de entregable',
        url: '/platform/projects/:id/deliverables/:deliverableId',
        group: 'Proyectos',
        file: 'frontend/pages/platform/projects/[id]/deliverables/[deliverableId]/index.vue',
        reference: 'vista de detalle de entregable',
        audience: 'client',
        viewType: 'detail',
      },
      {
        label: 'Pagos de proyecto',
        url: '/platform/projects/:id/payments',
        group: 'Proyectos',
        file: 'frontend/pages/platform/projects/[id]/payments.vue',
        reference: 'vista de pagos de proyecto',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Clientes de plataforma',
        url: '/platform/clients',
        group: 'Clientes',
        file: 'frontend/pages/platform/clients/index.vue',
        reference: 'vista listado de clientes de plataforma',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Detalle de cliente de plataforma',
        url: '/platform/clients/:id',
        group: 'Clientes',
        file: 'frontend/pages/platform/clients/[id].vue',
        reference: 'vista de detalle de cliente de plataforma',
        audience: 'admin',
        viewType: 'detail',
      },
      {
        label: 'Accesos del proyecto',
        url: '/platform/projects/:id/access',
        group: 'Proyectos',
        file: 'frontend/pages/platform/projects/[id]/access.vue',
        reference: 'credenciales por proyecto',
        audience: 'admin',
        viewType: 'readonly',
      },
      {
        label: 'Login de administrador (impersonación)',
        url: '/platform/admin-login',
        group: 'Acceso',
        file: 'frontend/pages/platform/admin-login.vue',
        reference: 'vista de login de administrador via impersonacion',
        audience: 'client',
        viewType: 'auth',
      },
      {
        label: 'Olvide mi contraseña',
        url: '/platform/forgot-password',
        group: 'Acceso',
        file: 'frontend/pages/platform/forgot-password.vue',
        reference: 'vista de recuperacion de contrasena de plataforma',
        audience: 'client',
        viewType: 'auth',
      },
      {
        label: 'Restablecer contraseña',
        url: '/platform/reset-password',
        group: 'Acceso',
        file: 'frontend/pages/platform/reset-password.vue',
        reference: 'vista para definir nueva contrasena de plataforma',
        audience: 'client',
        viewType: 'auth',
      },
      {
        label: 'Verificar código',
        url: '/platform/verify-code',
        group: 'Acceso',
        file: 'frontend/pages/platform/verify-code.vue',
        reference: 'vista de verificacion de codigo de plataforma',
        audience: 'client',
        viewType: 'auth',
      },
    ],
  },
]

export const proposalViewReferenceGuide = [
  {
    label: 'Propuesta dentro del panel',
    recommendedName: 'vista de edicion/detalle de propuesta del panel',
    url: '/panel/proposals/:id/edit',
    file: 'frontend/pages/panel/proposals/[id]/edit.vue',
    description: 'Usala para referirte a la pantalla interna donde el admin edita la propuesta, revisa analitica, documentos, emails y secciones.',
  },
  {
    label: 'Propuesta que ve el cliente',
    recommendedName: 'vista publica de propuesta',
    url: '/proposal/:uuid',
    file: 'frontend/pages/proposal/[uuid]/index.vue',
    description: 'Usala para referirte al enlace compartido con el cliente. Esta ruta usa uuid publico.',
  },
  {
    label: 'Modo especifico de la propuesta publica',
    recommendedName: 'vista publica de propuesta en modo detallado, ejecutivo o tecnico',
    url: '/proposal/:uuid?mode=detailed|executive|technical',
    file: 'frontend/pages/proposal/[uuid]/index.vue',
    description: 'Usala cuando el problema depende del modo seleccionado en la propuesta publica.',
  },
]

export function countCatalogViews(sections = viewCatalogSections) {
  return sections.reduce((count, section) => count + section.views.length, 0)
}

export function getViewCopyReference(sectionLabel, view) {
  return `[${sectionLabel}] ${view.label} \u2014 ${view.url}`
}

export function groupSectionViews(section) {
  const groups = []
  const byName = new Map()
  for (const view of section.views) {
    const name = view.group || 'General'
    let entry = byName.get(name)
    if (!entry) {
      entry = { group: name, views: [] }
      byName.set(name, entry)
      groups.push(entry)
    }
    entry.views.push(view)
  }
  return groups
}

export function isOpenableViewUrl(url) {
  return !url.includes(':')
}
