export const viewCatalogSections = [
  {
    id: 'public-site',
    label: 'Sitio publico',
    description: 'Vistas publicas de marketing, contenido y paginas legales.',
    views: [
      {
        label: 'Inicio',
        url: '/',
        file: 'frontend/pages/index.vue',
        reference: 'vista publica de inicio',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Landing de apps',
        url: '/landing-apps',
        file: 'frontend/pages/landing-apps.vue',
        reference: 'vista publica de landing de apps',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Landing de software',
        url: '/landing-software',
        file: 'frontend/pages/landing-software.vue',
        reference: 'vista publica de landing de software',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Landing de diseno web',
        url: '/landing-web-design',
        file: 'frontend/pages/landing-web-design.vue',
        reference: 'vista publica de landing de diseno web',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Sobre nosotros',
        url: '/about-us',
        file: 'frontend/pages/about-us.vue',
        reference: 'vista publica de sobre nosotros',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Contacto',
        url: '/contact',
        file: 'frontend/pages/contact.vue',
        reference: 'vista publica de contacto',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Contacto exitoso',
        url: '/contact-success',
        file: 'frontend/pages/contact-success.vue',
        reference: 'vista publica de confirmacion de contacto',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Portafolio',
        url: '/portfolio-works',
        file: 'frontend/pages/portfolio-works/index.vue',
        reference: 'vista publica de portafolio',
        audience: 'public',
        viewType: 'list',
      },
      {
        label: 'Detalle de portafolio',
        url: '/portfolio-works/:slug',
        file: 'frontend/pages/portfolio-works/[slug].vue',
        reference: 'vista publica de detalle de portafolio',
        audience: 'public',
        viewType: 'detail',
      },
      {
        label: 'Blog',
        url: '/blog',
        file: 'frontend/pages/blog/index.vue',
        reference: 'vista publica de blog',
        audience: 'public',
        viewType: 'list',
      },
      {
        label: 'Detalle de blog',
        url: '/blog/:slug',
        file: 'frontend/pages/blog/[slug].vue',
        reference: 'vista publica de articulo del blog',
        audience: 'public',
        viewType: 'detail',
      },
      {
        label: 'Politica de privacidad',
        url: '/privacy-policy',
        file: 'frontend/pages/privacy-policy.vue',
        reference: 'vista publica de politica de privacidad',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Terminos y condiciones',
        url: '/terms-and-conditions',
        file: 'frontend/pages/terms-and-conditions.vue',
        reference: 'vista publica de terminos y condiciones',
        audience: 'public',
        viewType: 'readonly',
      },
      {
        label: 'Callback de LinkedIn',
        url: '/auth/linkedin/callback',
        file: 'frontend/pages/auth/linkedin/callback.vue',
        reference: 'vista de callback de autenticacion de LinkedIn',
        audience: 'public',
        viewType: 'auth',
      },
      {
        label: 'Fallback / ruta no encontrada',
        url: '/:slug*',
        file: 'frontend/pages/[...slug].vue',
        reference: 'vista fallback para rutas no encontradas',
        audience: 'public',
        viewType: 'readonly',
      },
    ],
  },
  {
    id: 'public-proposals',
    label: 'Propuestas publicas',
    description: 'Vistas que ve el cliente al abrir una propuesta compartida.',
    views: [
      {
        label: 'Propuesta publica',
        url: '/proposal/:uuid',
        file: 'frontend/pages/proposal/[uuid]/index.vue',
        reference: 'vista publica de propuesta',
        notes: 'Admite ?mode=detailed, ?mode=executive y ?mode=technical para abrir modos especificos.',
        audience: 'public',
        viewType: 'detail',
      },
    ],
  },
  {
    id: 'admin-panel',
    label: 'Panel administrativo',
    description: 'Vistas internas del panel para gestionar propuestas, contenido, documentos y usuarios admin.',
    views: [
      {
        label: 'Login del panel',
        url: '/panel/login',
        file: 'frontend/pages/panel/login.vue',
        reference: 'vista de login del panel',
        audience: 'admin',
        viewType: 'auth',
      },
      {
        label: 'Dashboard del panel',
        url: '/panel',
        file: 'frontend/pages/panel/index.vue',
        reference: 'vista dashboard del panel',
        audience: 'admin',
        viewType: 'dashboard',
      },
      {
        label: 'Mapa de vistas',
        url: '/panel/views',
        file: 'frontend/pages/panel/views.vue',
        reference: 'vista de mapa de vistas del panel',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'Listado de propuestas',
        url: '/panel/proposals',
        file: 'frontend/pages/panel/proposals/index.vue',
        reference: 'vista listado de propuestas del panel',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Crear propuesta',
        url: '/panel/proposals/create',
        file: 'frontend/pages/panel/proposals/create.vue',
        reference: 'vista de creacion de propuesta del panel',
        audience: 'admin',
        viewType: 'create',
      },
      {
        label: 'Editar / detalle de propuesta',
        url: '/panel/proposals/:id/edit',
        file: 'frontend/pages/panel/proposals/[id]/edit.vue',
        reference: 'vista de edicion/detalle de propuesta del panel',
        notes: 'Usa el id interno de la propuesta, no el uuid publico.',
        audience: 'admin',
        viewType: 'edit',
      },
      {
        label: 'Valores por defecto de propuestas',
        url: '/panel/proposals/defaults',
        file: 'frontend/pages/panel/proposals/defaults.vue',
        reference: 'vista de valores por defecto de propuestas',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'Plantillas de email de propuestas',
        url: '/panel/proposals/email-templates',
        file: 'frontend/pages/panel/proposals/email-templates.vue',
        reference: 'vista de plantillas de email de propuestas',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'Entregabilidad de email',
        url: '/panel/proposals/email-deliverability',
        file: 'frontend/pages/panel/proposals/email-deliverability.vue',
        reference: 'vista de entregabilidad de email de propuestas',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'Clientes',
        url: '/panel/clients',
        file: 'frontend/pages/panel/clients/index.vue',
        reference: 'vista de clientes del panel',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Blog del panel',
        url: '/panel/blog',
        file: 'frontend/pages/panel/blog/index.vue',
        reference: 'vista listado de blog del panel',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Crear post de blog',
        url: '/panel/blog/create',
        file: 'frontend/pages/panel/blog/create.vue',
        reference: 'vista de creacion de post de blog',
        audience: 'admin',
        viewType: 'create',
      },
      {
        label: 'Editar post de blog',
        url: '/panel/blog/:id/edit',
        file: 'frontend/pages/panel/blog/[id]/edit.vue',
        reference: 'vista de edicion de post de blog',
        audience: 'admin',
        viewType: 'edit',
      },
      {
        label: 'Calendario de blog',
        url: '/panel/blog/calendar',
        file: 'frontend/pages/panel/blog/calendar.vue',
        reference: 'vista de calendario de blog',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'Portafolio del panel',
        url: '/panel/portfolio',
        file: 'frontend/pages/panel/portfolio/index.vue',
        reference: 'vista listado de portafolio del panel',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Crear item de portafolio',
        url: '/panel/portfolio/create',
        file: 'frontend/pages/panel/portfolio/create.vue',
        reference: 'vista de creacion de item de portafolio',
        audience: 'admin',
        viewType: 'create',
      },
      {
        label: 'Editar item de portafolio',
        url: '/panel/portfolio/:id/edit',
        file: 'frontend/pages/panel/portfolio/[id]/edit.vue',
        reference: 'vista de edicion de item de portafolio',
        audience: 'admin',
        viewType: 'edit',
      },
      {
        label: 'Documentos PDF',
        url: '/panel/documents',
        file: 'frontend/pages/panel/documents/index.vue',
        reference: 'vista listado de documentos PDF',
        audience: 'admin',
        viewType: 'list',
      },
      {
        label: 'Crear documento PDF',
        url: '/panel/documents/create',
        file: 'frontend/pages/panel/documents/create.vue',
        reference: 'vista de creacion de documento PDF',
        audience: 'admin',
        viewType: 'create',
      },
      {
        label: 'Editar documento PDF',
        url: '/panel/documents/:id/edit',
        file: 'frontend/pages/panel/documents/[id]/edit.vue',
        reference: 'vista de edicion de documento PDF',
        audience: 'admin',
        viewType: 'edit',
      },
      {
        label: 'Admins del panel',
        url: '/panel/admins',
        file: 'frontend/pages/panel/admins/index.vue',
        reference: 'vista de administradores del panel',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'Emails',
        url: '/panel/emails',
        file: 'frontend/pages/panel/emails/index.vue',
        reference: 'vista de envío de emails con branding del panel',
        audience: 'admin',
        viewType: 'config',
      },
      {
        label: 'Tareas',
        url: '/panel/tareas',
        file: 'frontend/pages/panel/tareas/index.vue',
        reference: 'vista de tablero kanban de tareas internas del panel',
        audience: 'admin',
        viewType: 'list',
      },
    ],
  },
  {
    id: 'client-platform',
    label: 'Plataforma de clientes',
    description: 'Vistas del portal autenticado para clientes y administradores de proyecto.',
    views: [
      {
        label: 'Entrada de plataforma',
        url: '/platform',
        file: 'frontend/pages/platform/index.vue',
        reference: 'vista de entrada de plataforma',
        audience: 'client',
        viewType: 'auth',
      },
      {
        label: 'Login de plataforma',
        url: '/platform/login',
        file: 'frontend/pages/platform/login.vue',
        reference: 'vista de login de plataforma',
        audience: 'client',
        viewType: 'auth',
      },
      {
        label: 'Verificacion de plataforma',
        url: '/platform/verify',
        file: 'frontend/pages/platform/verify.vue',
        reference: 'vista de verificacion de plataforma',
        audience: 'client',
        viewType: 'auth',
      },
      {
        label: 'Completar perfil',
        url: '/platform/complete-profile',
        file: 'frontend/pages/platform/complete-profile.vue',
        reference: 'vista de completar perfil de plataforma',
        audience: 'client',
        viewType: 'auth',
      },
      {
        label: 'Dashboard de plataforma',
        url: '/platform/dashboard',
        file: 'frontend/pages/platform/dashboard.vue',
        reference: 'vista dashboard de plataforma',
        audience: 'client',
        viewType: 'dashboard',
      },
      {
        label: 'Notificaciones',
        url: '/platform/notifications',
        file: 'frontend/pages/platform/notifications.vue',
        reference: 'vista de notificaciones de plataforma',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Perfil',
        url: '/platform/profile',
        file: 'frontend/pages/platform/profile.vue',
        reference: 'vista de perfil de plataforma',
        audience: 'client',
        viewType: 'config',
      },
      {
        label: 'Proyectos',
        url: '/platform/projects',
        file: 'frontend/pages/platform/projects/index.vue',
        reference: 'vista listado de proyectos de plataforma',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Detalle de proyecto',
        url: '/platform/projects/:id',
        file: 'frontend/pages/platform/projects/[id]/index.vue',
        reference: 'vista de detalle de proyecto de plataforma',
        audience: 'client',
        viewType: 'detail',
      },
      {
        label: 'Tablero de proyecto',
        url: '/platform/projects/:id/board',
        file: 'frontend/pages/platform/projects/[id]/board.vue',
        reference: 'vista de tablero de proyecto',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Bugs de proyecto',
        url: '/platform/projects/:id/bugs',
        file: 'frontend/pages/platform/projects/[id]/bugs.vue',
        reference: 'vista de bugs de proyecto',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Cambios de proyecto',
        url: '/platform/projects/:id/changes',
        file: 'frontend/pages/platform/projects/[id]/changes.vue',
        reference: 'vista de cambios de proyecto',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Cuentas de cobro de proyecto',
        url: '/platform/projects/:id/collection-accounts',
        file: 'frontend/pages/platform/projects/[id]/collection-accounts.vue',
        reference: 'vista de cuentas de cobro de proyecto',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Modelo de datos de proyecto',
        url: '/platform/projects/:id/data-model',
        file: 'frontend/pages/platform/projects/[id]/data-model.vue',
        reference: 'vista de modelo de datos de proyecto',
        audience: 'client',
        viewType: 'detail',
      },
      {
        label: 'Entregables de proyecto',
        url: '/platform/projects/:id/deliverables',
        file: 'frontend/pages/platform/projects/[id]/deliverables/index.vue',
        reference: 'vista de entregables de proyecto',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Detalle de entregable',
        url: '/platform/projects/:id/deliverables/:deliverableId',
        file: 'frontend/pages/platform/projects/[id]/deliverables/[deliverableId]/index.vue',
        reference: 'vista de detalle de entregable',
        audience: 'client',
        viewType: 'detail',
      },
      {
        label: 'Pagos de proyecto',
        url: '/platform/projects/:id/payments',
        file: 'frontend/pages/platform/projects/[id]/payments.vue',
        reference: 'vista de pagos de proyecto',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Clientes de plataforma',
        url: '/platform/clients',
        file: 'frontend/pages/platform/clients/index.vue',
        reference: 'vista listado de clientes de plataforma',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Detalle de cliente de plataforma',
        url: '/platform/clients/:id',
        file: 'frontend/pages/platform/clients/[id].vue',
        reference: 'vista de detalle de cliente de plataforma',
        audience: 'client',
        viewType: 'detail',
      },
      {
        label: 'Cuentas de cobro',
        url: '/platform/collection-accounts',
        file: 'frontend/pages/platform/collection-accounts/index.vue',
        reference: 'vista listado de cuentas de cobro',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Detalle de cuenta de cobro',
        url: '/platform/collection-accounts/:id',
        file: 'frontend/pages/platform/collection-accounts/[id].vue',
        reference: 'vista de detalle de cuenta de cobro',
        audience: 'client',
        viewType: 'detail',
      },
      {
        label: 'Tablero global',
        url: '/platform/board',
        file: 'frontend/pages/platform/board.vue',
        reference: 'vista de tablero global de plataforma',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Bugs globales',
        url: '/platform/bugs',
        file: 'frontend/pages/platform/bugs.vue',
        reference: 'vista de bugs globales de plataforma',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Cambios globales',
        url: '/platform/changes',
        file: 'frontend/pages/platform/changes.vue',
        reference: 'vista de cambios globales de plataforma',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Entregables globales',
        url: '/platform/deliverables',
        file: 'frontend/pages/platform/deliverables.vue',
        reference: 'vista de entregables globales de plataforma',
        audience: 'client',
        viewType: 'list',
      },
      {
        label: 'Pagos globales',
        url: '/platform/payments',
        file: 'frontend/pages/platform/payments.vue',
        reference: 'vista de pagos globales de plataforma',
        audience: 'client',
        viewType: 'list',
      },
    ],
  },
]

export const proposalViewReferenceGuide = [
  {
    label: 'Propuesta dentro del panel',
    recommendedName: 'vista de edicion/detalle de propuesta del panel',
    url: '/panel/proposals/:id/edit',
    file: 'frontend/pages/panel/proposals/[id]/edit.vue',
    description: 'Usala para referirte a la pantalla interna donde el admin edita la propuesta, revisa analitica, documentos, emails y secciones.',
  },
  {
    label: 'Propuesta que ve el cliente',
    recommendedName: 'vista publica de propuesta',
    url: '/proposal/:uuid',
    file: 'frontend/pages/proposal/[uuid]/index.vue',
    description: 'Usala para referirte al enlace compartido con el cliente. Esta ruta usa uuid publico.',
  },
  {
    label: 'Modo especifico de la propuesta publica',
    recommendedName: 'vista publica de propuesta en modo detallado, ejecutivo o tecnico',
    url: '/proposal/:uuid?mode=detailed|executive|technical',
    file: 'frontend/pages/proposal/[uuid]/index.vue',
    description: 'Usala cuando el problema depende del modo seleccionado en la propuesta publica.',
  },
]

export function countCatalogViews(sections = viewCatalogSections) {
  return sections.reduce((count, section) => count + section.views.length, 0)
}

export function getViewCopyReference(sectionLabel, view) {
  return `[${sectionLabel}] ${view.label} \u2014 ${view.url}`
}
