# Generated by Django 6.1 on 2026-09-26 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0063_projectaccessnote_projectadminaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_encrypted', models.TextField()),
                ('secret_type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('payload_encrypted', models.TextField()),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2)),
                ('origin', models.CharField(choices=[('panel', 'Equipo (panel)'), ('mcp', 'Asistente (MCP)'), ('public', 'Cliente (página pública)')], max_length=10)),
                ('creator_name', models.CharField(blank=True, max_length=120)),
                ('creator_email', models.EmailField(blank=True, max_length=254)),
                ('creator_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('validity_days', models.PositiveSmallIntegerField(default=7)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consumed_user_agent', models.CharField(blank=True, max_length=300)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('activation_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secure_links', to='accounts.userprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secure_links_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secure_links', to='accounts.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SecureLinkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Creado'), ('revealed', 'Abierto por el destinatario'), ('reveal_blocked', 'Intento de apertura rechazado'), ('reactivated', 'Reactivado'), ('rotated', 'Enlace regenerado'), ('revoked', 'Revocado'), ('updated', 'Editado'), ('panel_viewed', 'Contenido visto en el panel')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='secure_links.securelink')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='securelink',
            index=models.Index(fields=['origin', 'consumed_at'], name='secure_link_origin_consumed'),
        ),
        migrations.AddIndex(
            model_name='securelink',
            index=models.Index(fields=['expires_at'], name='secure_link_expires'),
        ),
    ]
