# Generated by Django 5.0.6 on 2024-09-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_es', models.CharField(max_length=255, verbose_name='Title (Spanish)')),
                ('cover_image', models.ImageField(upload_to='designs/cover/')),
                ('detail_image', models.ImageField(upload_to='designs/detail/')),
                ('category_title_en', models.CharField(max_length=255, verbose_name='Category Title (English)')),
                ('category_title_es', models.CharField(max_length=255, verbose_name='Category Title (Spanish)')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_es', models.CharField(max_length=255, verbose_name='Title (Spanish)')),
                ('image', models.ImageField(upload_to='components/examples/')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Item Name (English)')),
                ('name_es', models.CharField(max_length=255, verbose_name='Item Name (Spanish)')),
            ],
        ),
        migrations.CreateModel(
            name='Model3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_es', models.CharField(max_length=255, verbose_name='Title (Spanish)')),
                ('image', models.ImageField(upload_to='3dmodels/images/')),
                ('file', models.FileField(upload_to='3dmodels/files/')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_es', models.CharField(max_length=255, verbose_name='Title (Spanish)')),
                ('image', models.ImageField(upload_to='components/images/')),
                ('examples', models.ManyToManyField(related_name='components', to='content.example')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Category Name (English)')),
                ('name_es', models.CharField(max_length=255, verbose_name='Category Name (Spanish)')),
                ('items', models.ManyToManyField(related_name='categories', to='content.item')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_es', models.CharField(max_length=255, verbose_name='Title (Spanish)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_es', models.TextField(verbose_name='Description (Spanish)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('development_time_en', models.CharField(max_length=255, verbose_name='Development Time (English)')),
                ('development_time_es', models.CharField(max_length=255, verbose_name='Development Time (Spanish)')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('categories', models.ManyToManyField(related_name='products', to='content.category')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_es', models.CharField(max_length=255, verbose_name='Title (Spanish)')),
                ('components', models.ManyToManyField(related_name='sections', to='content.component')),
            ],
        ),
        migrations.CreateModel(
            name='UISectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_es', models.CharField(max_length=255, verbose_name='Title (Spanish)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('description_es', models.TextField(verbose_name='Description (Spanish)')),
                ('sections', models.ManyToManyField(related_name='categories', to='content.section')),
            ],
        ),
    ]
