# Generated by Django 5.0.6 on 2024-11-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_es', models.CharField(max_length=255, verbose_name='Title (Spanish)')),
                ('description_en', models.CharField(max_length=255, verbose_name='Description (English)')),
                ('description_es', models.CharField(max_length=255, verbose_name='Description (Spanish)')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Price')),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Annual Price')),
                ('cpu_cores_en', models.CharField(max_length=255, verbose_name='CPU Cores (English)')),
                ('cpu_cores_es', models.CharField(max_length=255, verbose_name='CPU Cores (Spanish)')),
                ('ram_en', models.CharField(max_length=255, verbose_name='RAM (English)')),
                ('ram_es', models.CharField(max_length=255, verbose_name='RAM (Spanish)')),
                ('storage_en', models.CharField(max_length=255, verbose_name='Storage (English)')),
                ('storage_es', models.CharField(max_length=255, verbose_name='Storage (Spanish)')),
                ('bandwidth_en', models.CharField(max_length=255, verbose_name='Bandwidth (English)')),
                ('bandwidth_es', models.CharField(max_length=255, verbose_name='Bandwidth (Spanish)')),
                ('data_center_location_en', models.CharField(max_length=255, verbose_name='Data Center Location (English)')),
                ('data_center_location_es', models.CharField(max_length=255, verbose_name='Data Center Location (Spanish)')),
                ('operating_system_en', models.CharField(max_length=255, verbose_name='Operating System (English)')),
                ('operating_system_es', models.CharField(max_length=255, verbose_name='Operating System (Spanish)')),
            ],
        ),
    ]
