# Generated by Django 5.0.6 on 2024-06-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_categoriesdevelopment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Title (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example',
            name='title_es',
            field=models.CharField(default=1, max_length=255, verbose_name='Title (Spanish)'),
            preserve_default=False,
        ),
    ]
