# Generated by Django 5.0.6 on 2024-11-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_hosting'),
    ]

    operations = [
        migrations.AddField(
            model_name='model3d',
            name='category_title_en',
            field=models.CharField(default=1, max_length=255, verbose_name='Category Title (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model3d',
            name='category_title_es',
            field=models.CharField(default=1, max_length=255, verbose_name='Category Title (Spanish)'),
            preserve_default=False,
        ),
    ]
