# Generated by Django 5.0.6 on 2025-03-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_model3d_category_title_en_model3d_category_title_es'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosting',
            name='monthly_price',
        ),
        migrations.AddField(
            model_name='hosting',
            name='semi_annually_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Semi Annually Price'),
            preserve_default=False,
        ),
    ]
