# Generated by Django 5.0.6 on 2025-03-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_hosting_monthly_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hosting_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hosting Plan ID for Scroll Targeting'),
        ),
        migrations.AddField(
            model_name='product',
            name='hosting_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Associated Hosting Plan Name'),
        ),
    ]
