# Generated by Django 5.0.6 on 2025-03-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_product_hosting_id_product_hosting_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_es', models.CharField(max_length=255, verbose_name='Title (Spanish)')),
                ('cover_image', models.ImageField(upload_to='portfolio/cover/')),
                ('project_url', models.URLField(max_length=500, verbose_name='Project URL')),
                ('category_title_en', models.CharField(max_length=255, verbose_name='Category Title (English)')),
                ('category_title_es', models.CharField(max_length=255, verbose_name='Category Title (Spanish)')),
            ],
        ),
    ]
