# Generated by Django 5.0.6 on 2025-04-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_product_mobile_app_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='section',
            name='components',
        ),
        migrations.RemoveField(
            model_name='uisectioncategory',
            name='sections',
        ),
        migrations.DeleteModel(
            name='Example',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='UISectionCategory',
        ),
    ]
