# Generated by Django 5.0.6 on 2026-01-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_component_examples_remove_section_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='budget',
            field=models.CharField(blank=True, choices=[('1-3K', '1-3K'), ('3-5K', '3-5K'), ('5-10K', '5-10K'), ('10-20K', '10-20K'), ('>30K', '>30K')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
