# Generated by Django 5.0.6 on 2026-01-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_contact_budget_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='budget',
            field=models.CharField(blank=True, choices=[('500-5K', '500-5K'), ('5-10K', '5-10K'), ('10-20K', '10-20K'), ('20-30K', '20-30K'), ('>30K', '>30K')], max_length=10, null=True),
        ),
    ]
