# Generated by Django 5.0.6 on 2026-03-04 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_contact_message_alter_contact_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('total_investment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(choices=[('COP', 'COP'), ('USD', 'USD')], default='COP', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_days', models.PositiveIntegerField(default=5)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Proposal',
                'verbose_name_plural': 'Business Proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalRequirementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_groups', to='content.businessproposal')),
            ],
            options={
                'verbose_name': 'Requirement Group',
                'verbose_name_plural': 'Requirement Groups',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProposalRequirementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50)),
                ('icon', models.CharField(default='✅', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.proposalrequirementgroup')),
            ],
            options={
                'verbose_name': 'Requirement Item',
                'verbose_name_plural': 'Requirement Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProposalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('greeting', 'Greeting'), ('executive_summary', 'Executive Summary'), ('context_diagnostic', 'Context & Diagnostic'), ('conversion_strategy', 'Conversion Strategy'), ('design_ux', 'Design & UX'), ('creative_support', 'Creative Support'), ('development_stages', 'Development Stages'), ('functional_requirements', 'Functional Requirements'), ('timeline', 'Timeline'), ('investment', 'Investment'), ('final_note', 'Final Note'), ('next_steps', 'Next Steps')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('is_wide_panel', models.BooleanField(default=False)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.businessproposal')),
            ],
            options={
                'verbose_name': 'Proposal Section',
                'verbose_name_plural': 'Proposal Sections',
                'ordering': ['order'],
                'unique_together': {('proposal', 'section_type')},
            },
        ),
    ]
