# Generated by Django 5.0.6 on 2026-03-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_businessproposal_proposalrequirementgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='urgency_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
