# Generated by Django 5.0.6 on 2026-03-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_businessproposal_urgency_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='discount_percent',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
