# Generated by Django 5.0.6 on 2026-03-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_businessproposal_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='language',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2),
        ),
    ]
