# Generated by Django 5.0.6 on 2026-03-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_add_language_to_businessproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_es', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/covers/')),
                ('excerpt_es', models.TextField(help_text='Resumen corto en español (1-2 oraciones).')),
                ('excerpt_en', models.TextField(help_text='Short summary in English (1-2 sentences).')),
                ('content_es', models.TextField(help_text='Contenido completo del artículo en HTML (español).')),
                ('content_en', models.TextField(help_text='Full article content in HTML (English).')),
                ('sources', models.JSONField(blank=True, default=list, help_text='List of {name, url} objects for consulted sources.')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
