# Generated by Django 5.0.6 on 2026-03-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='rejection_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
