# Generated by Django 5.0.6 on 2026-03-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_add_rejection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='urgency_reminder_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='businessproposal',
            name='reminder_days',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
