# Generated by Django 5.0.6 on 2026-03-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_proposal_lifecycle_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Category slug for filtering (e.g. technology, design, guides).', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_json_en',
            field=models.JSONField(blank=True, default=dict, help_text='Structured JSON content in English (intro, sections, conclusion, cta).'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_json_es',
            field=models.JSONField(blank=True, default=dict, help_text='Structured JSON content in Spanish (intro, sections, conclusion, cta).'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pin this post as the featured/hero post on the blog listing.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_en',
            field=models.TextField(blank=True, default='', help_text='SEO meta description in English.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description_es',
            field=models.TextField(blank=True, default='', help_text='SEO meta description in Spanish.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title_en',
            field=models.CharField(blank=True, default='', help_text='SEO title override in English.', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title_es',
            field=models.CharField(blank=True, default='', help_text='SEO title override in Spanish.', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(blank=True, default='', help_text='Full article content in HTML (English).'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content_es',
            field=models.TextField(blank=True, default='', help_text='Contenido completo del artículo en HTML (español).'),
        ),
    ]
