# Generated by Django 5.0.6 on 2026-03-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_blog_structured_json_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', help_text='External URL for cover image (used when no file is uploaded).', max_length=500),
        ),
    ]
