# Generated by Django 5.0.6 on 2026-03-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_add_cover_image_url_to_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalViewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Client-side generated session identifier.', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='content.businessproposal')),
            ],
            options={
                'verbose_name': 'Proposal View Event',
                'verbose_name_plural': 'Proposal View Events',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalSectionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(max_length=50)),
                ('section_title', models.CharField(blank=True, default='', max_length=255)),
                ('time_spent_seconds', models.FloatField(default=0, help_text='Seconds the client spent viewing this section.')),
                ('entered_at', models.DateTimeField(help_text='Timestamp when the client navigated to this section.')),
                ('view_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_views', to='content.proposalviewevent')),
            ],
            options={
                'verbose_name': 'Proposal Section View',
                'verbose_name_plural': 'Proposal Section Views',
                'ordering': ['entered_at'],
            },
        ),
    ]
