# Generated by Django 5.0.6 on 2026-03-07 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_responded_at_and_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='abandonment_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='followup_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='investment_interest_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProposalShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('shared_by_name', models.CharField(max_length=255)),
                ('shared_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='content.businessproposal')),
            ],
            options={
                'verbose_name': 'Proposal Share Link',
                'verbose_name_plural': 'Proposal Share Links',
                'ordering': ['-created_at'],
            },
        ),
    ]
