# Generated by Django 5.0.6 on 2026-03-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_proposal_marketing_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessproposal',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proposalchangelog',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resent', 'Resent'), ('expired', 'Expired'), ('duplicated', 'Duplicated'), ('commented', 'Commented'), ('reengagement', 'Reengagement')], max_length=20),
        ),
    ]
