# Generated by Django 5.0.6 on 2026-03-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_fix_discount_percent_default_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='stakeholder_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
