# Generated by Django 5.0.6 on 2026-03-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_add_stakeholder_alert_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_credit',
            field=models.CharField(blank=True, default='', help_text='Attribution text for the cover image (e.g. "Photo by John Doe on Unsplash").', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image_credit_url',
            field=models.URLField(blank=True, default='', help_text='URL to the photographer profile or image source page.', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords_en',
            field=models.CharField(blank=True, default='', help_text='Comma-separated SEO keywords in English.', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords_es',
            field=models.CharField(blank=True, default='', help_text='Comma-separated SEO keywords in Spanish.', max_length=500),
        ),
    ]
