# Generated by Django 5.0.6 on 2026-03-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_add_blog_cover_credit_and_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, choices=[('projectapp-team', 'Project App Team'), ('gustavo-perez', 'Gustavo Pérez — CEO'), ('carlos-blanco', 'Carlos Blanco — CFO')], default='projectapp-team', help_text='Author profile slug (projectapp-team, gustavo-perez, carlos-blanco).', max_length=50),
        ),
    ]
