# Generated by Django 5.0.6 on 2026-03-09 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_add_blog_author_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliowork',
            options={'ordering': ['order', '-published_at', '-created_at'], 'verbose_name': 'Portfolio Work', 'verbose_name_plural': 'Portfolio Works'},
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='content_json_en',
            field=models.JSONField(blank=True, default=dict, help_text='Structured JSON content in English (problem, solution, results).'),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='content_json_es',
            field=models.JSONField(blank=True, default=dict, help_text='Structured JSON content in Spanish (problem, solution, results).'),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='cover_image_url',
            field=models.URLField(blank=True, default='', help_text='External URL for cover image (used when no file is uploaded).', max_length=500),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='excerpt_en',
            field=models.TextField(blank=True, default='', help_text='Short tagline in English for the listing cards.'),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='excerpt_es',
            field=models.TextField(blank=True, default='', help_text='Tagline corto en español para las cards del listado.'),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='meta_description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='meta_description_es',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='meta_keywords_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='meta_keywords_es',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='meta_title_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='meta_title_es',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Manual sort order (lower first).'),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='portfoliowork',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfoliowork',
            name='category_title_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Category Title (English)'),
        ),
        migrations.AlterField(
            model_name='portfoliowork',
            name='category_title_es',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Category Title (Spanish)'),
        ),
        migrations.AlterField(
            model_name='portfoliowork',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='portfolio/cover/'),
        ),
    ]
