# Generated by Django 5.0.6 on 2026-03-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_portfolio_work_revamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='market_type',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('saas', 'SaaS'), ('retail', 'Retail'), ('services', 'Servicios profesionales'), ('health', 'Salud'), ('education', 'Educación'), ('real_estate', 'Inmobiliaria'), ('other', 'Otro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='project_type',
            field=models.CharField(blank=True, choices=[('website', 'Sitio Web'), ('ecommerce', 'E-commerce'), ('webapp', 'Aplicación Web'), ('landing', 'Landing Page'), ('redesign', 'Rediseño'), ('other', 'Otro')], default='', max_length=20),
        ),
    ]
