# Generated by Django 5.0.6 on 2026-03-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_add_project_type_market_type_client_phone_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalchangelog',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resent', 'Resent'), ('expired', 'Expired'), ('duplicated', 'Duplicated'), ('commented', 'Commented'), ('reengagement', 'Reengagement'), ('call', 'Call'), ('meeting', 'Meeting'), ('followup', 'Follow-up'), ('note', 'Note')], max_length=20),
        ),
    ]
