# Generated by Django 5.0.6 on 2026-03-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_add_seller_activity_change_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='market_type_custom',
            field=models.CharField(blank=True, default='', help_text='Free-text description when market_type is "other".', max_length=100),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='project_type_custom',
            field=models.CharField(blank=True, default='', help_text='Free-text description when project_type is "other".', max_length=100),
        ),
        migrations.CreateModel(
            name='ProposalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('reminder', 'Recordatorio'), ('followup', 'Seguimiento'), ('call', 'Llamada'), ('meeting', 'Reunión'), ('custom', 'Personalizado')], default='reminder', max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('alert_date', models.DateTimeField(help_text='When this alert should become visible.')),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_alerts', to='content.businessproposal')),
            ],
            options={
                'verbose_name': 'Proposal Alert',
                'verbose_name_plural': 'Proposal Alerts',
                'ordering': ['alert_date'],
            },
        ),
    ]
