# Generated by Django 5.0.6 on 2026-03-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_add_proposal_alert_and_custom_type_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalalert',
            name='alert_type',
            field=models.CharField(choices=[('reminder', 'Recordatorio'), ('followup', 'Seguimiento'), ('call', 'Llamada'), ('meeting', 'Reunión'), ('custom', 'Personalizado'), ('discount_suggestion', 'Sugerencia de descuento')], default='reminder', max_length=20),
        ),
    ]
