# Generated by Django 5.0.6 on 2026-03-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_add_automations_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='post_expiration_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessproposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('negotiating', 'Negotiating'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposalalert',
            name='alert_type',
            field=models.CharField(choices=[('reminder', 'Recordatorio'), ('followup', 'Seguimiento'), ('call', 'Llamada'), ('meeting', 'Reunión'), ('custom', 'Personalizado'), ('discount_suggestion', 'Sugerencia de descuento'), ('post_expiration_visit', 'Visita post-expiración')], default='reminder', max_length=25),
        ),
        migrations.AlterField(
            model_name='proposalchangelog',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resent', 'Resent'), ('expired', 'Expired'), ('duplicated', 'Duplicated'), ('commented', 'Commented'), ('negotiating', 'Negotiating'), ('reengagement', 'Reengagement'), ('call', 'Call'), ('meeting', 'Meeting'), ('followup', 'Follow-up'), ('note', 'Note')], max_length=20),
        ),
    ]
