# Generated by Django 5.0.6 on 2026-03-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_add_negotiating_status_and_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalchangelog',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resent', 'Resent'), ('expired', 'Expired'), ('duplicated', 'Duplicated'), ('commented', 'Commented'), ('negotiating', 'Negotiating'), ('reengagement', 'Reengagement'), ('call', 'Call'), ('meeting', 'Meeting'), ('followup', 'Follow-up'), ('note', 'Note'), ('calc_confirmed', 'Calculator Confirmed'), ('calc_abandoned', 'Calculator Abandoned')], max_length=20),
        ),
    ]
