# Generated by Django 5.0.6 on 2026-03-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_add_calculator_change_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='hosting_percent',
            field=models.PositiveIntegerField(default=30, help_text='Percentage of total investment charged for annual hosting.'),
        ),
    ]
