# Generated by Django 5.0.6 on 2026-03-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_add_hosting_percent_to_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='calculator_followup_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposalalert',
            name='alert_type',
            field=models.CharField(choices=[('reminder', 'Recordatorio'), ('followup', 'Seguimiento'), ('call', 'Llamada'), ('meeting', 'Reunión'), ('custom', 'Personalizado'), ('discount_suggestion', 'Sugerencia de descuento'), ('post_expiration_visit', 'Visita post-expiración'), ('high_engagement_today', 'Alta actividad hoy'), ('whatsapp_suggestion', 'Sugerencia de WhatsApp'), ('calculator_followup', 'Seguimiento calculadora')], default='reminder', max_length=25),
        ),
        migrations.AlterField(
            model_name='proposalchangelog',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resent', 'Resent'), ('expired', 'Expired'), ('duplicated', 'Duplicated'), ('commented', 'Commented'), ('negotiating', 'Negotiating'), ('reengagement', 'Reengagement'), ('call', 'Call'), ('meeting', 'Meeting'), ('followup', 'Follow-up'), ('note', 'Note'), ('calc_confirmed', 'Calculator Confirmed'), ('calc_abandoned', 'Calculator Abandoned'), ('auto_archived', 'Auto Archived'), ('status_change', 'Status Change'), ('cond_accepted', 'Conditional Acceptance'), ('calc_followup', 'Calculator Follow-up Sent')], max_length=20),
        ),
    ]
