# Generated by Django 5.0.6 on 2026-03-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0038_add_calculator_followup_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalDefaultConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], help_text='Language for this default configuration.', max_length=2, unique=True)),
                ('sections_json', models.JSONField(default=list, help_text='Full array of default section dicts (same structure as DEFAULT_SECTIONS).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proposal Default Config',
                'verbose_name_plural': 'Proposal Default Configs',
            },
        ),
    ]
