# Generated by Django 5.0.6 on 2026-03-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_proposaldefaultconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(help_text='Registry key (e.g. proposal_sent_client)', max_length=80, unique=True)),
                ('content_overrides', models.JSONField(blank=True, default=dict, help_text='JSON dict of {field_key: custom_value} overrides.')),
                ('is_active', models.BooleanField(default=True, help_text='When False the email is silently skipped.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template Config',
                'verbose_name_plural': 'Email Template Configs',
                'ordering': ['template_key'],
            },
        ),
    ]
