# Generated by Django 5.0.6 on 2026-03-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_emailtemplateconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsectionview',
            name='view_mode',
            field=models.CharField(choices=[('executive', 'Executive'), ('detailed', 'Detailed'), ('unknown', 'Unknown')], default='unknown', help_text='Whether this section was viewed in executive or detailed mode.', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalviewevent',
            name='view_mode',
            field=models.CharField(choices=[('executive', 'Executive'), ('detailed', 'Detailed'), ('unknown', 'Unknown')], default='unknown', help_text='Whether the client viewed in executive or detailed mode.', max_length=20),
        ),
    ]
