# Generated by Django 5.0.6 on 2026-03-13 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_add_view_mode_to_tracking_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=100)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='content.businessproposal')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['template_key', 'sent_at'], name='content_ema_templat_33b560_idx'), models.Index(fields=['status', 'sent_at'], name='content_ema_status_b7e639_idx')],
            },
        ),
    ]
