# Generated by Django 5.0.6 on 2026-03-14 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0042_add_email_log_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='items',
        ),
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.DeleteModel(
            name='Hosting',
        ),
        migrations.DeleteModel(
            name='Model3D',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
