# Generated by Django 5.0.6 on 2026-03-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0043_remove_design_model3d_hosting_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalalert',
            name='alert_type',
            field=models.CharField(choices=[('reminder', 'Recordatorio'), ('followup', 'Seguimiento'), ('call', 'Llamada'), ('meeting', 'Reunión'), ('custom', 'Personalizado'), ('discount_suggestion', 'Sugerencia de descuento'), ('post_expiration_visit', 'Visita post-expiración'), ('high_engagement_today', 'Alta actividad hoy'), ('whatsapp_suggestion', 'Sugerencia de WhatsApp'), ('calculator_followup', 'Seguimiento calculadora'), ('engagement_decay', 'Pérdida de engagement')], default='reminder', max_length=30),
        ),
    ]
