# Generated by Django 5.0.6 on 2026-03-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_add_engagement_decay_alert_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proposal Alert', 'verbose_name_plural': 'Proposal Alerts'},
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='cached_heat_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Pre-computed heat score (1-10), updated by tracking endpoint and periodic task.'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='engagement_declining',
            field=models.BooleanField(default=False, help_text='Set when engagement decay is detected; reset on normal session.'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='last_automated_email_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last automated email sent to the client. Used for 24h cooldown.', null=True),
        ),
        migrations.AddField(
            model_name='proposalalert',
            name='priority',
            field=models.CharField(choices=[('critical', 'Alta urgencia'), ('high', 'Alta'), ('normal', 'Normal')], default='normal', help_text='Auto-computed priority based on alert type.', max_length=10),
        ),
    ]
