# Generated by Django 5.0.6 on 2026-03-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_add_engagement_signals_and_alert_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalalert',
            name='alert_type',
            field=models.CharField(choices=[('reminder', 'Recordatorio'), ('followup', 'Seguimiento'), ('call', 'Llamada'), ('meeting', 'Reunión'), ('custom', 'Personalizado'), ('discount_suggestion', 'Sugerencia de descuento'), ('post_expiration_visit', 'Visita post-expiración'), ('high_engagement_today', 'Alta actividad hoy'), ('whatsapp_suggestion', 'Sugerencia de WhatsApp'), ('calculator_followup', 'Seguimiento calculadora'), ('engagement_decay', 'Pérdida de engagement'), ('post_rejection_revisit', 'Revisita post-rechazo')], default='reminder', max_length=30),
        ),
    ]
