# Generated by Django 5.0.6 on 2026-03-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0047_add_hosting_billing_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalchangelog',
            name='actor_type',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('seller', 'Seller'), ('system', 'System')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='proposalchangelog',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resent', 'Resent'), ('expired', 'Expired'), ('duplicated', 'Duplicated'), ('commented', 'Commented'), ('negotiating', 'Negotiating'), ('reengagement', 'Reengagement'), ('call', 'Call'), ('meeting', 'Meeting'), ('followup', 'Follow-up'), ('note', 'Note'), ('calc_confirmed', 'Calculator Confirmed'), ('calc_abandoned', 'Calculator Abandoned'), ('auto_archived', 'Auto Archived'), ('status_change', 'Status Change'), ('cond_accepted', 'Conditional Acceptance'), ('calc_followup', 'Calculator Follow-up Sent'), ('req_clicked', 'Requirement Clicked')], max_length=20),
        ),
    ]
