# Generated by Django 5.0.6 on 2026-03-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_proposalchangelog_actor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='selected_modules',
            field=models.JSONField(blank=True, default=list, help_text='List of module IDs selected by the client in the calculator (e.g. ["module-payments", "module-reservations"]).'),
        ),
    ]
