# Generated by Django 5.0.6 on 2026-03-29 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_add_selected_modules_to_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=20)),
                ('content_markdown', models.TextField(blank=True, default='')),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2)),
                ('cover_type', models.CharField(choices=[('generic', 'Genérica'), ('none', 'Sin portada'), ('proposal', 'Propuesta')], default='generic', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
