# Generated by Django 5.0.6 on 2026-03-30 12:51

from django.db import migrations, models


def populate_cover_flags(apps, schema_editor):
    """Set include_* flags based on legacy cover_type value."""
    Document = apps.get_model('content', 'Document')
    for doc in Document.objects.all():
        if doc.cover_type == 'proposal':
            doc.include_portada = True
            doc.include_subportada = True
            doc.include_contraportada = True
        elif doc.cover_type == 'none':
            doc.include_portada = False
            doc.include_subportada = False
            doc.include_contraportada = False
        else:
            doc.include_portada = False
            doc.include_subportada = True
            doc.include_contraportada = True
        doc.save(update_fields=['include_portada', 'include_subportada', 'include_contraportada'])


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='include_contraportada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='include_portada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='include_subportada',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(populate_cover_flags, migrations.RunPython.noop),
    ]
