# Generated by Django 5.0.6 on 2026-03-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_collection_accounts_and_document_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessproposal',
            name='market_type',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('saas', 'SaaS'), ('retail', 'Retail'), ('services', 'Servicios profesionales'), ('health', 'Salud'), ('education', 'Educación'), ('real_estate', 'Inmobiliaria'), ('fintech', 'Fintech / Finanzas'), ('restaurant', 'Restaurantes / F&B'), ('tourism', 'Turismo / Hospitalidad'), ('logistics', 'Logística / Transporte'), ('sports', 'Deportes / Fitness'), ('legal', 'Servicios Legales / Jurídico'), ('construction', 'Construcción / Arquitectura'), ('media', 'Medios / Entretenimiento'), ('ngo', 'ONG / Sector Público'), ('agriculture', 'Agro / Tecnología Agrícola'), ('other', 'Otro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessproposal',
            name='project_type',
            field=models.CharField(blank=True, choices=[('website', 'Sitio Web'), ('ecommerce', 'E-commerce'), ('webapp', 'Aplicación Web'), ('landing', 'Landing Page'), ('redesign', 'Rediseño'), ('mobile_app', 'App Móvil'), ('branding', 'Branding / Identidad Visual'), ('cms', 'Sistema CMS'), ('portal', 'Portal / Intranet'), ('api_integration', 'Integración de APIs'), ('marketplace', 'Marketplace'), ('erp', 'Sistema ERP / Administrativo'), ('booking', 'Sistema de Reservas'), ('dashboard', 'Dashboard / Reportes'), ('crm', 'Sistema CRM'), ('other', 'Otro')], default='', max_length=20),
        ),
    ]
