# Generated by Django 5.0.6 on 2026-04-01 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_archived_soft_delete_protect_payments'),
        ('content', '0059_technical_document_growth_readiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessproposal',
            name='deliverable',
            field=models.OneToOneField(blank=True, help_text='Platform deliverable that owns this proposal (PDFs, technical document).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_proposal', to='accounts.deliverable'),
        ),
    ]
