# Generated by Django 5.0.6 on 2026-04-02 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0060_alter_businessproposal_deliverable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_full_name', models.CharField(blank=True, default='', help_text='Legal name of the contractor (EL CONTRATISTA).', max_length=255)),
                ('contractor_cedula', models.CharField(blank=True, default='', help_text='Cédula number of the contractor.', max_length=30)),
                ('contractor_email', models.EmailField(blank=True, default='', help_text='Notification email for the contractor (Cláusula 14).', max_length=254)),
                ('bank_name', models.CharField(blank=True, default='', help_text='Bank name for payment (e.g. Bancolombia).', max_length=100)),
                ('bank_account_type', models.CharField(blank=True, default='Ahorros', help_text='Account type: Ahorros or Corriente.', max_length=50)),
                ('bank_account_number', models.CharField(blank=True, default='', help_text='Bank account number for payment.', max_length=50)),
                ('contract_city', models.CharField(blank=True, default='Medellín', help_text='City for dispute resolution (Cláusula 17).', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company settings',
                'verbose_name_plural': 'Company settings',
            },
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='contract_params',
            field=models.JSONField(blank=True, default=dict, help_text='Parameters for contract PDF generation (party names, cédulas, bank details, etc.).'),
        ),
        migrations.AlterField(
            model_name='businessproposal',
            name='market_type',
            field=models.CharField(blank=True, choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('saas', 'SaaS'), ('retail', 'Retail'), ('services', 'Servicios profesionales'), ('health', 'Salud'), ('education', 'Educación'), ('real_estate', 'Inmobiliaria'), ('fintech', 'Fintech / Finanzas'), ('restaurant', 'Restaurantes / F&B'), ('tourism', 'Turismo / Hospitalidad'), ('logistics', 'Logística / Transporte'), ('sports', 'Deportes / Fitness'), ('legal', 'Servicios Legales / Jurídico'), ('construction', 'Construcción / Arquitectura'), ('media', 'Medios / Entretenimiento'), ('ngo', 'ONG / Sector Público'), ('agriculture', 'Agro / Tecnología Agrícola'), ('tech', 'Tecnología / Software'), ('consulting', 'Consultoría / Asesoría'), ('automotive', 'Automotriz'), ('fashion', 'Moda / Textil'), ('beauty', 'Belleza / Cuidado Personal'), ('manufacturing', 'Manufactura / Industrial'), ('energy', 'Energía / Utilities'), ('gaming', 'Videojuegos / Gaming'), ('other', 'Otro')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='businessproposal',
            name='project_type',
            field=models.CharField(blank=True, choices=[('website', 'Sitio Web'), ('ecommerce', 'E-commerce'), ('webapp', 'Aplicación Web'), ('landing', 'Landing Page'), ('redesign', 'Rediseño'), ('mobile_app', 'App Móvil'), ('branding', 'Branding / Identidad Visual'), ('cms', 'Sistema CMS'), ('portal', 'Portal / Intranet'), ('api_integration', 'Integración de APIs'), ('marketplace', 'Marketplace'), ('erp', 'Sistema ERP / Administrativo'), ('booking', 'Sistema de Reservas'), ('dashboard', 'Dashboard / Reportes'), ('crm', 'Sistema CRM'), ('saas', 'SaaS / Plataforma'), ('chatbot', 'Chatbot / Asistente Virtual'), ('ai_tool', 'Herramienta con IA'), ('automation', 'Automatización / RPA'), ('data_analytics', 'Analítica de Datos / BI'), ('plugin_extension', 'Plugin / Extensión'), ('other', 'Otro')], default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Contrato'), ('amendment', 'Otrosí'), ('legal_annex', 'Anexo legal'), ('client_document', 'Documento del cliente'), ('other', 'Otro')], default='other', max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='proposal_documents/')),
                ('is_generated', models.BooleanField(default=False, help_text='True for system-generated PDFs (contract). Cannot be deleted by user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_documents', to='content.businessproposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
