# Generated by Django 5.0.6 on 2026-04-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0061_add_company_settings_proposal_document_contract_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldocument',
            name='custom_type_label',
            field=models.CharField(blank=True, default='', help_text='Custom label when document_type is "other".', max_length=100),
        ),
    ]
