# Generated by Django 5.0.6 on 2026-04-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0062_add_custom_type_label_to_proposal_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_markdown', models.TextField(help_text='Markdown text. Use {client_full_name}, {contractor_cedula}, etc. for placeholders.')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract template',
                'verbose_name_plural': 'Contract templates',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
