# Generated by Django 5.0.6 on 2026-04-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0067_fix_contract_template_dashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='contractor_signature',
            field=models.ImageField(blank=True, help_text='Signature image for the contractor (displayed on contract PDFs). PNG with transparent background recommended.', null=True, upload_to='signatures/'),
        ),
    ]
