# Generated by Django 5.0.6 on 2026-04-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0068_companysettings_contractor_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
