# Generated by Django 5.0.6 on 2026-04-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0072_linkedintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsectionview',
            name='subsection_key',
            field=models.CharField(blank=True, default='', help_text='Fragment key for technical document subsections (e.g. "stack", "architecture").', max_length=50),
        ),
    ]
