# Generated by Django 5.0.6 on 2026-04-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0075_proposaldefaultconfig_expiration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='platform_onboarding_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], help_text='Tracks async onboarding: pending (in progress), completed, failed.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proposalchangelog',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resent', 'Resent'), ('expired', 'Expired'), ('duplicated', 'Duplicated'), ('commented', 'Commented'), ('negotiating', 'Negotiating'), ('reengagement', 'Reengagement'), ('call', 'Call'), ('meeting', 'Meeting'), ('followup', 'Follow-up'), ('note', 'Note'), ('calc_confirmed', 'Calculator Confirmed'), ('calc_abandoned', 'Calculator Abandoned'), ('auto_archived', 'Auto Archived'), ('status_change', 'Status Change'), ('cond_accepted', 'Conditional Acceptance'), ('calc_followup', 'Calculator Follow-up Sent'), ('req_clicked', 'Requirement Clicked'), ('email_sent', 'Email Sent'), ('seller_inactivity_escalation', 'Seller Inactivity Escalation'), ('platform_launch', 'Platform Launch')], max_length=30),
        ),
    ]
