# Generated by Django 5.0.6 on 2026-04-09 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_project_data_model_entity'),
        ('content', '0078_add_finished_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='client',
            field=models.ForeignKey(blank=True, help_text='UserProfile (rol=cliente) propietario de esta propuesta.', limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='accounts.userprofile'),
        ),
    ]
