# Generated by Django 5.0.6 on 2026-04-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0080_backfill_proposal_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(choices=[('design', 'Diseño'), ('development', 'Desarrollo')], max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When an admin marked this stage as completed. Silences alerts.', null=True)),
                ('warning_sent_at', models.DateTimeField(blank=True, help_text='Timestamp of the 70% pre-deadline warning email. Sent once.', null=True)),
                ('last_overdue_reminder_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent overdue reminder email (first one + every 3 days while uncompleted).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stages', to='content.businessproposal')),
            ],
            options={
                'verbose_name': 'Proposal Project Stage',
                'verbose_name_plural': 'Proposal Project Stages',
                'ordering': ['proposal_id', 'order'],
                'unique_together': {('proposal', 'stage_key')},
            },
        ),
    ]
