# Generated by Django 5.0.6 on 2026-04-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0082_backfill_project_stages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalchangelog',
            name='change_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('resent', 'Resent'), ('expired', 'Expired'), ('duplicated', 'Duplicated'), ('commented', 'Commented'), ('negotiating', 'Negotiating'), ('reengagement', 'Reengagement'), ('call', 'Call'), ('meeting', 'Meeting'), ('followup', 'Follow-up'), ('note', 'Note'), ('calc_confirmed', 'Calculator Confirmed'), ('calc_abandoned', 'Calculator Abandoned'), ('auto_archived', 'Auto Archived'), ('status_change', 'Status Change'), ('cond_accepted', 'Conditional Acceptance'), ('calc_followup', 'Calculator Follow-up Sent'), ('req_clicked', 'Requirement Clicked'), ('email_sent', 'Email Sent'), ('seller_inactivity_escalation', 'Seller Inactivity Escalation'), ('platform_launch', 'Platform Launch'), ('stage_warning_sent', 'Stage Warning Sent'), ('stage_overdue_sent', 'Stage Overdue Sent'), ('stage_completed', 'Stage Completed')], max_length=30),
        ),
    ]
