# Generated by Django 5.0.6 on 2026-04-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0088_proposal_automations_paused_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_overdue_notified_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notified_100',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notified_40',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notified_70',
            field=models.BooleanField(default=False),
        ),
    ]
