# Generated by Django 5.0.6 on 2026-04-15 23:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_project_data_model_entity'),
        ('content', '0089_task_notification_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAppDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('initial_sent', 'Initial sent'), ('in_analysis', 'In analysis'), ('final_sent', 'Final sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('COP', 'COP'), ('USD', 'USD')], default='COP', max_length=3)),
                ('payment_terms', models.JSONField(blank=True, default=dict, help_text='Ej: {"initial_pct": 40, "final_pct": 60}')),
                ('duration_label', models.CharField(blank=True, default='', max_length=80)),
                ('size_category', models.CharField(blank=True, choices=[('small', 'Pequeña'), ('medium', 'Mediana'), ('large', 'Grande')], default='', max_length=10)),
                ('radiography', models.JSONField(blank=True, default=dict)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('initial_sent_at', models.DateTimeField(blank=True, null=True)),
                ('final_sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='web_app_diagnostics', to='accounts.userprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Web App Diagnostic',
                'verbose_name_plural': 'Web App Diagnostics',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('initial_proposal', 'Propuesta de Diagnóstico'), ('technical_proposal', 'Propuesta de Diagnóstico Técnico'), ('sizing_annex', 'Anexo de Dimensionamiento Preliminar')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content_md', models.TextField()),
                ('is_ready', models.BooleanField(default=False, help_text='Marca el documento como listo para incluir en el envío final.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='content.webappdiagnostic')),
            ],
            options={
                'verbose_name': 'Diagnostic Document',
                'verbose_name_plural': 'Diagnostic Documents',
                'ordering': ['order', 'id'],
                'unique_together': {('diagnostic', 'doc_type')},
            },
        ),
    ]
