# Generated by Django 5.0.6 on 2026-04-16 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0091_diagnostic_status_remap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('amendment', 'Otrosí'), ('legal_annex', 'Anexo legal'), ('client_document', 'Documento del cliente'), ('other', 'Otro')], default='other', max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='diagnostic_attachments/%Y/%m/')),
                ('custom_type_label', models.CharField(blank=True, default='', help_text='Custom label when document_type is "other".', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.webappdiagnostic')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
