# Generated by Django 5.0.6 on 2026-04-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0092_diagnostic_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_at', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='content.task')),
            ],
            options={
                'ordering': ['notify_at', 'created_at'],
            },
        ),
    ]
