# Generated by Django 5.0.6 on 2026-04-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0097_task_board_archive_and_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidentialityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_markdown', models.TextField(help_text='Markdown text. Use {client_full_name}, {client_cedula}, etc. for placeholders.')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Confidentiality template',
                'verbose_name_plural': 'Confidentiality templates',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticattachment',
            name='is_generated',
            field=models.BooleanField(default=False, help_text='True for system-generated PDFs (NDA). Cannot be deleted by user.'),
        ),
        migrations.AddField(
            model_name='webappdiagnostic',
            name='confidentiality_params',
            field=models.JSONField(blank=True, default=dict, help_text='Datos para rellenar placeholders del NDA (NIT cliente, representante legal, valor SMMLV, ciudad, etc.).'),
        ),
        migrations.AlterField(
            model_name='diagnosticattachment',
            name='document_type',
            field=models.CharField(choices=[('confidentiality_agreement', 'Acuerdo de confidencialidad'), ('amendment', 'Otrosí'), ('legal_annex', 'Anexo legal'), ('client_document', 'Documento del cliente'), ('other', 'Otro')], default='other', max_length=30),
        ),
    ]
