# Generated by Django 5.0.6 on 2026-04-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0099_seed_confidentiality_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='webappdiagnostic',
            name='client_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='webappdiagnostic',
            name='client_email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='webappdiagnostic',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='webappdiagnostic',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
