# Generated by Django 5.0.6 on 2026-04-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0100_add_diagnostic_client_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticDefaultConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], help_text='Language for this default configuration.', max_length=2, unique=True)),
                ('sections_json', models.JSONField(default=list, help_text='Full array of default section dicts (same shape as the seed).')),
                ('payment_initial_pct', models.PositiveSmallIntegerField(default=60)),
                ('payment_final_pct', models.PositiveSmallIntegerField(default=40)),
                ('default_currency', models.CharField(choices=[('COP', 'COP'), ('USD', 'USD')], default='COP', max_length=3)),
                ('default_investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('default_duration_label', models.CharField(blank=True, default='', max_length=80)),
                ('expiration_days', models.PositiveIntegerField(default=21)),
                ('reminder_days', models.PositiveIntegerField(default=7)),
                ('urgency_reminder_days', models.PositiveIntegerField(default=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diagnostic Default Config',
                'verbose_name_plural': 'Diagnostic Default Configs',
            },
        ),
    ]
