# Generated by Django 5.0.6 on 2026-04-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0105_proposal_default_config_slug_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldefaultconfig',
            name='default_currency',
            field=models.CharField(choices=[('COP', 'COP'), ('USD', 'USD')], default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='proposaldefaultconfig',
            name='default_discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposaldefaultconfig',
            name='default_total_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proposaldefaultconfig',
            name='hosting_discount_quarterly',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='proposaldefaultconfig',
            name='hosting_discount_semiannual',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='proposaldefaultconfig',
            name='hosting_percent',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='proposaldefaultconfig',
            name='reminder_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='proposaldefaultconfig',
            name='urgency_reminder_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
