# Generated by Django 5.2.13 on 2026-05-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0115_clear_cost_section_meta_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessproposal',
            name='hosting_percent',
            field=models.PositiveIntegerField(default=40, help_text='Percentage of total investment charged for annual hosting.'),
        ),
        migrations.AlterField(
            model_name='proposaldefaultconfig',
            name='hosting_percent',
            field=models.PositiveSmallIntegerField(default=40),
        ),
    ]
