# Generated by Django 5.2.13 on 2026-05-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0116_hosting_percent_default_40'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='email_intro',
            field=models.TextField(blank=True, default='', help_text='Párrafo descriptivo del alcance de la propuesta usado en el correo inicial enviado al cliente. Si queda vacío se usa un texto por defecto derivado del título.'),
        ),
    ]
