# Generated by Django 5.2.13 on 2026-05-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0120_seed_gustavo_company_settings_and_rename_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplate',
            name='content_markdown',
            field=models.TextField(help_text='Markdown text. Use {client_full_name}, {contractor_nit}, etc. for placeholders.'),
        ),
    ]
