# Generated by Django 5.0.6 on 2026-05-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0121_update_contracttemplate_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='email_features',
            field=models.JSONField(blank=True, default=list, help_text='Lista de bullets que se renderizan en el bloque "Qué incluye" del correo de envío. Ejemplo: ["Dashboard tiempo real...", "App móvil...", "Integración ERP..."]. Si queda vacío el bloque se omite.'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='email_method_phases',
            field=models.JSONField(blank=True, default=list, help_text='Lista de 3 fases para el card "Método en 3 fases". Cada item: {"number":"01","title":"Diagnóstico","duration":"5 días","description":"..."}. Si queda vacío se usa el método estándar de marca.'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='email_signed_by',
            field=models.CharField(choices=[('gustavo', 'Gustavo Pérez'), ('carlos', 'Carlos Blanco')], default='gustavo', help_text='Firmante del correo (nombre + rol se resuelven desde settings.EMAIL_SIGNATURES).', max_length=20),
        ),
    ]
