# Generated by Django 5.2.13 on 2026-05-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0122_email_template_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='content.documentfolder'),
        ),
    ]
