# Generated by Django 5.2.13 on 2026-07-01 23:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0126_fix_legacy_renewal_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_recipients', models.JSONField(blank=True, default=list)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accounting settings',
                'verbose_name_plural': 'Accounting settings',
            },
        ),
        migrations.CreateModel(
            name='HostingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=255)),
                ('domain_url', models.CharField(blank=True, default='', max_length=255)),
                ('monthly_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_modality', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=12)),
                ('benefit', models.CharField(blank=True, default='', max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('cycles_count', models.PositiveIntegerField(default=0)),
                ('payment_per_cycle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='PocketMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.CharField(max_length=255)),
                ('movement_date', models.DateField()),
                ('direction', models.CharField(choices=[('in', 'Ingreso'), ('out', 'Egreso')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncomeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gustavo_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('carlos_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('concept', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('expected', 'Esperado'), ('liquid', 'Líquido')], max_length=10)),
                ('period_date', models.DateField()),
                ('destination', models.CharField(choices=[('partners', 'Socios'), ('pocket', 'Bolsillo ProjectApp')], default='partners', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('expected_income', models.ForeignKey(blank=True, limit_choices_to={'kind': 'expected'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquid_records', to='content.incomerecord')),
                ('pocket_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_record', to='content.pocketmovement')),
            ],
            options={
                'ordering': ['-period_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gustavo_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('carlos_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('concept', models.CharField(max_length=255)),
                ('period_date', models.DateField()),
                ('category', models.CharField(choices=[('business', 'Negocio'), ('personal', 'Personal')], default='business', max_length=10)),
                ('paid_from', models.CharField(choices=[('partners', 'Socios'), ('pocket', 'Bolsillo ProjectApp')], default='partners', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pocket_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_record', to='content.pocketmovement')),
            ],
            options={
                'ordering': ['-period_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('COP', 'COP'), ('USD', 'USD')], default='COP', max_length=3)),
                ('cop_equivalent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('credit_card', 'T.C')], default='credit_card', max_length=12)),
                ('frequency', models.CharField(choices=[('monthly', 'Mensual'), ('annual', 'Anual'), ('biennial', 'Cada 2 años'), ('triennial', 'Cada 3 años')], default='monthly', max_length=10)),
                ('billing_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('cost_type', models.CharField(choices=[('fixed', 'Fijo'), ('variable', 'Variable')], default='fixed', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountingChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto'), ('hosting', 'Hosting'), ('pocket', 'Bolsillo'), ('recurring', 'Pago recurrente'), ('ads', 'Ads'), ('card_snapshot', 'Saldo tarjeta'), ('settings', 'Configuración')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('deleted', 'Eliminado')], max_length=10)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accounting Change Log',
                'verbose_name_plural': 'Accounting Change Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'object_id', 'created_at'], name='content_acc_entity__bc60dc_idx'), models.Index(fields=['created_at'], name='content_acc_created_2aea6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdsSpendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spend_date', models.DateField()),
                ('platform', models.CharField(choices=[('facebook', 'Facebook Ads'), ('google', 'Google Ads'), ('other', 'Otro')], default='facebook', max_length=10)),
                ('origin_card', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-spend_date', '-created_at'],
                'indexes': [models.Index(fields=['platform', 'spend_date'], name='content_ads_platfor_fd305a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CardBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField()),
                ('card_name', models.CharField(max_length=100)),
                ('available_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-snapshot_date', '-created_at'],
                'indexes': [models.Index(fields=['card_name', 'snapshot_date'], name='content_car_card_na_48d558_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pocketmovement',
            index=models.Index(fields=['movement_date'], name='content_poc_movemen_15b340_idx'),
        ),
        migrations.AddIndex(
            model_name='incomerecord',
            index=models.Index(fields=['kind', 'period_date'], name='content_inc_kind_1f7321_idx'),
        ),
        migrations.AddIndex(
            model_name='expenserecord',
            index=models.Index(fields=['period_date'], name='content_exp_period__a2b68c_idx'),
        ),
    ]
