# Generated by Django 5.2.13 on 2026-07-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0127_accountingsettings_hostingrecord_pocketmovement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('token_hash', models.CharField(blank=True, default='', help_text='SHA-256 hex digest of the connector token. Plaintext is never stored.', max_length=64)),
                ('token_prefix', models.CharField(blank=True, default='', help_text='First 8 chars of the token, for masked display in the panel.', max_length=8)),
                ('is_active', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MCP Connector',
                'verbose_name_plural': 'MCP Connectors',
            },
        ),
    ]
