# Generated by Django 5.2.13 on 2026-07-03 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0129_seed_blog_mcp_connector'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('handshake', 'Handshake'), ('tool_call', 'Tool call'), ('auth_error', 'Auth error'), ('origin_rejected', 'Origin rejected')], max_length=20)),
                ('ok', models.BooleanField(default=True)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='content.mcpconnector')),
            ],
            options={
                'verbose_name': 'MCP Request Log',
                'verbose_name_plural': 'MCP Request Logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
