# Generated by Django 5.2.13 on 2026-07-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0132_documents_mcp_connector_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='ledger',
            field=models.CharField(choices=[('company', 'Empresa'), ('gustavo', 'Personal Gustavo'), ('carlos', 'Personal Carlos')], db_index=True, default='company', max_length=10),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='ledger',
            field=models.CharField(choices=[('company', 'Empresa'), ('gustavo', 'Personal Gustavo'), ('carlos', 'Personal Carlos')], db_index=True, default='company', max_length=10),
        ),
    ]
