# Generated by Django 5.2.13 on 2026-07-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0133_add_ledger_to_accounting_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='card_reminder_cycle_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='card_reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='card_reminder_last_sent_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
