# Generated by Django 5.2.13 on 2026-07-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0136_seed_panel_mcp_connectors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessproposal',
            name='automations_paused',
            field=models.BooleanField(default=False, help_text='When true, no automatic emails (reminder, urgency, inactivity) are sent for this proposal. New proposals default to automations enabled (not paused).'),
        ),
    ]
