# Generated by Django 5.2.13 on 2026-07-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0137_alter_businessproposal_automations_paused'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary', models.TextField(help_text='Post text (LinkedIn commentary, max 3000 chars).', max_length=3000)),
                ('image', models.ImageField(blank=True, help_text='Optional image attached to the post.', null=True, upload_to='linkedin_posts/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=12)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When set (and status=scheduled), Huey publishes at this time.', null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('linkedin_post_id', models.CharField(blank=True, default='', help_text='LinkedIn URN returned on publish (x-restli-id).', max_length=255)),
                ('error_message', models.TextField(blank=True, default='', help_text='Last publish failure detail.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LinkedIn post',
                'verbose_name_plural': 'LinkedIn posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
