# Generated by Django 5.2.13 on 2026-07-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0139_seed_linkedin_personal_mcp_connector'),
    ]

    operations = [
        migrations.AddField(
            model_name='webappdiagnostic',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Set on the initial send from the language config; drives the UI expiration badge.', null=True),
        ),
    ]
