# Generated by Django 5.2.13 on 2026-07-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0140_webappdiagnostic_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalsection',
            name='section_type',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('executive_summary', 'Executive Summary'), ('context_diagnostic', 'Context & Diagnostic'), ('conversion_strategy', 'Conversion Strategy'), ('design_ux', 'Design & UX'), ('creative_support', 'Creative Support'), ('development_stages', 'Development Stages'), ('process_methodology', 'Process Methodology'), ('functional_requirements', 'Functional Requirements'), ('timeline', 'Timeline'), ('investment', 'Investment'), ('proposal_summary', 'Proposal Summary'), ('final_note', 'Final Note'), ('next_steps', 'Next Steps'), ('technical_document', 'Technical Document'), ('value_added_modules', 'Value Added Modules'), ('roi_projection', 'ROI Projection'), ('commercial_conditions', 'Commercial Conditions')], max_length=30),
        ),
    ]
