# Generated by Django 5.2.13 on 2026-07-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0142_backfill_ai_module_and_commercial_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(choices=[('COL', 'Colombia'), ('MEX', 'México'), ('USA', 'Estados Unidos')], db_index=True, default='COL', max_length=3)),
                ('name_es', models.CharField(max_length=255, verbose_name='Name (Spanish)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (English)')),
                ('note_es', models.TextField(blank=True, default='')),
                ('note_en', models.TextField(blank=True, default='')),
                ('hours', models.PositiveIntegerField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual sort order (lower first).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hour Package',
                'verbose_name_plural': 'Hour Packages',
                'ordering': ['nationality', 'order', 'hours'],
            },
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='nationality',
            field=models.CharField(choices=[('COL', 'Colombia'), ('MEX', 'México'), ('USA', 'Estados Unidos')], default='COL', help_text='Drives hour-package catalog seeding and suggested currency.', max_length=3),
        ),
    ]
