# Generated by Django 5.2.13 on 2026-07-09 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0144_seed_col_hour_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserecord',
            name='paid_from',
        ),
        migrations.RemoveField(
            model_name='expenserecord',
            name='pocket_movement',
        ),
    ]
