# Generated by Django 5.2.13 on 2026-07-10 00:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0145_remove_expenserecord_paid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='usd_exchange_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('4000'), max_digits=10),
        ),
    ]
