# Generated by Django 5.2.13 on 2026-07-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0146_accountingsettings_usd_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='hosting_expiry_reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hostingrecord',
            name='billing_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostingrecord',
            name='expiry_notice_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hostingrecord',
            name='expiry_notice_last_sent_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostingrecord',
            name='expiry_notice_target',
            field=models.DateField(blank=True, null=True),
        ),
    ]
