# Generated by Django 5.2.13 on 2026-07-10 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0147_accountingsettings_hosting_expiry_reminder_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hosting_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_documents', to='content.hostingrecord'),
        ),
        migrations.AddField(
            model_name='hostingrecord',
            name='client_contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hostingrecord',
            name='client_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='hostingrecord',
            name='client_identification',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='issuerprofile',
            name='default_payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
