# Generated by Django 5.2.13 on 2026-07-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0150_backfill_hosting_cycles'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourPackageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view_mode', models.CharField(choices=[('table', 'Tabla'), ('cards', 'Tarjetas'), ('compare', 'Comparativa')], default='table', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hour package settings',
                'verbose_name_plural': 'Hour package settings',
            },
        ),
    ]
