# Generated by Django 5.2.13 on 2026-07-10 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0152_reset_hour_package_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingchangelog',
            name='entity_type',
            field=models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto'), ('hosting', 'Hosting'), ('pocket', 'Bolsillo'), ('recurring', 'Pago recurrente'), ('ads', 'Ads'), ('card_snapshot', 'Saldo tarjeta'), ('statement', 'Extracto de tarjeta'), ('statement_tx', 'Transacción de extracto'), ('merchant_alias', 'Alias de comercio'), ('settings', 'Configuración')], max_length=20),
        ),
        migrations.CreateModel(
            name='CreditCardStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_name', models.CharField(db_index=True, max_length=100)),
                ('period_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('processed', 'Procesado')], default='draft', max_length=10)),
                ('purchases_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('previous_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payments_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('interest_and_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('minimum_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Card Statement',
                'verbose_name_plural': 'Credit Card Statements',
                'ordering': ['-period_date', 'card_name'],
            },
        ),
        migrations.CreateModel(
            name='CreditCardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateField()),
                ('raw_description', models.CharField(max_length=255)),
                ('merchant_name', models.CharField(blank=True, default='', max_length=150)),
                ('category', models.CharField(choices=[('software', 'Software y suscripciones'), ('advertising', 'Publicidad'), ('fuel', 'Gasolina'), ('groceries', 'Supermercado'), ('restaurants', 'Restaurantes'), ('utilities', 'Servicios'), ('travel', 'Viajes'), ('shopping', 'Compras'), ('other', 'Otros')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('original_currency', models.CharField(blank=True, default='', max_length=3)),
                ('installment_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('installments_total', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_identified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='content.creditcardstatement')),
            ],
            options={
                'verbose_name': 'Credit Card Transaction',
                'verbose_name_plural': 'Credit Card Transactions',
                'ordering': ['transaction_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MerchantAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_text', models.CharField(max_length=255, unique=True)),
                ('merchant_name', models.CharField(max_length=150)),
                ('default_category', models.CharField(choices=[('software', 'Software y suscripciones'), ('advertising', 'Publicidad'), ('fuel', 'Gasolina'), ('groceries', 'Supermercado'), ('restaurants', 'Restaurantes'), ('utilities', 'Servicios'), ('travel', 'Viajes'), ('shopping', 'Compras'), ('other', 'Otros')], default='other', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant Alias',
                'verbose_name_plural': 'Merchant Aliases',
                'ordering': ['match_text'],
            },
        ),
        migrations.AddConstraint(
            model_name='creditcardstatement',
            constraint=models.UniqueConstraint(fields=('card_name', 'period_date'), name='uniq_statement_card_period'),
        ),
        migrations.AddIndex(
            model_name='creditcardtransaction',
            index=models.Index(fields=['statement', 'transaction_date'], name='content_cre_stateme_b262f3_idx'),
        ),
    ]
