# Generated by Django 5.2.13 on 2026-07-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0153_credit_card_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='template_style',
            field=models.CharField(choices=[('professional', 'Profesional'), ('friendly', 'Amigable')], default='professional', help_text='Estilo de PDF por defecto: profesional o amigable.', max_length=20),
        ),
    ]
