# Generated by Django 5.2.13 on 2026-07-11 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0154_document_template_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='pocket_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_record', to='content.pocketmovement'),
        ),
    ]
