# Generated by Django 5.2.13 on 2026-07-11 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0156_behavior_tracking_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='statement_reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='statement_reminder_last_sent_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditcardstatement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='statement_pdfs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='accountingchangelog',
            name='entity_type',
            field=models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto'), ('hosting', 'Hosting'), ('pocket', 'Bolsillo'), ('recurring', 'Pago recurrente'), ('ads', 'Ads'), ('card_snapshot', 'Saldo tarjeta'), ('credit_card', 'Tarjeta de crédito'), ('statement', 'Extracto de tarjeta'), ('statement_tx', 'Transacción de extracto'), ('merchant_alias', 'Alias de comercio'), ('settings', 'Configuración')], max_length=20),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('source_ref', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('statements_since', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'ordering': ['name'],
            },
        ),
    ]
