# Generated by Django 5.2.13 on 2026-07-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0158_seed_credit_card_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomerecord',
            name='kind',
            field=models.CharField(choices=[('expected', 'Esperado'), ('liquid', 'Líquido'), ('lost', 'Perdido')], max_length=10),
        ),
    ]
