# Generated by Django 5.2.13 on 2026-07-16 14:07

from django.db import migrations, models


def set_config_hosting_percent(apps, schema_editor):
    """Align existing default-config rows with the new 60% hosting default.

    The stored value (30) predates the fix that actually wires this config
    into proposal creation; the owner-approved default going forward is 60.
    Existing proposals keep their own hosting_percent untouched.
    """
    ProposalDefaultConfig = apps.get_model('content', 'ProposalDefaultConfig')
    ProposalDefaultConfig.objects.update(hosting_percent=60)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0160_nationality_ext_and_july_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessproposal',
            name='hosting_percent',
            field=models.PositiveIntegerField(default=60, help_text='Percentage of total investment charged for annual hosting.'),
        ),
        migrations.AlterField(
            model_name='proposaldefaultconfig',
            name='hosting_percent',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.RunPython(set_config_hosting_percent,
                             migrations.RunPython.noop),
    ]
