# Generated by Django 5.2.13 on 2026-07-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0161_hosting_percent_default_60'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardtransaction',
            name='is_reversal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='merchantalias',
            name='is_gateway',
            field=models.BooleanField(default=False),
        ),
    ]
