# Generated by Django 5.2.13 on 2026-07-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0162_creditcardtransaction_is_reversal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewMapSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view_mode', models.CharField(choices=[('list', 'Lista'), ('map', 'Mapa')], default='list', max_length=10)),
                ('default_filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'View map settings',
                'verbose_name_plural': 'View map settings',
            },
        ),
    ]
