# Generated by Django 5.2.13 on 2026-07-27 23:51

from decimal import Decimal
from django.db import migrations, models

# Settings field per nationality (kept literal: migrations must not import app code).
BASE_RATE_FIELDS = {
    'COL': 'base_rate_col',
    'EXT': 'base_rate_ext',
    'USA': 'base_rate_usa',
}


def seed_base_rates_from_catalog(apps, schema_editor):
    """Initialize each base rate from the current catalog's leading package.

    Uses the first active package by (order, hours) of each nationality —
    "Hora Puntual" in the default ladder. Nationalities without active
    packages keep the field default.
    """
    HourPackage = apps.get_model('content', 'HourPackage')
    HourPackageSettings = apps.get_model('content', 'HourPackageSettings')

    settings, _ = HourPackageSettings.objects.get_or_create(pk=1)
    changed = False
    for nationality, field in BASE_RATE_FIELDS.items():
        leader = (
            HourPackage.objects
            .filter(nationality=nationality, is_active=True)
            .order_by('order', 'hours')
            .first()
        )
        if leader is not None:
            setattr(settings, field, leader.hourly_rate)
            changed = True
    if changed:
        settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0165_update_default_contract_template_v5'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourpackagesettings',
            name='base_rate_col',
            field=models.DecimalField(decimal_places=2, default=Decimal('30000'), max_digits=14),
        ),
        migrations.AddField(
            model_name='hourpackagesettings',
            name='base_rate_ext',
            field=models.DecimalField(decimal_places=2, default=Decimal('18'), max_digits=14),
        ),
        migrations.AddField(
            model_name='hourpackagesettings',
            name='base_rate_usa',
            field=models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=14),
        ),
        migrations.RunPython(
            seed_base_rates_from_catalog, migrations.RunPython.noop,
        ),
    ]
