# Generated by Django 5.2.13 on 2026-07-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0168_repair_draft_scope_clause'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='deduction_type',
            field=models.CharField(blank=True, choices=[('gateway_fee', 'Comisión plataforma de pago'), ('bank_fee', 'Comisión bancaria'), ('withholding', 'Retención en la fuente'), ('other', 'Otro')], default='', max_length=20),
        ),
    ]
