# Generated by Django 5.2.13 on 2026-07-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0169_expenserecord_deduction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessproposal',
            name='nationality',
            field=models.CharField(choices=[('COL', 'Colombia'), ('EXT', 'Extranjeros'), ('USA', 'Estados Unidos')], default='COL', help_text='Drives hour-package catalog seeding and suggested currency.', max_length=3),
        ),
        migrations.AlterField(
            model_name='hourpackage',
            name='nationality',
            field=models.CharField(choices=[('COL', 'Colombia'), ('EXT', 'Extranjeros'), ('USA', 'Estados Unidos')], db_index=True, default='COL', max_length=3),
        ),
    ]
