# Generated by Django 5.2.13 on 2026-08-01 13:41

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify

# Seed taxonomy, in display order. Categories are user-editable from the
# panel afterwards; this is only the starting point.
SEED_CATEGORIES = [
    'Suscripciones de IA',
    'Anuncios / publicidad',
    'Arquitectura e infraestructura',
    'Extras / otros',
]

# Existing records classified by exact name. Anything not listed (fake data,
# staging fixtures, records added after this migration was written) falls back
# to 'Extras / otros' rather than staying uncategorized.
PAYMENTS_BY_CATEGORY = {
    'Suscripciones de IA': ['Claude Code 20x', 'Chat-GPT'],
    'Anuncios / publicidad': [
        'Google Ads - Campañas',
        'Google Ads - Empresa Marketing',
        'FB Anuncios & Publicidad',
    ],
    'Arquitectura e infraestructura': ['Hostinger', 'GoDaddy', 'NameCheap'],
    'Extras / otros': ['Netflix', 'Figma'],
}

FALLBACK_CATEGORY = 'Extras / otros'


def seed_and_classify(apps, schema_editor):
    RecurringCategory = apps.get_model('content', 'RecurringCategory')
    RecurringPayment = apps.get_model('content', 'RecurringPayment')

    categories = {}
    for position, name in enumerate(SEED_CATEGORIES):
        # Historical models have no custom save(), so the slug is set here.
        category, _ = RecurringCategory.objects.get_or_create(
            name=name,
            defaults={'slug': slugify(name), 'order': position},
        )
        categories[name] = category

    category_by_payment_name = {
        payment_name: categories[category_name]
        for category_name, payment_names in PAYMENTS_BY_CATEGORY.items()
        for payment_name in payment_names
    }
    fallback = categories[FALLBACK_CATEGORY]

    # Number each category's rows following today's alphabetical order, so the
    # first render matches what the operator already sees.
    payments = list(RecurringPayment.objects.all().order_by('name'))
    for payment in payments:
        payment.category = category_by_payment_name.get(payment.name, fallback)

    counters = {}
    for payment in payments:
        key = payment.category_id
        payment.order = counters.get(key, 0)
        counters[key] = payment.order + 1

    if payments:
        RecurringPayment.objects.bulk_update(payments, ['category', 'order'])


def unclassify(apps, schema_editor):
    """Detach payments so the CreateModel rollback is not blocked by PROTECT."""
    RecurringPayment = apps.get_model('content', 'RecurringPayment')
    RecurringPayment.objects.update(category=None)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0170_alter_businessproposal_nationality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual sort order (lower first).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Recurring categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='recurringpayment',
            options={'ordering': ['category__order', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Manual sort order within its category (lower first).'),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='content.recurringcategory'),
        ),
        migrations.RunPython(seed_and_classify, unclassify),
    ]
