# Generated by Django 5.2.13 on 2026-08-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0171_recurring_category_and_order'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='proposalchangelog',
            index=models.Index(fields=['proposal', '-created_at'], name='pcl_proposal_created_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalchangelog',
            index=models.Index(fields=['proposal', 'change_type'], name='pcl_proposal_type_idx'),
        ),
    ]
