# Generated by Django 5.2.13 on 2026-08-04 21:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0173_expense_source_income_and_regross'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('destination_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QR Card',
                'verbose_name_plural': 'QR Cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
