# Generated by Django 5.2.13 on 2026-08-05 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_userprofile_billing_code_userprofile_nit'),
        ('content', '0174_qrcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='income_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_documents', to='content.incomerecord'),
        ),
        migrations.CreateModel(
            name='ClientDocumentNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('client_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_number_sequence', to='accounts.userprofile')),
            ],
        ),
    ]
