# Generated by Django 5.2.13 on 2026-08-05 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_userprofile_billing_code_userprofile_nit'),
        ('content', '0175_document_income_record_clientdocumentnumbersequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incomerecord',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_records', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='origin',
            field=models.CharField(blank=True, choices=[('development', 'Desarrollo'), ('hosting', 'Hosting'), ('diagnostic', 'Diagnóstico'), ('other', 'Otro')], default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='incomerecord',
            index=models.Index(fields=['client', 'period_date'], name='content_inc_client__5fc612_idx'),
        ),
    ]
