# Generated by Django 5.2.13 on 2026-08-05 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_userprofile_billing_code_userprofile_nit'),
        ('content', '0176_incomerecord_client_incomerecord_origin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostingrecord',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosting_records', to='accounts.userprofile'),
        ),
        migrations.AddIndex(
            model_name='hostingrecord',
            index=models.Index(fields=['client'], name='content_hos_client__3bc3c6_idx'),
        ),
    ]
