# Generated by Django 5.2.13 on 2026-08-08 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0177_hostingrecord_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpayment',
            name='custom_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Sólo para la frecuencia personalizada: cada cuántos meses se cobra.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Mensual'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('four_monthly', 'Cuatrimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual'), ('biennial', 'Cada 2 años'), ('triennial', 'Cada 3 años'), ('custom', 'Personalizada')], default='monthly', max_length=20),
        ),
    ]
