# Generated by Django 5.2.13 on 2026-08-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0179_update_default_contract_template_v6'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='contractor_cedula',
            field=models.CharField(blank=True, default='', help_text='Cédula del contratista. Se usa en los documentos sólo si no hay NIT.', max_length=30),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='contractor_nit',
            field=models.CharField(blank=True, default='', help_text='NIT del contratista. Tiene prioridad sobre la cédula en los documentos.', max_length=30),
        ),
        migrations.AlterField(
            model_name='contracttemplate',
            name='content_markdown',
            field=models.TextField(help_text='Markdown text. Use {client_full_name}, {contractor_id_type}, {contractor_id_number}, etc. for placeholders. Prefer the {contractor_id_*} pair over {contractor_nit}: it resolves to the NIT when there is one and to the cédula otherwise, and carries the matching label.'),
        ),
    ]
