# Generated by Django 5.2.13 on 2026-08-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0181_update_default_contract_template_v7'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='archived_via_folder',
            field=models.ForeignKey(blank=True, help_text='Carpeta cuyo archivado arrastró a este documento. NULL = archivado por sí mismo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cascade_archived_documents', to='content.documentfolder'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='archived_via_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cascade_archived_folders', to='content.documentfolder'),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
