# Generated by Django 5.2.13 on 2026-08-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0182_document_archive_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpaymentmethod',
            name='payment_method_type',
            field=models.CharField(choices=[('bank_transfer', 'Transferencia bancaria'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('wompi', 'Wompi'), ('cash', 'Efectivo'), ('other', 'Otro')], default='bank_transfer', max_length=32),
        ),
    ]
