# Generated by Django 5.2.13 on 2026-08-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0183_payment_method_spanish_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='income_default_view_mode',
            field=models.CharField(choices=[('grouped', 'Agrupado'), ('classic', 'Clásico')], default='grouped', max_length=10),
        ),
    ]
