# Generated by Django 5.2.13 on 2026-08-11 18:35

from django.db import migrations, models
from django.db.models import F


def arm_legacy_overdue_incomes(apps, schema_editor):
    """Stop years of backlog from firing all at once on deploy day.

    Every expected income already past its date has ``reminder_last_sent_at``
    empty, which the cadence reads as "never announced" and fires on the first
    run. Arming them as if they had just been announced pushes their first
    overdue notice one full frequency past the deploy, which is the window the
    operator needs to mute or write off the dead ones.

    Both fields are set together: a target without a last-sent date is a state
    the re-arm filter would never repair.
    """
    from content.utils import today_bogota

    IncomeRecord = apps.get_model('content', 'IncomeRecord')
    today = today_bogota()
    IncomeRecord.objects.filter(kind='expected', period_date__lt=today).update(
        reminder_target_date=F('period_date'),
        reminder_last_sent_at=today,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0184_accountingsettings_income_default_view_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='overdue_reminder_frequency',
            field=models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal')], default='biweekly', max_length=10),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='payment_calendar_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='reminder_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='reminder_last_sent_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='reminder_target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='reminders_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='reminders_muted_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='cycle_anchor_date',
            field=models.DateField(blank=True, help_text='Cualquier fecha de cobro conocida: a partir de ella se calculan las siguientes.', null=True),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='reminder_last_sent_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='reminder_target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(
            arm_legacy_overdue_incomes, migrations.RunPython.noop,
        ),
    ]
