# Generated by Django 5.2.13 on 2026-08-12 21:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0185_payment_calendar_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linktree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handle', models.CharField(help_text='Identificador público de la URL: projectapp.co/lk/@<handle>', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El handle debe tener entre 3 y 30 caracteres: minúsculas, números, guion, guion bajo o punto, y empezar con letra o número.', regex='^[a-z0-9][a-z0-9_.-]{2,29}$')])),
                ('name', models.CharField(help_text='Nombre interno en el panel', max_length=255)),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('company', 'Empresa')], default='personal', max_length=10)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('bio', models.TextField(blank=True, default='')),
                ('monogram', models.CharField(blank=True, default='', max_length=3)),
                ('claim_line_1', models.CharField(blank=True, default='', max_length=120)),
                ('claim_line_2', models.CharField(blank=True, default='', max_length=120)),
                ('badge_text', models.CharField(blank=True, default='', max_length=40)),
                ('footer_tagline', models.CharField(blank=True, default='DISEÑO · CÓDIGO · RESULTADOS', max_length=80)),
                ('show_brand_header', models.BooleanField(default=True)),
                ('pwa_enabled', models.BooleanField(default=True)),
                ('pwa_title', models.CharField(blank=True, default='Guarda la tarjeta en tu teléfono', max_length=120)),
                ('pwa_description', models.CharField(blank=True, default='Queda como un ícono en tu pantalla de inicio, sin instalar nada de la tienda.', max_length=200)),
                ('vcard_first_name', models.CharField(blank=True, default='', max_length=80)),
                ('vcard_last_name', models.CharField(blank=True, default='', max_length=80)),
                ('vcard_org', models.CharField(blank=True, default='ProjectApp.', max_length=120)),
                ('vcard_email', models.EmailField(blank=True, default='', max_length=254)),
                ('vcard_tel', models.CharField(blank=True, default='', max_length=30)),
                ('vcard_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Linktree',
                'verbose_name_plural': 'Linktrees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='qrcard',
            name='destination_type',
            field=models.CharField(choices=[('url', 'URL directa'), ('linktree', 'Linktree')], default='url', max_length=10),
        ),
        migrations.AddField(
            model_name='qrcard',
            name='linktree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='content.linktree'),
        ),
        migrations.CreateModel(
            name='LinktreeButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('primary', 'Principal'), ('featured', 'Destacado'), ('pair', 'Par'), ('row', 'Fila')], default='row', max_length=10)),
                ('action', models.CharField(choices=[('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('email', 'Correo'), ('web', 'Web'), ('instagram', 'Instagram'), ('vcard', 'Guardar contacto'), ('install', 'Instalar'), ('custom', 'Personalizado')], default='web', max_length=12)),
                ('label', models.CharField(max_length=80)),
                ('href', models.CharField(blank=True, default='', max_length=500)),
                ('icon', models.CharField(blank=True, default='', help_text='Nombre de ícono Lucide; solo aplica cuando action=custom', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('linktree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='content.linktree')),
            ],
            options={
                'verbose_name': 'Linktree Button',
                'verbose_name_plural': 'Linktree Buttons',
                'ordering': ['order', 'id'],
            },
        ),
    ]
