# Generated by Django 5.2.13 on 2026-08-12 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_savedfiltertab_view'),
        ('content', '0185_payment_calendar_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcollectionaccount',
            name='customer_project_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hostingrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosting_records', to='accounts.project'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='accounts.project'),
        ),
        migrations.AddIndex(
            model_name='hostingrecord',
            index=models.Index(fields=['project'], name='content_hos_project_a6a699_idx'),
        ),
        migrations.AddIndex(
            model_name='incomerecord',
            index=models.Index(fields=['project', 'period_date'], name='content_inc_project_a7747d_idx'),
        ),
    ]
