# Generated by Django 5.2.13 on 2026-08-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0187_linktree_and_qrcard_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linktree',
            name='monogram',
        ),
        migrations.AddField(
            model_name='linktree',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='linktrees/avatars/'),
        ),
    ]
