# Generated by Django 5.2.13 on 2026-08-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    # Both leaves of main: 0187_merge (archive repair + project relation) and
    # 0188 (linktree) had no common descendant, so the graph carried two heads.
    # Depending on both collapses it back to one.
    dependencies = [
        ('content', '0187_merge_archive_repair_and_project_relation'),
        ('content', '0188_linktree_avatar_replaces_monogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='description',
            field=models.TextField(),
        ),
    ]
