# Generated by Django 5.2.13 on 2026-08-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0189_documentitem_description_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostingrecord',
            options={'ordering': ['client_name', 'project__name']},
        ),
    ]
