# Generated by Django 5.2.13 on 2026-08-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0192_link_hosting_projects_from_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Body',
                'verbose_name_plural': 'Email Bodies',
            },
        ),
        migrations.CreateModel(
            name='EmailLogTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto'), ('hosting', 'Hosting'), ('pocket', 'Bolsillo'), ('recurring', 'Pago recurrente'), ('ads', 'Ads'), ('card_snapshot', 'Saldo tarjeta'), ('credit_card', 'Tarjeta de crédito'), ('statement', 'Extracto de tarjeta'), ('statement_tx', 'Transacción de extracto'), ('merchant_alias', 'Alias de comercio'), ('notification_recipient', 'Destinatario de notificación'), ('settings', 'Configuración'), ('collection_account', 'Cuenta de cobro'), ('payment', 'Pago de plataforma')], max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Email Log Target',
                'verbose_name_plural': 'Email Log Targets',
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='origin_action',
            field=models.CharField(blank=True, choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('deleted', 'Eliminado')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='content.emaillog'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='content.emailbody'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient'], name='content_ema_recipie_a0fa37_idx'),
        ),
        migrations.AddField(
            model_name='emaillogtarget',
            name='email_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='content.emaillog'),
        ),
        migrations.AddIndex(
            model_name='emaillogtarget',
            index=models.Index(fields=['entity_type', 'object_id'], name='content_ema_entity__ac843f_idx'),
        ),
        migrations.AddConstraint(
            model_name='emaillogtarget',
            constraint=models.UniqueConstraint(fields=('email_log', 'entity_type', 'object_id'), name='uniq_email_log_target'),
        ),
    ]
