# Generated by Django 5.2.13 on 2026-08-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0194_backfill_email_log_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomerecord',
            name='period_cadence',
            field=models.CharField(blank=True, choices=[('monthly', 'Mensual'), ('bimonthly', 'Bimestral'), ('quarterly', 'Trimestral'), ('four_monthly', 'Cuatrimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual'), ('biennial', 'Cada 2 años'), ('triennial', 'Cada 3 años'), ('custom', 'Personalizada')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
