# Generated by Django 5.2.13 on 2026-08-16 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_drop_client_status_tabs'),
        ('content', '0199_accountingchangelog_project_collection_entity_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfolder',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_document_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_folders', to='accounts.project'),
        ),
    ]
