# Generated by Django 5.2.13 on 2026-08-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0200_documentfolder_client_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingchangelog',
            name='entity_type',
            field=models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto'), ('hosting', 'Hosting'), ('pocket', 'Bolsillo'), ('recurring', 'Pago recurrente'), ('ads', 'Ads'), ('card_snapshot', 'Saldo tarjeta'), ('credit_card', 'Tarjeta de crédito'), ('statement', 'Extracto de tarjeta'), ('statement_tx', 'Transacción de extracto'), ('merchant_alias', 'Alias de comercio'), ('notification_recipient', 'Destinatario de notificación'), ('settings', 'Configuración'), ('project', 'Proyecto'), ('collection_account', 'Cuenta de cobro'), ('document_folder', 'Carpeta de documentos'), ('document', 'Documento')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emaillogtarget',
            name='entity_type',
            field=models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto'), ('hosting', 'Hosting'), ('pocket', 'Bolsillo'), ('recurring', 'Pago recurrente'), ('ads', 'Ads'), ('card_snapshot', 'Saldo tarjeta'), ('credit_card', 'Tarjeta de crédito'), ('statement', 'Extracto de tarjeta'), ('statement_tx', 'Transacción de extracto'), ('merchant_alias', 'Alias de comercio'), ('notification_recipient', 'Destinatario de notificación'), ('settings', 'Configuración'), ('project', 'Proyecto'), ('collection_account', 'Cuenta de cobro'), ('document_folder', 'Carpeta de documentos'), ('document', 'Documento'), ('payment', 'Pago de plataforma')], max_length=30),
        ),
    ]
