# Generated by Django 5.2.17 on 2026-08-25 19:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_hosting_nine_month_terms'),
        ('content', '0209_client_email_copy_recipients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_attachments', to='content.document')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Correo'), ('whatsapp', 'WhatsApp')], max_length=12)),
                ('direction', models.CharField(choices=[('outgoing', 'Saliente'), ('incoming', 'Entrante')], max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado'), ('received', 'Recibido'), ('failed', 'Fallido')], max_length=10)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('content', models.TextField()),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('manual', 'Registro manual'), ('platform_email', 'Correo enviado por la plataforma'), ('legacy_email', 'Correo histórico importado')], default='manual', max_length=20)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_messages_created', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='communication_messages', through='content.CommunicationAttachment', to='content.document')),
                ('email_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_message', to='content.emaillog')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='content.communicationmessage')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_messages_updated', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_messages_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='communicationattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.communicationmessage'),
        ),
        migrations.CreateModel(
            name='CommunicationMessageDateCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_occurred_at', models.DateTimeField()),
                ('corrected_occurred_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_date_corrections', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_corrections', to='content.communicationmessage')),
            ],
            options={
                'ordering': ['-corrected_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], db_index=True, default='open', max_length=10)),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='communication_threads', to='accounts.userprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_threads_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_threads', to='accounts.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_threads_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='communicationmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='content.communicationthread'),
        ),
        migrations.AddConstraint(
            model_name='communicationattachment',
            constraint=models.UniqueConstraint(fields=('message', 'document'), name='unique_communication_document'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['client', 'status', 'last_activity_at'], name='commthread_client_status_at'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['project', 'status', 'last_activity_at'], name='commthread_project_status_at'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['thread', 'occurred_at'], name='commmessage_thread_at'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['channel', 'direction', 'status'], name='commmessage_route_status'),
        ),
    ]
