# Generated by Django 5.2.17 on 2026-08-25 19:39

import unicodedata

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _normalized_name(value):
    normalized = unicodedata.normalize('NFKD', str(value or '').strip())
    without_accents = ''.join(
        character for character in normalized
        if not unicodedata.combining(character)
    )
    return ' '.join(without_accents.casefold().split())


def seed_states_and_expand_legacy_data(apps, schema_editor):
    Document = apps.get_model('content', 'Document')
    DocumentNote = apps.get_model('content', 'DocumentNote')
    DocumentState = apps.get_model('content', 'DocumentState')
    DocumentStateEpisode = apps.get_model('content', 'DocumentStateEpisode')
    DocumentStateEpisodeEvent = apps.get_model(
        'content', 'DocumentStateEpisodeEvent',
    )
    DocumentStateGroup = apps.get_model('content', 'DocumentStateGroup')
    DocumentTag = apps.get_model('content', 'DocumentTag')
    DocumentType = apps.get_model('content', 'DocumentType')

    cycle = DocumentStateGroup.objects.create(
        name='Ciclo', selection_mode='exclusive', order=0,
    )
    signals = DocumentStateGroup.objects.create(
        name='Señales', selection_mode='additive', order=1,
    )
    seed_rows = (
        ('Borrador', 'draft', 'gray', cycle, 0),
        ('Enviado', 'sent', 'blue', cycle, 1),
        ('En revisión', 'in_review', 'yellow', cycle, 2),
        ('Bug atendido', 'bug_resolved', 'emerald', cycle, 3),
        ('Cerrado', 'closed', 'purple', cycle, 4),
        ('Solucionar bug', 'needs_fix', 'red', signals, 0),
    )
    seeded = {}
    for name, system_key, color, group, order in seed_rows:
        state = DocumentState.objects.create(
            name=name,
            normalized_name=_normalized_name(name),
            slug=system_key.replace('_', '-'),
            system_key=system_key,
            color=color,
            group=group,
            order=order,
        )
        seeded[system_key] = state
    seeded['needs_fix'].incompatibilities.add(
        seeded['bug_resolved'], seeded['closed'],
    )

    # Published used to carry two meanings. From now on it only migrates the
    # client-portal visibility gate; no cycle state is inferred from it.
    Document.objects.filter(status='published').update(is_client_visible=True)

    tag_state_ids = {}
    next_order = 100
    for tag in DocumentTag.objects.all().order_by('id'):
        normalized = _normalized_name(tag.name)
        existing = DocumentState.objects.filter(normalized_name=normalized).first()
        if existing:
            state = existing
        else:
            slug = tag.slug or f'estado-{tag.pk}'
            if DocumentState.objects.filter(slug=slug).exists():
                slug = f'legacy-{tag.pk}-{slug}'[:80]
            state = DocumentState.objects.create(
                name=tag.name,
                normalized_name=normalized,
                slug=slug,
                color=tag.color,
                group=signals,
                order=next_order,
            )
            next_order += 1
        tag_state_ids[tag.pk] = state.pk

    collection_type_ids = list(
        DocumentType.objects.filter(code='collection_account')
        .values_list('id', flat=True),
    )
    excluded_document_ids = set(
        Document.objects.filter(document_type_id__in=collection_type_ids)
        .values_list('id', flat=True),
    )
    assignment_model = Document.tags.through
    for document_id, tag_id in assignment_model.objects.values_list(
        'document_id', 'documenttag_id',
    ).iterator():
        if document_id in excluded_document_ids:
            continue
        state_id = tag_state_ids.get(tag_id)
        if not state_id:
            continue
        episode = DocumentStateEpisode.objects.create(
            document_id=document_id,
            state_id=state_id,
            opened_at=None,
            origin='migration',
        )
        DocumentStateEpisodeEvent.objects.create(
            episode=episode,
            event_type='opened',
            effective_at=None,
            details={
                'origin': 'migration',
                'opening_time_known': False,
                'legacy_tag_id': tag_id,
            },
        )

    for document in Document.objects.exclude(client_custom_notes=[]).iterator():
        notes = document.client_custom_notes
        if not isinstance(notes, list):
            continue
        for order, note in enumerate(notes):
            if not isinstance(note, dict):
                continue
            title = str(note.get('title') or '').strip()
            content = str(note.get('content') or '').strip()
            if not title and not content:
                continue
            DocumentNote.objects.create(
                document=document,
                title=title,
                content=content or title,
                order=order,
                created_at_known=False,
            )


def preserve_expanded_data(apps, schema_editor):
    # Expand/contract migration: rolling back the schema drops these tables;
    # there is no truthful way to compress episode history back into one tag.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0209_client_email_copy_recipients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('selection_mode', models.CharField(choices=[('exclusive', 'Uno activo'), ('additive', 'Varios activos')], default='additive', max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='is_client_visible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='DocumentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('normalized_name', models.CharField(editable=False, max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('color', models.CharField(choices=[('gray', 'Gris'), ('emerald', 'Verde'), ('blue', 'Azul'), ('yellow', 'Amarillo'), ('orange', 'Naranja'), ('red', 'Rojo'), ('purple', 'Morado')], default='gray', max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('system_key', models.CharField(blank=True, help_text='Stable key for seeded integrations; names remain editable.', max_length=40, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incompatibilities', models.ManyToManyField(blank=True, to='content.documentstate')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_sources', to='content.documentstate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='content.documentstategroup')),
            ],
            options={
                'ordering': ('group__order', 'order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DocumentStateEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('completed', 'Cerrado'), ('removed', 'Quitado'), ('transitioned', 'Transicionado'), ('merged', 'Fusionado')], default='', max_length=16)),
                ('close_note', models.CharField(blank=True, default='', max_length=500)),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('note', 'Nota'), ('email', 'Correo'), ('migration', 'Migración'), ('mcp', 'MCP')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_episodes', to='content.document')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='content.documentstate')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Pendiente'), ('resolved', 'Resuelta'), ('discarded', 'Descartada')], default='open', max_length=12)),
                ('resolution_note', models.CharField(blank=True, default='', max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at_known', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_notes', to='content.document')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='content.documentstateepisode')),
            ],
            options={
                'ordering': ('order', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DocumentStateEpisodeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('opened', 'Abierto'), ('closed', 'Cerrado'), ('removed', 'Quitado'), ('transitioned', 'Transicionado'), ('merged', 'Fusionado'), ('opened_at_corrected', 'Fecha de apertura corregida')], max_length=24)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='content.documentstateepisode')),
            ],
            options={
                'ordering': ('-recorded_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='documentstateepisode',
            index=models.Index(fields=['document', 'closed_at'], name='content_doc_documen_af49aa_idx'),
        ),
        migrations.AddIndex(
            model_name='documentstateepisode',
            index=models.Index(fields=['state', 'closed_at'], name='content_doc_state_i_48979f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentnote',
            index=models.Index(fields=['document', 'status'], name='content_doc_documen_2e240b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentnote',
            index=models.Index(fields=['episode', 'status'], name='content_doc_episode_94d74b_idx'),
        ),
        migrations.AddIndex(
            model_name='documentstateepisodeevent',
            index=models.Index(fields=['episode', 'recorded_at'], name='content_doc_episode_64eeb7_idx'),
        ),
        migrations.RunPython(
            seed_states_and_expand_legacy_data,
            preserve_expanded_data,
        ),
    ]
