# Generated by Django 5.2.17 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0212_seed_communications_mcp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingsettings',
            name='collection_accounts_group_by',
            field=models.CharField(
                choices=[('client', 'Cliente'), ('project', 'Proyecto')],
                default='client',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='accountingsettings',
            name='collection_accounts_view_mode',
            field=models.CharField(
                choices=[('grouped', 'Agrupado'), ('classic', 'Clásico')],
                default='grouped',
                max_length=10,
            ),
        ),
    ]
