# Generated by Django 5.2.17 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_project_workflow_state'),
        ('content', '0212_seed_communications_mcp'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentstate',
            name='catalog',
            field=models.CharField(
                choices=[('documents', 'Documentos'), ('projects', 'Proyectos')],
                db_index=True,
                default='documents',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='documentstate',
            name='operational_effect',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'Sin efecto automático'),
                    ('development', 'En desarrollo'),
                    ('operating', 'Operativo'),
                    ('paused', 'Pausado'),
                    ('suspended', 'Cobros suspendidos'),
                    ('completed', 'Cierre correcto'),
                    ('decommissioned', 'Baja definitiva'),
                ],
                default='',
                help_text=(
                    'Project-side consequence policy; blank for document states.'
                ),
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='documentstateepisode',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='state_episodes',
                to='accounts.project',
            ),
        ),
        migrations.AddField(
            model_name='documentstategroup',
            name='catalog',
            field=models.CharField(
                choices=[('documents', 'Documentos'), ('projects', 'Proyectos')],
                db_index=True,
                default='documents',
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name='documentstate',
            name='normalized_name',
            field=models.CharField(editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='documentstate',
            name='slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='documentstate',
            name='system_key',
            field=models.CharField(
                blank=True,
                help_text=(
                    'Stable key for seeded integrations; names remain editable.'
                ),
                max_length=40,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='documentstateepisode',
            name='document',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='state_episodes',
                to='content.document',
            ),
        ),
        migrations.AlterField(
            model_name='documentstategroup',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='incomerecord',
            name='kind',
            field=models.CharField(
                choices=[
                    ('expected', 'Esperado'),
                    ('liquid', 'Líquido'),
                    ('lost', 'Perdido'),
                    ('cancelled', 'Cancelado'),
                ],
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name='documentstateepisode',
            index=models.Index(
                fields=['project', 'closed_at'],
                name='content_doc_project_70cfa7_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='documentstate',
            constraint=models.UniqueConstraint(
                fields=('catalog', 'normalized_name'),
                name='unique_state_name_per_catalog',
            ),
        ),
        migrations.AddConstraint(
            model_name='documentstate',
            constraint=models.UniqueConstraint(
                fields=('catalog', 'slug'),
                name='unique_state_slug_per_catalog',
            ),
        ),
        migrations.AddConstraint(
            model_name='documentstate',
            constraint=models.UniqueConstraint(
                condition=models.Q(system_key__isnull=False),
                fields=('catalog', 'system_key'),
                name='unique_state_system_key_per_catalog',
            ),
        ),
        migrations.AddConstraint(
            model_name='documentstateepisode',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(document__isnull=False, project__isnull=True)
                    | models.Q(document__isnull=True, project__isnull=False)
                ),
                name='state_episode_exactly_one_subject',
            ),
        ),
        migrations.AddConstraint(
            model_name='documentstategroup',
            constraint=models.UniqueConstraint(
                fields=('catalog', 'name'),
                name='unique_state_group_name_per_catalog',
            ),
        ),
    ]
