# Generated by Django 5.2.17 on 2026-08-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0213_accounting_collection_preferences'),
        ('content', '0214_seed_project_lifecycle_states'),
    ]

    operations = []
