# Generated by Django 5.2.17 on 2026-08-26 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0213_accounting_collection_preferences'),
        ('content', '0214_seed_project_lifecycle_states'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNoteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('deleted', 'Eliminada'), ('restored', 'Restaurada')], max_length=16)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-recorded_at', '-id'),
            },
        ),
        migrations.RemoveIndex(
            model_name='documentnote',
            name='content_doc_documen_2e240b_idx',
        ),
        migrations.RemoveIndex(
            model_name='documentnote',
            name='content_doc_episode_94d74b_idx',
        ),
        migrations.AddField(
            model_name='documentnote',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentnote',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='documentnote',
            index=models.Index(fields=['document', 'deleted_at', 'status'], name='content_doc_documen_721f5e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentnote',
            index=models.Index(fields=['episode', 'deleted_at', 'status'], name='content_doc_episode_db7874_idx'),
        ),
        migrations.AddField(
            model_name='documentnoteevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentnoteevent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_note_events', to='content.document'),
        ),
        migrations.AddField(
            model_name='documentnoteevent',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='content.documentnote'),
        ),
        migrations.AddIndex(
            model_name='documentnoteevent',
            index=models.Index(fields=['document', 'recorded_at'], name='content_doc_documen_936201_idx'),
        ),
    ]
