# Generated by Django 5.2.17 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0215_merge_accounting_preferences_project_lifecycle'),
        ('content', '0215_merge_email_copy_accounting_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewmapsettings',
            name='default_view_mode',
            field=models.CharField(
                choices=[
                    ('list', 'Lista'),
                    ('map', 'Mapa'),
                    ('explorer', 'Explorador'),
                ],
                default='list',
                max_length=10,
            ),
        ),
    ]
