# Generated by Django 5.2.17 on 2026-08-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0216_document_note_soft_delete'),
        ('content', '0216_viewmapsettings_explorer'),
    ]

    operations = []
