# Generated by Django 5.2.17 on 2026-08-27 13:40

from django.db import migrations, models
from django.db.models import F, Q


PROJECT_DESCRIPTIONS = {
    'development': (
        'El proyecto se está construyendo y todavía no se considera entregado '
        'ni en operación.'
    ),
    'active': (
        'Está entregado y operando, sin una nueva versión relevante en '
        'desarrollo.'
    ),
    'evolving': (
        'Está en producción y funcionando mientras se desarrolla una siguiente '
        'versión o ampliación.'
    ),
    'paused': (
        'El trabajo está detenido temporalmente y se espera retomarlo.'
    ),
    'suspended': (
        'Dejó de operar temporalmente y puede volver cuando se resuelva la causa.'
    ),
    'completed': 'Terminó como debía y quedó cerrado correctamente.',
    'decommissioned': (
        'Terminó de forma definitiva y no se espera que vuelva; no atribuye '
        'culpa ni motivo.'
    ),
}

CUSTOM_DESCRIPTIONS = {
    'development': 'El proyecto se encuentra en una etapa de construcción.',
    'operating': 'El proyecto está entregado y se mantiene en operación.',
    'paused': 'El trabajo del proyecto está detenido temporalmente.',
    'suspended': 'El servicio del proyecto está suspendido y puede reactivarse.',
    'completed': 'El proyecto terminó correctamente y quedó cerrado.',
    'decommissioned': 'El proyecto terminó de forma definitiva.',
}


def add_project_state_help(apps, schema_editor):
    """Seed help copy and add the operating-but-changing lifecycle state."""
    DocumentState = apps.get_model('content', 'DocumentState')
    alias = schema_editor.connection.alias
    projects = DocumentState.objects.using(alias).filter(catalog='projects')

    active = projects.filter(system_key='active').first()
    if active is None:
        raise RuntimeError(
            'Cannot seed En evolución: the project catalog has no active state.'
        )

    evolving = projects.filter(system_key='evolving').first()
    if evolving is None:
        named = projects.filter(
            Q(normalized_name__in=('en evolucion', 'en evolución'))
            | Q(name__iexact='En evolución')
        ).first()
        if named is not None:
            if (
                named.group_id != active.group_id
                or named.operational_effect != 'operating'
                or not named.is_active
                or named.merged_into_id is not None
                or named.system_key not in (None, '')
            ):
                raise RuntimeError(
                    'Cannot adopt the existing En evolución state. It must be '
                    'active, unmerged, in the project lifecycle group and use '
                    'the operating effect.'
                )
            named.system_key = 'evolving'
            named.description = PROJECT_DESCRIPTIONS['evolving']
            named.save(update_fields=('system_key', 'description'))
            evolving = named
        else:
            insert_order = active.order + 1
            projects.filter(
                group_id=active.group_id,
                order__gte=insert_order,
            ).update(order=F('order') + 1)
            evolving = DocumentState.objects.using(alias).create(
                catalog='projects',
                name='En evolución',
                description=PROJECT_DESCRIPTIONS['evolving'],
                normalized_name='en evolucion',
                slug='evolving',
                color='blue',
                group_id=active.group_id,
                order=insert_order,
                system_key='evolving',
                operational_effect='operating',
            )
    elif evolving.operational_effect != 'operating':
        raise RuntimeError(
            'The evolving project state exists with a non-operating effect.'
        )

    for state in projects.iterator():
        if state.description.strip():
            continue
        state.description = PROJECT_DESCRIPTIONS.get(
            state.system_key,
            CUSTOM_DESCRIPTIONS.get(
                state.operational_effect,
                'Estado administrable del ciclo del proyecto.',
            ),
        )
        state.save(update_fields=('description',))


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0217_merge_disabled_controls_notes_viewmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentstate',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.RunPython(
            add_project_state_help,
            migrations.RunPython.noop,
        ),
    ]
