# Generated by Django 5.2.17 on 2026-08-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0218_documentstate_mysql_unique_system_key'),
        ('content', '0218_project_state_help'),
    ]

    operations = [
    ]
