# Generated by Django 5.2.17 on 2026-08-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0219_merge_20260827_1702'),
        ('content', '0219_rename_documents_mcp_connector'),
    ]

    operations = [
    ]
