# Generated by Django 6.1 on 2026-08-28

import content.models.email_delivery_snapshot
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0222_cross_cutting_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliverySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.UUIDField(db_index=True, unique=True)),
                ('template_key', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[('client', 'Al cliente'), ('internal', 'Interno'), ('security', 'Seguridad')], max_length=10)),
                ('family', models.CharField(blank=True, default='', max_length=40)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('from_email', models.CharField(blank=True, default='', max_length=320)),
                ('message_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('attachment_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('attachment_count', models.PositiveIntegerField(default=0)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_snapshot', to='content.emailbody')),
                ('resend_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resends', to='content.emaildeliverysnapshot')),
            ],
            options={
                'ordering': ['-captured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=content.models.email_delivery_snapshot.email_attachment_upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, default='application/octet-stream', max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('position', models.PositiveIntegerField(default=0)),
                ('format_kind', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('spreadsheet', 'Excel / hoja de cálculo'), ('image', 'Imagen'), ('other', 'Otro formato')], default='other', max_length=20)),
                ('business_kind', models.CharField(blank=True, default='', max_length=64)),
                ('business_kind_label', models.CharField(blank=True, default='', max_length=128)),
                ('source_document_type_code', models.CharField(blank=True, default='', max_length=64)),
                ('source_document_type_name', models.CharField(blank=True, default='', max_length=128)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_attachment_snapshots', to='content.document')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='content.emaildeliverysnapshot')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='content.emaildeliverysnapshot'),
        ),
        migrations.CreateModel(
            name='EmailLinkSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('label', models.CharField(blank=True, default='', max_length=500)),
                ('group', models.CharField(choices=[('content', 'Contenido'), ('template', 'Plantilla o firma')], default='content', max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='content.emaildeliverysnapshot')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='emaildeliverysnapshot',
            index=models.Index(fields=['template_key', 'captured_at'], name='content_ema_templat_1c7991_idx'),
        ),
        migrations.AddIndex(
            model_name='emaildeliverysnapshot',
            index=models.Index(fields=['family', 'captured_at'], name='content_ema_family_9e8df4_idx'),
        ),
        migrations.AddIndex(
            model_name='emailattachmentsnapshot',
            index=models.Index(fields=['format_kind'], name='content_ema_format__0146af_idx'),
        ),
        migrations.AddIndex(
            model_name='emailattachmentsnapshot',
            index=models.Index(fields=['business_kind'], name='content_ema_busines_e8b31e_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailattachmentsnapshot',
            constraint=models.UniqueConstraint(fields=('snapshot', 'position'), name='uniq_email_attachment_position'),
        ),
        migrations.AddConstraint(
            model_name='emaillinksnapshot',
            constraint=models.UniqueConstraint(fields=('snapshot', 'url'), name='uniq_email_snapshot_link'),
        ),
    ]
