# Generated by Django 6.1 on 2026-08-28 18:41

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_VISIBLE_PROJECT_STATE_KEYS = ('development', 'active', 'evolving')


def seed_document_manager_visibility(apps, schema_editor):
    DocumentState = apps.get_model('content', 'DocumentState')
    DocumentState.objects.using(schema_editor.connection.alias).filter(
        catalog='projects',
        system_key__in=DEFAULT_VISIBLE_PROJECT_STATE_KEYS,
    ).update(show_in_document_manager=True)


def clear_document_manager_visibility(apps, schema_editor):
    DocumentState = apps.get_model('content', 'DocumentState')
    DocumentState.objects.using(schema_editor.connection.alias).filter(
        catalog='projects',
    ).update(show_in_document_manager=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_project_workflow_state'),
        ('content', '0222_cross_cutting_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfolder',
            name='managed_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_root_folder', to='accounts.project'),
        ),
        migrations.AddField(
            model_name='documentstate',
            name='show_in_document_manager',
            field=models.BooleanField(default=False, help_text='Whether projects in this state appear in the default Documents project-folder list. Ignored for document states.'),
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(managed_project__isnull=True)
                    | models.Q(parent__isnull=True)
                ),
                name='managed_project_folder_is_root',
            ),
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(managed_project__isnull=True)
                    | models.Q(project=models.F('managed_project'))
                ),
                name='managed_folder_matches_project',
            ),
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(managed_project__isnull=True)
                    | models.Q(is_archived=False)
                ),
                name='managed_project_folder_is_active',
            ),
        ),
        migrations.RunPython(
            seed_document_manager_visibility,
            clear_document_manager_visibility,
        ),
    ]
