# Generated by Django 6.1 on 2026-08-28 18:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_project_workflow_state'),
        ('content', '0222_cross_cutting_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalModuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name_es', models.CharField(max_length=160)),
                ('name_en', models.CharField(max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Additional module category',
                'verbose_name_plural': 'Additional module categories',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('order',), name='uniq_additional_module_category_order')],
            },
        ),
        migrations.CreateModel(
            name='AdditionalModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name_es', models.CharField(max_length=240)),
                ('name_en', models.CharField(max_length=240)),
                ('summary_es', models.CharField(max_length=360)),
                ('summary_en', models.CharField(max_length=360)),
                ('what_is_es', models.TextField()),
                ('what_is_en', models.TextField()),
                ('purpose_es', models.TextField()),
                ('purpose_en', models.TextField()),
                ('problems_solved_es', models.JSONField(default=list)),
                ('problems_solved_en', models.JSONField(default=list)),
                ('integrations_es', models.JSONField(default=list)),
                ('integrations_en', models.JSONField(default=list)),
                ('implementation_requirements_es', models.JSONField(default=list)),
                ('implementation_requirements_en', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='content.additionalmodulecategory')),
            ],
            options={
                'verbose_name': 'Additional module',
                'verbose_name_plural': 'Additional modules',
                'ordering': ['category__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalModuleShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_label', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_module_share_links', to='accounts.userprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_additional_module_share_links', to=settings.AUTH_USER_MODEL)),
                ('selected_modules', models.ManyToManyField(related_name='share_links', to='content.additionalmodule')),
            ],
            options={
                'verbose_name': 'Additional module share link',
                'verbose_name_plural': 'Additional module share links',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalModuleShareView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='content.additionalmodulesharelink')),
            ],
            options={
                'verbose_name': 'Additional module share view',
                'verbose_name_plural': 'Additional module share views',
                'ordering': ['-viewed_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='additionalmodule',
            index=models.Index(fields=['is_active', 'category', 'order'], name='content_add_is_acti_327f6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='additionalmodule',
            constraint=models.UniqueConstraint(fields=('category', 'order'), name='uniq_additional_module_position'),
        ),
        migrations.AddIndex(
            model_name='additionalmoduleshareview',
            index=models.Index(fields=['share_link', 'viewed_at'], name='content_add_share_l_fea780_idx'),
        ),
        migrations.AddConstraint(
            model_name='additionalmoduleshareview',
            constraint=models.UniqueConstraint(fields=('share_link', 'session_id'), name='uniq_additional_module_share_session'),
        ),
    ]
