# Generated by Django 6.1 on 2026-08-28 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_commercial_proposal_type(apps, schema_editor):
    DocumentType = apps.get_model('content', 'DocumentType')
    DocumentType.objects.get_or_create(
        code='commercial_proposal',
        defaults={
            'name': 'Propuesta comercial',
            'description': 'Versión PDF inmutable enviada por el sistema.',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_project_workflow_state'),
        ('content', '0222_cross_cutting_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='generated_file',
            field=models.FileField(blank=True, default='', help_text='Immutable file generated and stored by a system workflow.', upload_to='documents/generated/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_proposal',
            field=models.ForeignKey(blank=True, help_text='Proposal whose immutable PDF snapshot produced this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='content.businessproposal'),
        ),
        migrations.AddField(
            model_name='document',
            name='source_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentfolder',
            name='system_key',
            field=models.CharField(blank=True, editable=False, help_text='Stable identifier for folders whose structure is managed by the system.', max_length=255, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('source_proposal', 'source_version'), name='unique_document_source_proposal_version'),
        ),
        migrations.RunPython(seed_commercial_proposal_type, migrations.RunPython.noop),
    ]
