# Generated by Django 6.1 on 2026-08-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0223_email_delivery_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachmentsnapshot',
            name='source_document',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='email_attachment_snapshots',
                to='content.document',
            ),
        ),
    ]
