from django.db import migrations


CATEGORIES = [
    ('commerce-transactions', 'Comercio y transacciones', 'Commerce and transactions'),
    ('identity-access', 'Identidad y acceso', 'Identity and access'),
    ('marketing-acquisition', 'Marketing y adquisición', 'Marketing and acquisition'),
    ('user-experience', 'Experiencia de usuario', 'User experience'),
    ('intelligence-tracking', 'Inteligencia y seguimiento', 'Intelligence and tracking'),
]


MODULES = [
    {
        'category': 'commerce-transactions',
        'slug': 'electronic-invoicing', 'icon': '🧾',
        'name_es': 'Facturación electrónica e integración DIAN',
        'name_en': 'Electronic invoicing and DIAN integration',
        'summary_es': 'Emite y sigue comprobantes fiscales desde los mismos flujos donde ocurre la venta.',
        'summary_en': 'Issue and track tax documents from the same workflows where the sale happens.',
        'what_is_es': 'Una conexión entre la plataforma y un proveedor de facturación electrónica autorizado para generar facturas, notas crédito, notas débito y documentos soporte sin volver a registrar la operación.',
        'what_is_en': 'A connection between the platform and an authorized electronic invoicing provider to generate invoices, credit notes, debit notes, and supporting documents without entering the transaction twice.',
        'purpose_es': 'Mantener la operación comercial y el cumplimiento fiscal sincronizados, con trazabilidad del estado de cada comprobante ante la DIAN.',
        'purpose_en': 'Keep commercial operations and tax compliance synchronized, with traceability of each document status before DIAN.',
        'problems_solved_es': ['Evita digitar la misma venta en dos sistemas.', 'Reduce errores de impuestos, clientes y productos.', 'Hace visible si un comprobante fue aceptado, rechazado o sigue en proceso.'],
        'problems_solved_en': ['Avoids entering the same sale in two systems.', 'Reduces tax, customer, and product errors.', 'Shows whether a document was accepted, rejected, or is still processing.'],
        'integrations_es': ['Siigo, Alegra u otro proveedor con API documentada.', 'Pedidos, pagos, clientes, productos e impuestos de la plataforma.', 'Correo y alertas internas para estados fiscales.'],
        'integrations_en': ['Siigo, Alegra, or another provider with a documented API.', 'Platform orders, payments, customers, products, and taxes.', 'Email and internal alerts for tax statuses.'],
        'implementation_requirements_es': ['Cuenta activa con el proveedor de facturación.', 'Resoluciones, numeración, impuestos y datos fiscales definidos.', 'Reglas claras sobre cuándo facturar, anular o emitir una nota.'],
        'implementation_requirements_en': ['An active account with the invoicing provider.', 'Defined resolutions, numbering, taxes, and tax identity data.', 'Clear rules for when to invoice, cancel, or issue a note.'],
    },
    {
        'category': 'commerce-transactions',
        'slug': 'regional-payment-gateways', 'icon': '🇨🇴',
        'name_es': 'Pasarelas de pago regionales',
        'name_en': 'Regional payment gateways',
        'summary_es': 'Recibe pagos en Colombia con los medios que tus clientes ya usan.',
        'summary_en': 'Accept payments in Colombia through methods your customers already use.',
        'what_is_es': 'Una integración de checkout y confirmación de pagos con proveedores colombianos como Wompi, PayU o ePayco, incluyendo tarjetas, PSE y medios alternativos según el proveedor.',
        'what_is_en': 'A checkout and payment-confirmation integration with Colombian providers such as Wompi, PayU, or ePayco, including cards, PSE, and alternative methods supported by the provider.',
        'purpose_es': 'Cobrar dentro del flujo digital y actualizar automáticamente pedidos, reservas, suscripciones o cuentas cuando el dinero se confirma.',
        'purpose_en': 'Collect payment inside the digital flow and automatically update orders, reservations, subscriptions, or accounts when funds are confirmed.',
        'problems_solved_es': ['Elimina confirmaciones manuales por comprobante o captura.', 'Mantiene pagos pendientes, aprobados y rechazados en un solo estado confiable.', 'Evita dobles cobros o dobles confirmaciones por reintentos del proveedor.'],
        'problems_solved_en': ['Removes manual confirmation from receipts or screenshots.', 'Keeps pending, approved, and rejected payments in one reliable status.', 'Prevents duplicate charges or confirmations caused by provider retries.'],
        'integrations_es': ['Wompi, PayU o ePayco.', 'Carrito, reservas, facturación, inventario o membresías.', 'Webhooks, conciliación y notificaciones de pago.'],
        'integrations_en': ['Wompi, PayU, or ePayco.', 'Cart, bookings, invoicing, inventory, or memberships.', 'Webhooks, reconciliation, and payment notifications.'],
        'implementation_requirements_es': ['Cuenta comercial aprobada en la pasarela.', 'Métodos de pago y monedas del alcance definidos.', 'Reglas para pendientes, vencimientos, reembolsos y conciliación.'],
        'implementation_requirements_en': ['An approved merchant account with the gateway.', 'Defined payment methods and currencies.', 'Rules for pending payments, expiration, refunds, and reconciliation.'],
    },
    {
        'category': 'commerce-transactions',
        'slug': 'international-payment-gateways', 'icon': '🌎',
        'name_es': 'Pasarelas de pago internacionales',
        'name_en': 'International payment gateways',
        'summary_es': 'Cobra a clientes de otros países con tarjetas, divisas y métodos globales.',
        'summary_en': 'Charge customers abroad using cards, currencies, and global payment methods.',
        'what_is_es': 'Una integración con Stripe, PayPal u otro proveedor global para pagos únicos o recurrentes, autenticación bancaria y confirmación segura del lado del servidor.',
        'what_is_en': 'An integration with Stripe, PayPal, or another global provider for one-time or recurring payments, bank authentication, and secure server-side confirmation.',
        'purpose_es': 'Abrir la venta a otros mercados sin construir infraestructura financiera propia y conservar el estado del cobro dentro de la plataforma.',
        'purpose_en': 'Open sales to other markets without building proprietary financial infrastructure while keeping payment status inside the platform.',
        'problems_solved_es': ['Permite cobrar en mercados y monedas diferentes.', 'Maneja autenticación 3D Secure y pagos que requieren pasos adicionales.', 'Centraliza reembolsos, disputas y suscripciones.'],
        'problems_solved_en': ['Enables charging across different markets and currencies.', 'Handles 3D Secure and payments that require additional steps.', 'Centralizes refunds, disputes, and subscriptions.'],
        'integrations_es': ['Stripe, PayPal u otra pasarela global con API.', 'Checkout, planes, suscripciones y acceso a servicios.', 'Facturación, correo y analítica de conversión.'],
        'integrations_en': ['Stripe, PayPal, or another global gateway with an API.', 'Checkout, plans, subscriptions, and service access.', 'Invoicing, email, and conversion analytics.'],
        'implementation_requirements_es': ['Cuenta habilitada en los países y monedas objetivo.', 'Política comercial de cobros, devoluciones y contracargos.', 'Definición de impuestos, precios y conversión de moneda fuera de la pasarela.'],
        'implementation_requirements_en': ['An account enabled for target countries and currencies.', 'Commercial policy for charges, refunds, and chargebacks.', 'Defined taxes, pricing, and currency conversion outside the gateway.'],
    },
    {
        'category': 'commerce-transactions',
        'slug': 'gift-cards', 'icon': '🎁',
        'name_es': 'Tarjetas de regalo y saldos',
        'name_en': 'Gift cards and stored balances',
        'summary_es': 'Vende crédito canjeable y conviértelo en una nueva vía de compra y recomendación.',
        'summary_en': 'Sell redeemable credit and turn it into a new purchase and referral channel.',
        'what_is_es': 'Un módulo para emitir códigos o tarjetas con saldo, fecha de vigencia y reglas de uso, que el destinatario puede aplicar total o parcialmente en una compra.',
        'what_is_en': 'A module for issuing codes or cards with a balance, validity period, and usage rules that recipients can apply fully or partially to a purchase.',
        'purpose_es': 'Facilitar regalos, campañas, compensaciones y crédito comercial sin depender de cupones de un solo uso.',
        'purpose_en': 'Support gifts, campaigns, compensation, and store credit without relying on single-use coupons.',
        'problems_solved_es': ['Permite que una persona compre para otra sin elegir el producto final.', 'Controla saldos parciales y evita canjes duplicados.', 'Da trazabilidad a emisión, entrega, uso, vencimiento y anulación.'],
        'problems_solved_en': ['Lets one person buy for another without choosing the final product.', 'Controls partial balances and prevents duplicate redemption.', 'Tracks issuance, delivery, use, expiration, and cancellation.'],
        'integrations_es': ['Checkout, catálogo, pedidos y cuentas de cliente.', 'Pasarelas de pago y correo de entrega.', 'Reportes de saldos emitidos, usados y pendientes.'],
        'integrations_en': ['Checkout, catalog, orders, and customer accounts.', 'Payment gateways and delivery email.', 'Reports for issued, used, and outstanding balances.'],
        'implementation_requirements_es': ['Reglas de vigencia, acumulación, devolución y transferibilidad.', 'Diseño y mensaje de la tarjeta.', 'Tratamiento contable y fiscal del saldo pendiente.'],
        'implementation_requirements_en': ['Validity, stacking, refund, and transfer rules.', 'Gift card design and message.', 'Accounting and tax treatment for outstanding balances.'],
    },
    {
        'category': 'identity-access',
        'slug': 'biometric-verification', 'icon': '🪪',
        'name_es': 'Verificación y validación biométrica',
        'name_en': 'Biometric identity verification',
        'summary_es': 'Confirma que la persona y su documento coinciden antes de habilitar una operación sensible.',
        'summary_en': 'Confirm that a person matches their identity document before enabling a sensitive operation.',
        'what_is_es': 'Una integración KYC con un proveedor especializado que combina lectura del documento, comparación facial y prueba de vida para devolver una decisión verificable.',
        'what_is_en': 'A KYC integration with a specialist provider that combines document reading, face matching, and liveness checks to return a verifiable decision.',
        'purpose_es': 'Reducir suplantación y fraude en registros, firmas, desembolsos, accesos o cambios críticos sin convertir el proceso en una revisión manual.',
        'purpose_en': 'Reduce impersonation and fraud in onboarding, signing, disbursements, access, or critical changes without turning the process into a manual review.',
        'problems_solved_es': ['Detecta documentos inconsistentes o rostros que no coinciden.', 'Distingue una persona presente de una foto o grabación.', 'Conserva evidencia y resultado para auditoría según la política acordada.'],
        'problems_solved_en': ['Detects inconsistent documents or non-matching faces.', 'Distinguishes a live person from a photo or recording.', 'Keeps evidence and results for audit under the agreed policy.'],
        'integrations_es': ['Proveedor biométrico/KYC elegido por el cliente.', 'Registro, login reforzado, firma o aprobación de operaciones.', 'Alertas y revisión manual para casos inconclusos.'],
        'integrations_en': ['Biometric/KYC provider selected by the client.', 'Onboarding, step-up login, signing, or transaction approval.', 'Alerts and manual review for inconclusive cases.'],
        'implementation_requirements_es': ['Contrato y cuenta con el proveedor, facturados por éste al cliente.', 'Base legal, consentimiento y política de retención de datos biométricos.', 'Criterios de aprobación, rechazo y revisión manual.'],
        'implementation_requirements_en': ['A provider contract and account billed directly to the client.', 'Legal basis, consent, and biometric-data retention policy.', 'Approval, rejection, and manual-review criteria.'],
    },
    {
        'category': 'marketing-acquisition',
        'slug': 'landing-page', 'icon': '🚀',
        'name_es': 'Landing page',
        'name_en': 'Landing page',
        'summary_es': 'Dale a campañas y visitantes un punto de llegada claro, medible y orientado a una acción.',
        'summary_en': 'Give campaigns and visitors a clear, measurable destination focused on one action.',
        'what_is_es': 'Una página pública enfocada en una oferta, audiencia y llamado a la acción. Presenta el valor esencial, responde objeciones y conduce al visitante hacia contacto, registro, compra o agenda.',
        'what_is_en': 'A public page focused on one offer, audience, and call to action. It presents the essential value, answers objections, and leads visitors to contact, signup, purchase, or booking.',
        'purpose_es': 'Crear el punto de partida que una plataforma necesita para recibir usuarios, explicar por qué entrar y medir de dónde vienen las oportunidades.',
        'purpose_en': 'Create the starting point a platform needs to receive users, explain why they should continue, and measure where opportunities come from.',
        'problems_solved_es': ['Evita enviar campañas a una página genérica o sin contexto.', 'Concentra el mensaje y la acción sin distraer al visitante.', 'Permite medir visitas, fuentes, formularios y conversiones.'],
        'problems_solved_en': ['Avoids sending campaigns to a generic or contextless page.', 'Concentrates the message and action without distracting visitors.', 'Measures visits, sources, forms, and conversions.'],
        'integrations_es': ['Formularios, CRM, agenda, WhatsApp o checkout.', 'Analítica, píxeles publicitarios y seguimiento de conversiones.', 'Chat, correo transaccional y dominio de la marca.'],
        'integrations_en': ['Forms, CRM, booking, WhatsApp, or checkout.', 'Analytics, ad pixels, and conversion tracking.', 'Chat, transactional email, and the brand domain.'],
        'implementation_requirements_es': ['Identidad visual, textos, oferta y llamado a la acción definidos.', 'Dominio o subdominio y destino de los datos del formulario.', 'Objetivo de conversión, fuentes de tráfico y medición acordados.'],
        'implementation_requirements_en': ['Defined brand identity, copy, offer, and call to action.', 'A domain or subdomain and a destination for form data.', 'Agreed conversion goal, traffic sources, and measurement.'],
    },
    {
        'category': 'marketing-acquisition',
        'slug': 'corporate-branding', 'icon': '🎨',
        'name_es': 'Identidad visual e imagen corporativa',
        'name_en': 'Corporate visual identity',
        'summary_es': 'Haz que pantallas, correos y documentos se reconozcan como una sola marca.',
        'summary_en': 'Make screens, emails, and documents feel like one recognizable brand.',
        'what_is_es': 'La aplicación consistente de logo, color, tipografía, tono y recursos visuales en el sistema y en cada pieza que éste genera o comparte.',
        'what_is_en': 'The consistent application of logo, color, typography, tone, and visual assets across the system and every item it generates or shares.',
        'purpose_es': 'Construir confianza y continuidad de marca desde el primer acceso hasta un correo, PDF, error o enlace compartido.',
        'purpose_en': 'Build trust and brand continuity from the first visit through emails, PDFs, errors, and shared links.',
        'problems_solved_es': ['Reemplaza pantallas y mensajes genéricos.', 'Evita que cada canal use estilos diferentes.', 'Mejora reconocimiento y percepción profesional.'],
        'problems_solved_en': ['Replaces generic screens and messages.', 'Prevents each channel from using a different visual language.', 'Improves recognition and professional perception.'],
        'integrations_es': ['Interfaz, login, estados vacíos y páginas de error.', 'Correos, PDFs, exportaciones y tarjetas de redes sociales.', 'Metadatos de buscadores y asistentes de IA.'],
        'integrations_en': ['Interface, login, empty states, and error pages.', 'Emails, PDFs, exports, and social preview cards.', 'Search-engine and AI-assistant metadata.'],
        'implementation_requirements_es': ['Logo en formatos útiles, paleta y tipografías licenciadas.', 'Guía de tono y ejemplos aprobados.', 'Responsable de marca para validar aplicaciones.'],
        'implementation_requirements_en': ['Logo in usable formats, palette, and licensed fonts.', 'Tone guide and approved examples.', 'A brand owner who can validate applications.'],
    },
    {
        'category': 'marketing-acquisition',
        'slug': 'conversion-tracking', 'icon': '📡',
        'name_es': 'Seguimiento de conversiones para Meta y Google Ads',
        'name_en': 'Conversion tracking for Meta and Google Ads',
        'summary_es': 'Devuelve a las campañas señales confiables sobre las acciones que sí producen negocio.',
        'summary_en': 'Send campaigns reliable signals about the actions that actually create business value.',
        'what_is_es': 'Una medición server-side que reporta eventos valiosos a Meta Conversions API y Google Enhanced Conversions, complementando el seguimiento del navegador.',
        'what_is_en': 'Server-side measurement that reports valuable events to Meta Conversions API and Google Enhanced Conversions, complementing browser tracking.',
        'purpose_es': 'Mejorar atribución y optimización publicitaria aun cuando cookies, bloqueadores o restricciones del dispositivo reducen la señal del navegador.',
        'purpose_en': 'Improve advertising attribution and optimization when cookies, blockers, or device restrictions reduce browser signals.',
        'problems_solved_es': ['Recupera conversiones que el píxel no observa.', 'Evita contar dos veces el mismo evento.', 'Relaciona cada evento con valor y resultado operativo.'],
        'problems_solved_en': ['Recovers conversions the browser pixel misses.', 'Prevents counting the same event twice.', 'Connects each event with business value and outcome.'],
        'integrations_es': ['Meta Conversions API y Google Ads.', 'Formularios, checkout, agenda, propuestas o eventos propios.', 'Panel de diagnóstico y analítica.'],
        'integrations_en': ['Meta Conversions API and Google Ads.', 'Forms, checkout, booking, proposals, or custom events.', 'Diagnostics dashboard and analytics.'],
        'implementation_requirements_es': ['Cuentas publicitarias y permisos técnicos.', 'Mapa de eventos, valores y consentimientos.', 'Política de privacidad y datos de matching permitidos.'],
        'implementation_requirements_en': ['Advertising accounts and technical permissions.', 'An event, value, and consent map.', 'Privacy policy and permitted matching data.'],
    },
    {
        'category': 'marketing-acquisition',
        'slug': 'email-marketing', 'icon': '✉️',
        'name_es': 'Email marketing y automatizaciones',
        'name_en': 'Email marketing and automations',
        'summary_es': 'Acompaña cada oportunidad con mensajes oportunos según su comportamiento y etapa.',
        'summary_en': 'Nurture each opportunity with timely messages based on behavior and stage.',
        'what_is_es': 'Un conjunto de listas, segmentos, campañas y secuencias automáticas conectado con los eventos reales de la plataforma.',
        'what_is_en': 'A set of lists, segments, campaigns, and automated sequences connected to real platform events.',
        'purpose_es': 'Mantener conversaciones relevantes a escala sin depender de envíos manuales ni tratar igual a todos los contactos.',
        'purpose_en': 'Maintain relevant conversations at scale without manual sending or treating every contact the same.',
        'problems_solved_es': ['Evita seguimientos olvidados o enviados fuera de contexto.', 'Segmenta por interés, etapa y actividad.', 'Mide entregas, aperturas, clics y bajas.'],
        'problems_solved_en': ['Prevents forgotten or out-of-context follow-ups.', 'Segments by interest, stage, and activity.', 'Measures delivery, opens, clicks, and unsubscribes.'],
        'integrations_es': ['Brevo, Mailchimp, SendGrid u otro proveedor.', 'CRM, formularios, compras y actividad del producto.', 'Plantillas, dominio de envío y analítica.'],
        'integrations_en': ['Brevo, Mailchimp, SendGrid, or another provider.', 'CRM, forms, purchases, and product activity.', 'Templates, sending domain, and analytics.'],
        'implementation_requirements_es': ['Base de contactos con consentimiento y origen trazable.', 'Dominio autenticado y proveedor configurado.', 'Segmentos, frecuencia, contenido y reglas de baja.'],
        'implementation_requirements_en': ['A contact base with consent and traceable source.', 'An authenticated domain and configured provider.', 'Segments, frequency, content, and unsubscribe rules.'],
    },
    {
        'category': 'marketing-acquisition',
        'slug': 'qr-generator', 'icon': '▦',
        'name_es': 'Generador y gestión de códigos QR',
        'name_en': 'QR code generation and management',
        'summary_es': 'Conecta piezas físicas con destinos digitales medibles y actualizables.',
        'summary_en': 'Connect physical materials to measurable, updateable digital destinations.',
        'what_is_es': 'Un módulo para crear, personalizar, organizar y seguir códigos QR estáticos o dinámicos desde el panel.',
        'what_is_en': 'A module for creating, customizing, organizing, and tracking static or dynamic QR codes from the admin panel.',
        'purpose_es': 'Llevar usuarios desde impresos, espacios o productos a una acción digital sin perder control del destino.',
        'purpose_en': 'Move users from print, places, or products into a digital action without losing destination control.',
        'problems_solved_es': ['Permite cambiar el destino sin reimprimir un QR dinámico.', 'Evita códigos dispersos sin dueño ni contexto.', 'Mide escaneos y campañas.'],
        'problems_solved_en': ['Changes a dynamic QR destination without reprinting.', 'Avoids scattered codes without ownership or context.', 'Measures scans and campaigns.'],
        'integrations_es': ['Landing pages, perfiles, formularios, documentos o pagos.', 'Analítica y parámetros de campaña.', 'Descarga PNG/SVG para piezas impresas.'],
        'integrations_en': ['Landing pages, profiles, forms, documents, or payments.', 'Analytics and campaign parameters.', 'PNG/SVG downloads for print materials.'],
        'implementation_requirements_es': ['Inventario de usos y destinos.', 'Reglas de marca, tamaño y contraste de impresión.', 'Dominio estable para enlaces dinámicos.'],
        'implementation_requirements_en': ['An inventory of uses and destinations.', 'Brand, size, and print-contrast rules.', 'A stable domain for dynamic links.'],
    },
    {
        'category': 'marketing-acquisition',
        'slug': 'content-generator', 'icon': '✍️',
        'name_es': 'Generación y calendario de contenido',
        'name_en': 'Content generation and editorial calendar',
        'summary_es': 'Planea, redacta y coordina publicaciones sin perder la voz de la marca.',
        'summary_en': 'Plan, draft, and coordinate publishing without losing the brand voice.',
        'what_is_es': 'Un espacio asistido para producir borradores, organizar ideas y gestionar un calendario editorial mensual o semanal con estados de aprobación.',
        'what_is_en': 'An assisted workspace for producing drafts, organizing ideas, and managing monthly or weekly editorial calendars with approval states.',
        'purpose_es': 'Convertir objetivos de comunicación en una cadencia visible de contenidos listos para revisar y publicar.',
        'purpose_en': 'Turn communication goals into a visible cadence of content ready for review and publishing.',
        'problems_solved_es': ['Reduce el tiempo de pasar de una idea al primer borrador.', 'Evita duplicar temas o perder fechas.', 'Mantiene tono, formato y llamados a la acción consistentes.'],
        'problems_solved_en': ['Reduces time from idea to first draft.', 'Prevents duplicate topics and missed dates.', 'Keeps tone, format, and calls to action consistent.'],
        'integrations_es': ['Blog, LinkedIn, email o redes mediante proveedor.', 'Banco de temas, productos y guía de marca.', 'Flujo de revisión, aprobación y programación.'],
        'integrations_en': ['Blog, LinkedIn, email, or social channels through a provider.', 'Topic bank, products, and brand guide.', 'Review, approval, and scheduling workflow.'],
        'implementation_requirements_es': ['Objetivos, audiencias y pilares de contenido.', 'Guía de tono y ejemplos permitidos/prohibidos.', 'Responsables de revisión y canales de publicación.'],
        'implementation_requirements_en': ['Content goals, audiences, and pillars.', 'Tone guide and allowed/forbidden examples.', 'Review owners and publishing channels.'],
    },
    {
        'category': 'user-experience',
        'slug': 'progressive-web-app', 'icon': '📱',
        'name_es': 'Aplicación móvil instalable (PWA)',
        'name_en': 'Installable mobile app (PWA)',
        'summary_es': 'Permite instalar la plataforma desde el navegador y conservar funciones útiles con conexión limitada.',
        'summary_en': 'Let users install the platform from the browser and keep useful functions with limited connectivity.',
        'what_is_es': 'Una evolución de la web con manifiesto, service worker, iconos y estrategias de caché para comportarse como una aplicación instalada.',
        'what_is_en': 'An evolution of the web using a manifest, service worker, icons, and caching strategies so it behaves like an installed application.',
        'purpose_es': 'Mejorar recurrencia, acceso rápido y resiliencia sin publicar aplicaciones separadas en cada tienda.',
        'purpose_en': 'Improve repeat use, quick access, and resilience without publishing separate applications in each store.',
        'problems_solved_es': ['Da acceso desde la pantalla de inicio.', 'Mantiene una experiencia clara cuando la red falla.', 'Actualiza la aplicación sin intervención del usuario.'],
        'problems_solved_en': ['Provides home-screen access.', 'Maintains a clear experience when the network fails.', 'Updates the application without user intervention.'],
        'integrations_es': ['Autenticación y rutas principales de la plataforma.', 'Caché, sincronización en segundo plano y notificaciones push.', 'Analítica de instalación y uso.'],
        'integrations_en': ['Authentication and core platform routes.', 'Cache, background sync, and push notifications.', 'Installation and usage analytics.'],
        'implementation_requirements_es': ['Definir qué funciona offline y qué no.', 'Iconos, nombre corto y colores de instalación.', 'Política de actualizaciones, permisos y notificaciones.'],
        'implementation_requirements_en': ['Define what works offline and what does not.', 'Installation icons, short name, and colors.', 'Update, permission, and notification policy.'],
    },
    {
        'category': 'user-experience',
        'slug': 'internationalization', 'icon': '🌐',
        'name_es': 'Plataforma multiidioma',
        'name_en': 'Multilingual platform',
        'summary_es': 'Entrega interfaz y contenido en el idioma adecuado para cada audiencia.',
        'summary_en': 'Deliver interface and content in the right language for each audience.',
        'what_is_es': 'Una arquitectura de internacionalización para traducir interfaz, contenido, correos, fechas, números y rutas sin duplicar la aplicación.',
        'what_is_en': 'An internationalization architecture for translating interface, content, emails, dates, numbers, and routes without duplicating the application.',
        'purpose_es': 'Atender mercados y equipos diversos con una experiencia coherente y preparada para sumar idiomas.',
        'purpose_en': 'Serve diverse markets and teams with a consistent experience prepared to add languages.',
        'problems_solved_es': ['Evita textos mezclados o traducciones incrustadas en código.', 'Presenta fechas, monedas y formatos locales correctamente.', 'Permite administrar traducciones del contenido.'],
        'problems_solved_en': ['Prevents mixed-language text and translations embedded in code.', 'Presents local dates, currencies, and formats correctly.', 'Supports managing content translations.'],
        'integrations_es': ['Navegación, contenido, formularios, PDFs y correo.', 'SEO con rutas y alternates por idioma.', 'Proveedor o flujo humano de traducción.'],
        'integrations_en': ['Navigation, content, forms, PDFs, and email.', 'SEO with localized routes and language alternates.', 'A provider or human translation workflow.'],
        'implementation_requirements_es': ['Idiomas, regiones y contenido traducible del alcance.', 'Responsable de traducción y aprobación.', 'Reglas para idioma por usuario, URL y fallback.'],
        'implementation_requirements_en': ['Target languages, regions, and translatable content.', 'Translation and approval owner.', 'Rules for language by user, URL, and fallback.'],
    },
    {
        'category': 'user-experience',
        'slug': 'live-chat', 'icon': '💬',
        'name_es': 'Chat en vivo y atención',
        'name_en': 'Live chat and support',
        'summary_es': 'Permite resolver dudas dentro de la experiencia sin obligar al usuario a cambiar de canal.',
        'summary_en': 'Resolve questions inside the experience without forcing users to switch channels.',
        'what_is_es': 'Un canal de conversación integrado con disponibilidad, historial, datos de contexto y escalamiento a una persona o equipo.',
        'what_is_en': 'An embedded conversation channel with availability, history, context data, and escalation to a person or team.',
        'purpose_es': 'Acompañar decisiones, soporte y ventas en el momento en que aparece una duda.',
        'purpose_en': 'Support decisions, service, and sales at the moment a question appears.',
        'problems_solved_es': ['Reduce abandono por preguntas sin respuesta.', 'Conserva contexto de página, usuario y conversación.', 'Ordena horarios, responsables y seguimiento.'],
        'problems_solved_en': ['Reduces abandonment caused by unanswered questions.', 'Preserves page, user, and conversation context.', 'Organizes schedules, owners, and follow-up.'],
        'integrations_es': ['Intercom, Crisp, Zendesk u otra solución.', 'CRM, usuarios, tickets y base de conocimiento.', 'Notificaciones por correo o mensajería.'],
        'integrations_en': ['Intercom, Crisp, Zendesk, or another solution.', 'CRM, users, tickets, and knowledge base.', 'Email or messaging notifications.'],
        'implementation_requirements_es': ['Herramienta o modelo de atención seleccionado.', 'Horarios, mensajes de ausencia y responsables.', 'Política de datos y tiempos de respuesta.'],
        'implementation_requirements_en': ['Selected support tool or operating model.', 'Schedules, away messages, and owners.', 'Data policy and response-time expectations.'],
    },
    {
        'category': 'user-experience',
        'slug': 'dark-mode', 'icon': '🌙',
        'name_es': 'Modo oscuro',
        'name_en': 'Dark mode',
        'summary_es': 'Ofrece una apariencia alternativa legible y consistente para ambientes de poca luz.',
        'summary_en': 'Offer a readable, consistent alternative appearance for low-light environments.',
        'what_is_es': 'Un tema completo que adapta superficies, texto, bordes, gráficos, imágenes y estados a una paleta oscura accesible.',
        'what_is_en': 'A complete theme that adapts surfaces, text, borders, charts, images, and states to an accessible dark palette.',
        'purpose_es': 'Dar control visual al usuario y mantener comodidad en sesiones largas o entornos oscuros.',
        'purpose_en': 'Give users visual control and maintain comfort during long sessions or in dark environments.',
        'problems_solved_es': ['Evita invertir colores de forma incompleta o ilegible.', 'Conserva contraste y jerarquía visual.', 'Recuerda la preferencia por usuario o dispositivo.'],
        'problems_solved_en': ['Avoids incomplete or unreadable color inversion.', 'Preserves contrast and visual hierarchy.', 'Remembers preference by user or device.'],
        'integrations_es': ['Sistema de diseño, gráficos, editor y contenido multimedia.', 'Preferencia del sistema operativo y perfil de usuario.', 'Correos o PDFs sólo cuando el formato lo admite.'],
        'integrations_en': ['Design system, charts, editor, and media content.', 'Operating-system and user-profile preference.', 'Emails or PDFs only when the format supports it.'],
        'implementation_requirements_es': ['Paleta oscura y contraste validados.', 'Inventario de componentes, gráficos e imágenes.', 'Regla de preferencia automática o manual.'],
        'implementation_requirements_en': ['Validated dark palette and contrast.', 'Inventory of components, charts, and images.', 'Automatic or manual preference rule.'],
    },
    {
        'category': 'intelligence-tracking',
        'slug': 'artificial-intelligence', 'icon': '🤖',
        'name_es': 'Integración y automatización con IA',
        'name_en': 'AI integration and automation',
        'summary_es': 'Aplica modelos de IA a una tarea concreta con datos, límites y revisión definidos.',
        'summary_en': 'Apply AI models to a concrete task with defined data, limits, and review.',
        'what_is_es': 'Una capacidad conectada a modelos de lenguaje, visión o clasificación para asistir, generar, extraer, buscar o ejecutar pasos dentro de un proceso real.',
        'what_is_en': 'A capability connected to language, vision, or classification models to assist, generate, extract, search, or execute steps within a real process.',
        'purpose_es': 'Reducir trabajo repetitivo o ampliar la capacidad de decisión sin presentar la IA como una función aislada del negocio.',
        'purpose_en': 'Reduce repetitive work or expand decision capacity without treating AI as a feature disconnected from the business.',
        'problems_solved_es': ['Acelera borradores, clasificación y extracción.', 'Permite consultar información con lenguaje natural.', 'Automatiza pasos con aprobación humana donde importa.'],
        'problems_solved_en': ['Speeds up drafting, classification, and extraction.', 'Enables natural-language access to information.', 'Automates steps with human approval where it matters.'],
        'integrations_es': ['Claude, OpenAI u otro proveedor adecuado al caso.', 'Datos, documentos, búsqueda y flujos internos.', 'Auditoría, límites de costo y revisión humana.'],
        'integrations_en': ['Claude, OpenAI, or another provider suited to the use case.', 'Data, documents, search, and internal workflows.', 'Audit, cost limits, and human review.'],
        'implementation_requirements_es': ['Un caso de uso y criterio de éxito concretos.', 'Fuentes de datos autorizadas y ejemplos de calidad.', 'Política de privacidad, revisión, errores y costos del proveedor.'],
        'implementation_requirements_en': ['A concrete use case and success criterion.', 'Authorized data sources and quality examples.', 'Privacy, review, error, and provider-cost policy.'],
    },
    {
        'category': 'intelligence-tracking',
        'slug': 'behavior-tracking', 'icon': '🧭',
        'name_es': 'Seguimiento de comportamiento y producto',
        'name_en': 'Behavior and product analytics',
        'summary_es': 'Entiende qué hacen los usuarios, dónde abandonan y qué caminos sí completan.',
        'summary_en': 'Understand what users do, where they leave, and which paths they complete.',
        'what_is_es': 'Una instrumentación de eventos, embudos y recorridos que observa interacciones relevantes sin depender únicamente de visitas de página.',
        'what_is_en': 'Event, funnel, and journey instrumentation that observes meaningful interactions instead of relying only on page views.',
        'purpose_es': 'Convertir el uso real del producto en evidencia para priorizar mejoras, onboarding y conversión.',
        'purpose_en': 'Turn real product usage into evidence for prioritizing improvements, onboarding, and conversion.',
        'problems_solved_es': ['Detecta pasos con abandono o fricción.', 'Compara adopción de funciones y cohortes.', 'Separa opiniones aisladas de patrones de uso.'],
        'problems_solved_en': ['Detects steps with abandonment or friction.', 'Compares feature adoption and cohorts.', 'Separates isolated opinions from usage patterns.'],
        'integrations_es': ['PostHog, Mixpanel, GA4 u otra plataforma.', 'Eventos del frontend y resultados del backend.', 'Dashboards, experimentos y alertas.'],
        'integrations_en': ['PostHog, Mixpanel, GA4, or another platform.', 'Frontend events and backend outcomes.', 'Dashboards, experiments, and alerts.'],
        'implementation_requirements_es': ['Mapa de eventos, propiedades y embudos.', 'Consentimiento, anonimización y retención.', 'Responsables de lectura y decisiones periódicas.'],
        'implementation_requirements_en': ['Event, property, and funnel map.', 'Consent, anonymization, and retention.', 'Owners for recurring review and decisions.'],
    },
    {
        'category': 'intelligence-tracking',
        'slug': 'reports-alerts', 'icon': '📊',
        'name_es': 'Reportes, indicadores y alertas',
        'name_en': 'Reports, metrics, and alerts',
        'summary_es': 'Convierte datos operativos en indicadores consultables y señales que llegan a tiempo.',
        'summary_en': 'Turn operational data into accessible metrics and signals that arrive on time.',
        'what_is_es': 'Un módulo de tableros, reportes exportables y alertas basadas en condiciones del negocio, con alcance por rol y período.',
        'what_is_en': 'A module for dashboards, exportable reports, and business-rule alerts scoped by role and period.',
        'purpose_es': 'Ayudar a cada responsable a observar resultados, excepciones y tendencias sin revisar registros uno por uno.',
        'purpose_en': 'Help each owner monitor results, exceptions, and trends without reviewing records one by one.',
        'problems_solved_es': ['Reduce consolidación manual en hojas de cálculo.', 'Avisa vencimientos, caídas o umbrales antes de que escalen.', 'Entrega una definición compartida de cada indicador.'],
        'problems_solved_en': ['Reduces manual spreadsheet consolidation.', 'Signals deadlines, drops, or thresholds before they escalate.', 'Provides a shared definition for each metric.'],
        'integrations_es': ['Base transaccional y eventos de la plataforma.', 'Correo, mensajería o notificaciones internas.', 'PDF, Excel/CSV y herramientas BI cuando aplica.'],
        'integrations_en': ['Transactional database and platform events.', 'Email, messaging, or internal notifications.', 'PDF, Excel/CSV, and BI tools when appropriate.'],
        'implementation_requirements_es': ['Indicadores, fórmulas, fuentes y responsables definidos.', 'Frecuencia, destinatarios y umbrales de alerta.', 'Permisos y política de exportación de datos.'],
        'implementation_requirements_en': ['Defined metrics, formulas, sources, and owners.', 'Alert frequency, recipients, and thresholds.', 'Permissions and data-export policy.'],
    },
]


def seed_catalog(apps, schema_editor):
    Category = apps.get_model('content', 'AdditionalModuleCategory')
    Module = apps.get_model('content', 'AdditionalModule')

    categories = {}
    for order, (slug, name_es, name_en) in enumerate(CATEGORIES):
        category, _ = Category.objects.update_or_create(
            slug=slug,
            defaults={
                'name_es': name_es,
                'name_en': name_en,
                'order': order,
                'is_active': True,
            },
        )
        categories[slug] = category

    category_orders = {slug: 0 for slug, _name_es, _name_en in CATEGORIES}
    for data in MODULES:
        category_slug = data['category']
        defaults = {key: value for key, value in data.items() if key != 'category'}
        defaults.update({
            'category': categories[category_slug],
            'order': category_orders[category_slug],
            'is_active': True,
        })
        Module.objects.update_or_create(slug=data['slug'], defaults=defaults)
        category_orders[category_slug] += 1


def unseed_catalog(apps, schema_editor):
    Category = apps.get_model('content', 'AdditionalModuleCategory')
    Module = apps.get_model('content', 'AdditionalModule')
    Module.objects.filter(slug__in=[row['slug'] for row in MODULES]).delete()
    Category.objects.filter(slug__in=[row[0] for row in CATEGORIES]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0223_additional_module_catalog'),
    ]

    operations = [
        migrations.RunPython(seed_catalog, unseed_catalog),
    ]
