# Generated by Django 6.1 on 2026-08-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0223_generated_document_filing'),
        ('content', '0224_seed_additional_module_catalog'),
    ]

    operations = []
