# Generated by Django 6.1 on 2026-08-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0224_merge_generated_filing_project_folders'),
        ('content', '0225_merge_additional_modules_generated_filing'),
    ]

    operations = []
