# Generated by Django 6.1 on 2026-08-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0226_merge_additional_modules_project_folders'),
        ('content', '0226_merge_email_history_generated_filing'),
    ]

    operations = []
