# Generated by Django 6.1 on 2026-08-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0229_expand_additional_module_catalog'),
        ('content', '0229_remove_paused_project_state'),
    ]

    operations = []
