# Generated by Django 6.1 on 2026-08-31 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_remove_project_document_manager_enabled'),
        ('content', '0230_merge_additional_modules_paused_project_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentfolder',
            name='managed_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_document_root_folder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.CheckConstraint(condition=models.Q(('managed_client__isnull', True), ('parent__isnull', True), _connector='OR'), name='managed_client_folder_is_root'),
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.CheckConstraint(condition=models.Q(('managed_client__isnull', True), ('client_user', models.F('managed_client')), _connector='OR'), name='managed_folder_matches_client'),
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.CheckConstraint(condition=models.Q(('managed_client__isnull', True), ('is_archived', False), _connector='OR'), name='managed_client_folder_is_active'),
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.CheckConstraint(condition=models.Q(('managed_client__isnull', True), ('managed_project__isnull', True), _connector='OR'), name='managed_root_is_project_or_client'),
        ),
    ]
