# Generated by Django 6.1 on 2026-08-31 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


OLD_DESCRIPTION = (
    'Lista y abre hilos por cliente o proyecto, crea hilos, registra mensajes '
    'de correo o WhatsApp, referencia documentos y marca envíos externos.'
)
NEW_DESCRIPTION = (
    'Lista y abre hilos por cliente o proyecto, crea hilos, registra y edita '
    'borradores de correo o WhatsApp, referencia documentos y marca envíos externos.'
)


def update_communications_description(apps, schema_editor):
    McpConnector = apps.get_model('content', 'McpConnector')
    McpConnector.objects.filter(slug='communications').update(
        description=NEW_DESCRIPTION,
    )


def restore_communications_description(apps, schema_editor):
    McpConnector = apps.get_model('content', 'McpConnector')
    McpConnector.objects.filter(slug='communications').update(
        description=OLD_DESCRIPTION,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0230_merge_additional_modules_paused_project_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationMessageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(default=list)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_message_revisions', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content.communicationmessage')),
            ],
            options={
                'ordering': ['-edited_at', '-id'],
                'indexes': [models.Index(fields=['message', 'edited_at'], name='commrevision_message_at')],
            },
        ),
        migrations.RunPython(
            update_communications_description,
            restore_communications_description,
        ),
    ]
