# Generated by Django 6.1 on 2026-08-31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0231_communication_message_revisions'),
        ('content', '0231_document_folder_managed_client'),
    ]

    operations = []
