# Generated by Django 6.1 on 2026-08-31 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_remove_project_document_manager_enabled'),
        ('content', '0231_document_folder_managed_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationthread',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationthread',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='communicationthread',
            name='managed_client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_communication_root_thread', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='communicationthread',
            name='managed_project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_root_thread', to='accounts.project'),
        ),
        migrations.AddConstraint(
            model_name='communicationthread',
            constraint=models.CheckConstraint(condition=models.Q(('managed_project__isnull', True), ('project', models.F('managed_project')), _connector='OR'), name='managed_thread_matches_project'),
        ),
        migrations.AddConstraint(
            model_name='communicationthread',
            constraint=models.CheckConstraint(condition=models.Q(('managed_client__isnull', True), ('client', models.F('managed_client')), _connector='OR'), name='managed_thread_matches_client'),
        ),
        migrations.AddConstraint(
            model_name='communicationthread',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('managed_project__isnull', True), ('managed_client__isnull', True)), ('is_archived', False), _connector='OR'), name='managed_thread_is_active'),
        ),
        migrations.AddConstraint(
            model_name='communicationthread',
            constraint=models.CheckConstraint(condition=models.Q(('managed_client__isnull', True), ('managed_project__isnull', True), _connector='OR'), name='managed_thread_is_project_or_client'),
        ),
    ]
