"""Drop the legacy proposal-requirement tables.

``ProposalRequirementGroup`` / ``ProposalRequirementItem`` hold 0 and 0 rows in
production, have no writer that a user can reach (only the Django admin could),
and the frontend already labelled them the "legacy" fallback behind
``BusinessProposal.content_json``, which is the live source.

``Document.deliverable`` was dropped here too and put back: it has 0 rows, but
it is NOT dead — ``accounts/collection_account_views.py`` writes it on create
and filters by it on list, and ``deliverable_id`` is a public field of the
collection-account serializer. Zero rows meant unused, not unwired.

Nothing to migrate, therefore: this is a pure drop.
"""
# Generated by Django 6.1 on 2026-08-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0233_client_audit_entity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalrequirementitem',
            name='group',
        ),
        migrations.DeleteModel(
            name='ProposalRequirementGroup',
        ),
        migrations.DeleteModel(
            name='ProposalRequirementItem',
        ),
    ]
