"""Drop three relations that were dead in code and empty in production.

Verified against production (MySQL ``projectapp_db``) before writing this:

- ``Document.deliverable``: 0 of 136 documents carried one. Never assigned
  anywhere, absent from every Document serializer, already excluded from the
  MCP contract. The feature its help_text described was never wired.
- ``ProposalRequirementGroup`` / ``ProposalRequirementItem``: 0 and 0 rows. No
  production writer ever created one — only tests and the Django admin could —
  and the frontend already labelled them the "legacy" fallback behind
  ``BusinessProposal.content_json``, which is the live source.

Nothing to migrate, therefore: this is a pure drop.
"""
# Generated by Django 6.1 on 2026-08-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0233_client_audit_entity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalrequirementitem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='document',
            name='deliverable',
        ),
        migrations.DeleteModel(
            name='ProposalRequirementGroup',
        ),
        migrations.DeleteModel(
            name='ProposalRequirementItem',
        ),
    ]
