# Generated by Django 6.1 on 2026-08-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0232_merge_communication_revision_managed_client'),
        ('content', '0234_drop_dead_proposal_requirements'),
    ]

    operations = [
    ]
