# Generated by Django 6.1 on 2026-09-02 12:26

import django.utils.timezone
from django.db import migrations, models


def mark_legacy_tracking_state(apps, schema_editor):
    from django.db.models import F

    BusinessProposal = apps.get_model('content', 'BusinessProposal')
    ProposalViewEvent = apps.get_model('content', 'ProposalViewEvent')
    BusinessProposal.objects.filter(first_viewed_at__isnull=False).update(
        first_view_notification_status='legacy_unverified',
    )
    ProposalViewEvent.objects.update(last_seen_at=F('viewed_at'))


def reset_legacy_tracking_state(apps, schema_editor):
    BusinessProposal = apps.get_model('content', 'BusinessProposal')
    BusinessProposal.objects.filter(
        first_view_notification_status='legacy_unverified',
    ).update(first_view_notification_status='not_started')


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0236_document_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessproposal',
            name='first_view_notification_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='first_view_notification_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='first_view_notification_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='first_view_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='first_view_notification_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('legacy_unverified', 'Legacy unverified')], default='not_started', help_text='Durable delivery state for the internal first-view email.', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalviewevent',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='When the browser finalized the session on hide or unload.', null=True),
        ),
        migrations.AddField(
            model_name='proposalviewevent',
            name='last_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Latest accepted heartbeat for this browser session.'),
        ),
        migrations.RunPython(
            mark_legacy_tracking_state,
            reset_legacy_tracking_state,
        ),
        migrations.AlterField(
            model_name='proposalalert',
            name='alert_type',
            field=models.CharField(choices=[('reminder', 'Recordatorio'), ('followup', 'Seguimiento'), ('call', 'Llamada'), ('meeting', 'Reunión'), ('custom', 'Personalizado'), ('discount_suggestion', 'Sugerencia de descuento'), ('post_expiration_visit', 'Visita post-expiración'), ('high_engagement_today', 'Alta actividad hoy'), ('whatsapp_suggestion', 'Sugerencia de WhatsApp'), ('calculator_followup', 'Seguimiento calculadora'), ('engagement_decay', 'Pérdida de engagement'), ('post_rejection_revisit', 'Revisita post-rechazo'), ('first_view', 'Primera vista confirmada')], default='reminder', max_length=30),
        ),
    ]
