# Generated by Django 6.1 on 2026-09-02 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_client_archived_state'),
        ('content', '0239_expand_communications_mcp_parity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentstateepisode',
            name='state_episode_exactly_one_subject',
        ),
        migrations.AddConstraint(
            model_name='documentstateepisode',
            constraint=models.CheckConstraint(condition=models.Q(('document__isnull', True), ('project__isnull', True), _connector='OR'), name='state_episode_subject_is_document_or_project'),
        ),
    ]
