# Generated by Django 6.1 on 2026-09-02 22:37

import content.models.financing_agreement
import content.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_client_archived_state'),
        ('content', '0239_expand_communications_mcp_parity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingAgreementNumberSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financing agreement number sequence',
            },
        ),
        migrations.CreateModel(
            name='FinancingAgreementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('content_markdown', models.TextField()),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', '-version', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uniq_financing_template_name_version')],
            },
        ),
        migrations.CreateModel(
            name='FinancingAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.CharField(blank=True, help_text='Assigned atomically when the draft is marked ready.', max_length=20, null=True, unique=True)),
                ('client_full_name', models.CharField(max_length=311)),
                ('client_company', models.CharField(blank=True, default='', max_length=200)),
                ('client_id_type', models.CharField(blank=True, default='', max_length=20)),
                ('client_id_number', models.CharField(blank=True, default='', max_length=32)),
                ('client_email', models.EmailField(blank=True, default='', max_length=254)),
                ('client_phone', models.CharField(blank=True, default='', max_length=30)),
                ('original_contract_reference', models.CharField(max_length=255)),
                ('original_contract_date', models.DateField()),
                ('project_name', models.CharField(max_length=255)),
                ('financed_scope', models.TextField()),
                ('modality', models.CharField(choices=[('five_year', 'Alianza a 5 años'), ('three_year', 'Alianza a 3 años')], max_length=20)),
                ('cycle_number', models.PositiveSmallIntegerField(default=1)),
                ('partnership_start_date', models.DateField()),
                ('partnership_end_date', models.DateField()),
                ('currency', models.CharField(choices=[('COP', 'COP'), ('USD', 'USD')], default='COP', max_length=3)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('initial_payment', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('financed_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('hosting_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('hosting_period', models.CharField(choices=[('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20)),
                ('installment_schedule', models.JSONField(blank=True, default=list)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('contract_markdown', models.TextField()),
                ('resolved_contract_markdown', models.TextField(blank=True, default='')),
                ('resolved_contract_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('signed_document', models.FileField(blank=True, max_length=500, null=True, storage=content.storage.get_private_storage, upload_to=content.models.financing_agreement.financing_signed_document_path)),
                ('signed_document_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('signed_document_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Listo para firma'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_index=True, default='draft', max_length=20)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_note', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('second_cycle_approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_agreements_activated', to=settings.AUTH_USER_MODEL)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_agreements_archived', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_agreements_cancelled', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='financing_agreements', to='accounts.userprofile')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_agreements_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_agreements_created', to=settings.AUTH_USER_MODEL)),
                ('previous_agreement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_cycle', to='content.financingagreement')),
                ('ready_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_agreements_prepared', to=settings.AUTH_USER_MODEL)),
                ('second_cycle_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_second_cycles_approved', to=settings.AUTH_USER_MODEL)),
                ('source_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_agreements', to='accounts.project')),
                ('source_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_agreements', to='content.businessproposal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_agreements_updated', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='content.financingagreementtemplate')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancingAgreementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_agreement_events', to=settings.AUTH_USER_MODEL)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='content.financingagreement')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['agreement', '-created_at'], name='content_fin_agreeme_02df4c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='financingagreement',
            index=models.Index(fields=['is_archived', 'status', '-created_at'], name='content_fin_is_arch_e7ff3f_idx'),
        ),
        migrations.AddIndex(
            model_name='financingagreement',
            index=models.Index(fields=['client', '-created_at'], name='content_fin_client__adc2b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='financingagreement',
            constraint=models.CheckConstraint(condition=models.Q(('cycle_number__in', (1, 2))), name='financing_cycle_one_or_two'),
        ),
        migrations.AddConstraint(
            model_name='financingagreement',
            constraint=models.CheckConstraint(condition=models.Q(('initial_payment__lte', models.F('total_value'))), name='financing_initial_not_above_total'),
        ),
        migrations.AddConstraint(
            model_name='financingagreement',
            constraint=models.CheckConstraint(condition=models.Q(('cycle_number', 1), ('modality', 'five_year'), _connector='OR'), name='financing_second_cycle_five_year_only'),
        ),
    ]
