# Generated by Django 6.1 on 2026-09-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0240_mcp_operational_platform'),
        ('content', '0240_state_episode_subject_exclusivity'),
    ]

    operations = [
    ]
