# Generated by Django 6.1 on 2026-09-02 22:42

from django.db import migrations


TEMPLATE_NAME = 'Otrosí de financiación'
TEMPLATE_VERSION = 1
TEMPLATE_MARKDOWN = """# OTROSÍ DE FINANCIACIÓN {agreement_number}

Entre los suscritos, **{client_full_name}**, identificado(a) con {client_id_type} No. {client_id_number}, en adelante **EL CONTRATANTE**, y **{contractor_full_name}**, identificado(a) con {contractor_id_type} No. {contractor_id_number}, en adelante **EL CONTRATISTA**, se celebra el presente otrosí al contrato **{original_contract_reference}**, suscrito el {original_contract_date}.

## PRIMERA. OBJETO

Las partes incorporan un mecanismo de financiación para el desarrollo e implementación de **{project_name}**, limitado al siguiente alcance aprobado:

> {financed_scope}

Este otrosí complementa el contrato original. Las cláusulas no modificadas conservan plena vigencia.

## SEGUNDA. VALOR Y SALDO FINANCIADO

El valor del ciclo es **{total_value}**. EL CONTRATANTE realiza un aporte inicial de **{initial_payment}** y el saldo financiado corresponde a **{financed_balance}**, a doce (12) meses y con interés ordinario del cero por ciento (0 %).

## TERCERA. CALENDARIO DE PAGOS

Cada cuota se paga dentro de los primeros cinco (5) días calendario del mes correspondiente, conforme al siguiente calendario:

{installment_schedule}

El pago de una cuota no extingue las cuotas anteriores que continúen pendientes.

## CUARTA. MORA Y AUMENTO DEL HOSTING

Por cada cuota que no sea pagada dentro de los primeros cinco (5) días calendario del mes correspondiente, el costo vigente del Hosting —actualmente **{hosting_value}** con periodicidad {hosting_period}— aumentará en un uno por ciento (1 %). Cada aumento es acumulativo, permanente y opera automáticamente desde el vencimiento, sin necesidad de requerimiento previo. Esta consecuencia no sustituye la obligación de pagar la cuota vencida ni las demás consecuencias legalmente procedentes que se pacten y resulten aplicables.

Las partes reconocen que esta condición distribuye el riesgo de impago asumido por EL CONTRATISTA al entregar y operar el producto antes de recuperar la totalidad del saldo financiado.

## QUINTA. MODALIDAD, EXCLUSIVIDAD Y CONTINUIDAD

La modalidad elegida es **{modality_label}**, vigente desde el {partnership_start_date} hasta el {partnership_end_date}.

{modality_terms}

Durante este periodo EL CONTRATISTA será la casa desarrolladora exclusiva del producto financiado para su desarrollo, mantenimiento, soporte, infraestructura, actualizaciones y continuidad técnica. La exclusividad se limita a este producto y no restringe iniciativas independientes de EL CONTRATANTE.

## SEXTA. CUSTODIA DEL CÓDIGO

EL CONTRATISTA conservará la custodia operativa de repositorios, versiones, respaldos, accesos e integridad del código durante la vigencia acordada. La custodia no transfiere a EL CONTRATISTA la propiedad intelectual ni autoriza una explotación distinta de la necesaria para ejecutar el contrato. La entrega material de repositorios se realizará al terminar la custodia y estar cumplidas las obligaciones pactadas, mediante acta.

## SÉPTIMA. CALCULADORA DE REQUERIMIENTOS

EL CONTRATANTE podrá describir en lenguaje natural una necesidad, su objetivo y el contexto esencial del producto. La calculadora devolverá una referencia de esfuerzo, trabajo, tiempo y rango de precio. El resultado es orientativo: sólo una cotización formal aprobada por ambas partes fija alcance, cronograma y precio definitivo.

## OCTAVA. PREVALENCIA Y REVISIÓN

En caso de contradicción, este otrosí prevalece únicamente sobre las materias que modifica expresamente. Los datos, valores y fechas aquí incorporados forman parte integral del acuerdo. El documento debe ser revisado por las partes y por su asesoría jurídica antes de firma.

Firmado en {contract_city}, el {contract_date}.

| EL CONTRATANTE | EL CONTRATISTA |
| --- | --- |
| {client_full_name} | {contractor_full_name} |
| {client_id_type} {client_id_number} | {contractor_id_type} {contractor_id_number} |
| {client_email} | {contractor_email} |
"""


def seed_template(apps, schema_editor):
    Template = apps.get_model('content', 'FinancingAgreementTemplate')
    Template.objects.filter(is_default=True).update(is_default=False)
    Template.objects.update_or_create(
        name=TEMPLATE_NAME,
        version=TEMPLATE_VERSION,
        defaults={
            'content_markdown': TEMPLATE_MARKDOWN,
            'is_default': True,
            'is_active': True,
        },
    )


def remove_template(apps, schema_editor):
    Template = apps.get_model('content', 'FinancingAgreementTemplate')
    Template.objects.filter(
        name=TEMPLATE_NAME,
        version=TEMPLATE_VERSION,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0240_financing_agreements'),
    ]

    operations = [
        migrations.RunPython(seed_template, remove_template),
    ]
