# Generated by Django 6.1 on 2026-09-03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0240_state_episode_subject_exclusivity'),
        ('content', '0241_seed_financing_template'),
    ]

    operations = []
