# Generated by Django 6.1 on 2026-09-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0247_seed_audiovisual_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplainerVideoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_additional_modules_video', models.BooleanField(default=True)),
                ('show_financing_video', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Explainer video settings',
                'verbose_name_plural': 'Explainer video settings',
            },
        ),
        migrations.AddField(
            model_name='additionalmodulesharelink',
            name='show_explainer_video',
            field=models.BooleanField(default=True),
        ),
    ]
