# Generated by Django 6.1 on 2026-09-19 13:14

import content.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0248_explainer_video_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalFormalization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict)),
                ('source_hash', models.CharField(max_length=64)),
                ('html_body', models.TextField()),
                ('text_body', models.TextField()),
                ('status', models.CharField(choices=[('prepared', 'Preparado'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('unknown', 'Entrega incierta')], default='prepared', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formalizations', to='content.businessproposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalFormalizationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('mime_type', models.CharField(max_length=100)),
                ('file', models.FileField(max_length=500, storage=content.storage.get_private_storage, upload_to='formalizations/%Y/%m/')),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('preparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.proposalformalization')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('preparation', 'key'), name='unique_formalization_file_key')],
            },
        ),
    ]
