# Generated by Django 5.2.13 on 2026-09-21 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0249_proposalformalization_proposalformalizationfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktree',
            name='accent_color',
            field=models.CharField(default='#f0ff3d', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Usa un color hexadecimal de 6 dígitos.')]),
        ),
        migrations.AddField(
            model_name='linktree',
            name='background_color',
            field=models.CharField(default='#001713', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Usa un color hexadecimal de 6 dígitos.')]),
        ),
        migrations.AddField(
            model_name='linktree',
            name='button_text_color',
            field=models.CharField(default='#001713', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Usa un color hexadecimal de 6 dígitos.')]),
        ),
        migrations.AddField(
            model_name='linktree',
            name='font_family',
            field=models.CharField(default='Ubuntu', max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9 -]{0,99}$', 'Usa el nombre de una familia de Google Fonts.')]),
        ),
        migrations.AddField(
            model_name='linktree',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='linktrees/logos/'),
        ),
        migrations.AddField(
            model_name='linktree',
            name='muted_color',
            field=models.CharField(default='#809490', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Usa un color hexadecimal de 6 dígitos.')]),
        ),
        migrations.AddField(
            model_name='linktree',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Usa un color hexadecimal de 6 dígitos.')]),
        ),
    ]
