# Generated by Django 5.2.13 on 2026-09-22 12:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0249_proposalformalization_proposalformalizationfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=32)),
                ('object_id', models.PositiveBigIntegerField()),
                ('object_label', models.CharField(max_length=255)),
                ('revision', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'object_id'), name='unique_entity_history')],
            },
        ),
        migrations.CreateModel(
            name='EntityRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('operation_id', models.UUIDField(default=uuid.uuid4)),
                ('action', models.CharField(max_length=32)),
                ('actor_id_snapshot', models.PositiveBigIntegerField(null=True)),
                ('actor_label', models.CharField(default='Sistema', max_length=255)),
                ('source', models.CharField(default='system', max_length=255)),
                ('source_key', models.CharField(max_length=160, null=True, unique=True)),
                ('snapshot', models.JSONField(null=True)),
                ('secrets', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=list)),
                ('evidence', models.JSONField(default=list)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='content.entityhistory')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'indexes': [models.Index(fields=['history', '-occurred_at', '-id'], name='entity_revision_chronology')],
                'constraints': [models.UniqueConstraint(fields=('history', 'number'), name='unique_entity_revision')],
            },
        ),
    ]
