# Generated by Django 5.2.13 on 2026-09-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0250_entityhistory_entityrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityrevision',
            name='changed_fields',
            field=models.JSONField(default=list),
        ),
    ]
