# Generated by Django 5.2.13 on 2026-09-21 22:51

import content.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_projectaccessnote_projectadminaccess'),
        ('content', '0250_linktree_accent_color_linktree_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linktree',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linktrees', to='accounts.project'),
        ),
        migrations.CreateModel(
            name='ProjectBrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('branding', 'Branding'), ('manual', 'Manual de marca'), ('design_system', 'Sistema de diseño'), ('logo', 'Logo'), ('other', 'Otro recurso')], max_length=20)),
                ('file', models.FileField(max_length=500, storage=content.storage.get_private_storage, upload_to='project-brand/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_assets', to='accounts.project')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
