# Generated by Django 5.2.13 on 2026-09-23 02:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0252_merge_history_and_branding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinktreeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('manifest', models.JSONField(default=dict)),
                ('html', models.TextField()),
                ('css', models.TextField(blank=True)),
                ('assets', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_templates', to='content.linktree')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinktreeTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assets', models.JSONField(default=dict)),
                ('overrides', models.JSONField(default=list)),
                ('profile', models.JSONField(default=dict)),
                ('profile_digest', models.CharField(max_length=64)),
                ('document', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Validando'), ('valid', 'Lista para publicar'), ('invalid', 'Requiere correcciones')], default='pending', max_length=10)),
                ('report', models.JSONField(default=dict)),
                ('screenshots', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('linktree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_versions', to='content.linktree')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='content.linktreetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='linktree',
            name='active_template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.linktreetemplateversion'),
        ),
        migrations.CreateModel(
            name='LinktreeTemplateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_key', models.CharField(max_length=40)),
                ('day', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='content.linktreetemplateversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('version', 'link_key', 'day'), name='unique_linktree_template_click_day')],
            },
        ),
    ]
