# Generated by Django 5.2.13 on 2026-09-23 20:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0253_linktree_html_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinktreeAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_-]{0,39}$', 'Usa una clave en minúsculas con números, guion o guion bajo (hasta 40 caracteres).')])),
                ('alt', models.CharField(blank=True, default='', max_length=500)),
                ('image', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linktree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='content.linktree')),
            ],
            options={
                'verbose_name': 'Linktree Asset',
                'verbose_name_plural': 'Linktree Assets',
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('linktree', 'key'), name='unique_linktree_asset_key')],
            },
        ),
    ]
