// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/13/2026, 5:36:48 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/cerrotico/work/projectapp_clean/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/cerrotico/work/projectapp_clean/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/cerrotico/work/projectapp_clean/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/cerrotico/work/projectapp_clean/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/cerrotico/work/projectapp_clean/frontend/plugins/**/*.{js,ts,mjs}","/home/cerrotico/work/projectapp_clean/frontend/composables/**/*.{js,ts,mjs}","/home/cerrotico/work/projectapp_clean/frontend/utils/**/*.{js,ts,mjs}","/home/cerrotico/work/projectapp_clean/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/cerrotico/work/projectapp_clean/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/cerrotico/work/projectapp_clean/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/cerrotico/work/projectapp_clean/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;