"""Explicit ORM write boundary for aggregates with durable revision history.

Custom QuerySets cover bulk updates (which Django signals do not observe).
No global monkey-patching or interception of unrelated models is involved.
"""

from copy import copy

from django.db import connections, models


class HistoryQuerySet(models.QuerySet):
    def update(self, **kwargs):
        from content.services.entity_history import capture_instance, history_operation
        from content.services.entity_history_registry import tracks_fields
        if not tracks_fields(self.model, kwargs):
            return super().update(**kwargs)
        with history_operation():
            rows = list(self.select_for_update().order_by('pk'))
            for row in rows:
                capture_instance(row)
            # Snapshot a child's destination aggregate before reassignment,
            # including CASE expressions generated by Django bulk_update.
            parents = [field for field in self.model._meta.concrete_fields
                       if isinstance(field, models.ForeignKey)
                       and (field.name in kwargs or field.attname in kwargs)]
            projected = {row.pk: copy(row) for row in rows}
            for field in parents:
                value = kwargs.get(field.attname, kwargs.get(field.name))
                if hasattr(value, 'resolve_expression'):
                    values = dict(self.annotate(_history_target=value)
                                  .values_list('pk', '_history_target'))
                else:
                    values = dict.fromkeys(projected, getattr(value, 'pk', value))
                for pk, row in projected.items():
                    setattr(row, field.attname, values[pk])
            for row in projected.values():
                capture_instance(row)
            result = super().update(**kwargs)
            for row in self.model.objects.filter(pk__in=[row.pk for row in rows]):
                capture_instance(row)
            return result

    def delete(self):
        from content.services.entity_history import capture_instance, history_operation
        with history_operation():
            for row in self.select_for_update().order_by('pk'):
                capture_instance(row)
            return super().delete()

    def bulk_create(self, objs, batch_size=None, **kwargs):
        from content.services.entity_history import capture_instance, history_operation
        objs = list(objs)
        with history_operation():
            # Upserts must snapshot existing rows before changing them.
            if kwargs.get('update_conflicts') or kwargs.get('ignore_conflicts'):
                raise ValueError('Use update_or_create for history-tracked upserts.')
            for obj in objs:
                capture_instance(obj)
            result = super().bulk_create(objs, batch_size=batch_size, **kwargs)
            for obj in result:
                if obj.pk is None:
                    raise ValueError('Bulk history requires returned primary keys; use create on this database.')
                capture_instance(obj, created=True)
            return result

    def _batched_insert(self, objs, fields, batch_size, **kwargs):
        if connections[self.db].features.can_return_rows_from_bulk_insert:
            return super()._batched_insert(objs, fields, batch_size, **kwargs)
        # MySQL cannot return generated PKs for a multi-row INSERT. Use the
        # same ORM compiler one row at a time, preserving bulk_create's lack
        # of save signals while obtaining each identity for its revision.
        return [row for obj in objs for row in self._insert(
            [obj], fields=fields, returning_fields=self.model._meta.db_returning_fields,
            using=self.db,
        )]

    def bulk_update(self, objs, fields, batch_size=None):
        from content.services.entity_history import history_operation
        with history_operation():
            return super().bulk_update(objs, fields, batch_size=batch_size)


class HistoryTrackedModel(models.Model):
    objects = HistoryQuerySet.as_manager()

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        from content.services.entity_history import capture_instance, history_operation
        from content.services.entity_history_registry import tracks_fields
        if not self._state.adding and not tracks_fields(type(self), kwargs.get('update_fields')):
            return super().save(*args, **kwargs)
        with history_operation():
            creating = self._state.adding
            if not creating:
                # Capture the old parent too when a child is reassigned.
                previous = type(self).objects.filter(pk=self.pk).first()
                if previous:
                    capture_instance(previous)
            capture_instance(self)
            result = super().save(*args, **kwargs)
            capture_instance(self, created=creating)
            return result

    def delete(self, *args, **kwargs):
        from content.services.entity_history import capture_instance, history_operation
        with history_operation():
            capture_instance(self)
            return super().delete(*args, **kwargs)
