# Generated by Django 6.1 on 2026-09-19 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0063_projectaccessnote_projectadminaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=200)),
                ('fingerprint_hash', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=240)),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('critical', 'Crítico')], max_length=10)),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('reviewing', 'En revisión'), ('resolved', 'Resuelto')], default='pending', max_length=10)),
                ('condition', models.CharField(default='active', max_length=12)),
                ('resource_snapshot', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=dict)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('detections', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-last_seen_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('kind', models.CharField(max_length=16)),
                ('text', models.TextField(blank=True)),
                ('from_state', models.CharField(blank=True, max_length=10)),
                ('to_state', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='monitoring.case')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('server', 'Servidor'), ('project', 'Proyecto')], max_length=10)),
                ('environment', models.CharField(default='production', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.project')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='monitoring.resource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resources', models.ManyToManyField(to='monitoring.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('expected_interval', models.PositiveIntegerField(default=300)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='monitoring.resource')),
            ],
            options={
                'ordering': ['resource__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('text', models.TextField()),
                ('resource_snapshot', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='monitoring.source')),
            ],
            options={
                'ordering': ['-observed_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('digest', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=12)),
                ('observed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('evidence', models.JSONField(default=dict)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='monitoring.case')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='monitoring.report')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monitoring.source')),
            ],
            options={
                'ordering': ['-observed_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='monitoring.source'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('resource', 'key'), name='monitor_source_resource_key'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='monitor_delivery_identity'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['state', '-last_seen_at'], name='monitoring__state_882de4_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['severity', '-last_seen_at'], name='monitoring__severit_21fa9a_idx'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('source', 'fingerprint_hash'), name='monitor_case_fingerprint'),
        ),
    ]
