# Generated by Django 6.1 on 2026-09-19 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['-last_seen_at', '-id'], name='monitoring__last_se_4418a8_idx'),
        ),
        migrations.AddIndex(
            model_name='caseactivity',
            index=models.Index(fields=['case', '-created_at'], name='monitoring__case_id_8229c4_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['case', '-observed_at'], name='monitoring__case_id_3a14d6_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['kind', 'received_at'], name='monitoring__kind_ffbad9_idx'),
        ),
    ]
