"""Canonical filing rules for documents generated by ProjectApp.

The hierarchy is server-owned and keyed independently from human-readable
folder names.  That makes creation idempotent, lets names follow a renamed
project/client, and prevents concurrent generations from creating duplicate
branches.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date

from django.db import transaction

from content.models import Document, DocumentFolder
from content.services.document_type_codes import (
    COLLECTION_ACCOUNT,
    COMMERCIAL_PROPOSAL,
)


MONTH_NAMES_ES = (
    '',
    'Enero',
    'Febrero',
    'Marzo',
    'Abril',
    'Mayo',
    'Junio',
    'Julio',
    'Agosto',
    'Septiembre',
    'Octubre',
    'Noviembre',
    'Diciembre',
)

DOCUMENT_KIND_LABELS = {
    COLLECTION_ACCOUNT: ('Cuentas de cobro', 10),
    COMMERCIAL_PROPOSAL: ('Propuestas comerciales', 20),
}


@dataclass(frozen=True)
class FolderLevel:
    system_key: str
    name: str
    order: int = 0
    project: object | None = None
    client_user: object | None = None


def _folder_name(value, fallback):
    normalized = ' '.join(str(value or '').split())
    return (normalized or fallback)[:120]


def _client_folder_name(client_user):
    if client_user is None:
        return 'Cliente sin identificar'
    profile = getattr(client_user, 'profile', None)
    if profile is not None:
        from accounts.services.proposal_client_service import (
            build_client_display_name,
        )

        display = build_client_display_name(profile)
        if display:
            return _folder_name(display, 'Cliente')
    full_name = client_user.get_full_name().strip()
    return _folder_name(full_name or client_user.email, 'Cliente')


def build_generated_folder_path(
    document_kind,
    *,
    business_date=None,
    project=None,
    client_user=None,
    cancelled=False,
    unissued=False,
):
    """Return the complete deterministic folder specification.

    ``business_date`` is mandatory for issued/generated documents.  A draft
    collection account cancelled before issue has its own date-free branch.
    """
    if document_kind not in DOCUMENT_KIND_LABELS:
        raise ValueError(f'Unsupported generated document kind: {document_kind}.')
    if not unissued and not isinstance(business_date, date):
        raise ValueError('A business date is required to file a generated document.')

    effective_client = client_user or getattr(project, 'client', None)
    levels = []

    if project is not None:
        owner_key = f'generated:project:{project.pk}'
        levels.extend((
            FolderLevel('generated:projects', 'Proyectos', order=10),
            FolderLevel(
                owner_key,
                _folder_name(project.name, f'Proyecto {project.pk}'),
                project=project,
                client_user=effective_client,
            ),
        ))
    elif effective_client is not None:
        owner_key = f'generated:client:{effective_client.pk}:unassigned'
        levels.extend((
            FolderLevel('generated:clients', 'Clientes', order=20),
            FolderLevel(
                f'generated:client:{effective_client.pk}',
                _client_folder_name(effective_client),
                client_user=effective_client,
            ),
            FolderLevel(
                owner_key,
                'Sin proyecto',
                client_user=effective_client,
            ),
        ))
    else:
        owner_key = 'generated:unclassified'
        levels.append(
            FolderLevel(owner_key, 'Sin clasificar', order=30),
        )

    kind_label, kind_order = DOCUMENT_KIND_LABELS[document_kind]
    kind_key = f'{owner_key}:{document_kind}'
    levels.append(FolderLevel(
        kind_key,
        kind_label,
        order=kind_order,
        project=project,
        client_user=effective_client,
    ))

    if unissued:
        unissued_key = f'{kind_key}:unissued'
        levels.extend((
            FolderLevel(
                unissued_key,
                'Sin emitir',
                project=project,
                client_user=effective_client,
            ),
            FolderLevel(
                f'{unissued_key}:cancelled',
                'Anuladas',
                project=project,
                client_user=effective_client,
            ),
        ))
        return tuple(levels)

    year_key = f'{kind_key}:{business_date.year}'
    month_key = f'{year_key}:{business_date.month:02d}'
    levels.extend((
        FolderLevel(
            year_key,
            str(business_date.year),
            project=project,
            client_user=effective_client,
        ),
        FolderLevel(
            month_key,
            f'{business_date.month:02d} - {MONTH_NAMES_ES[business_date.month]}',
            order=business_date.month,
            project=project,
            client_user=effective_client,
        ),
    ))
    if cancelled:
        levels.append(FolderLevel(
            f'{month_key}:cancelled',
            'Anuladas',
            project=project,
            client_user=effective_client,
        ))
    return tuple(levels)


def describe_generated_folder_path(*args, **kwargs):
    """Human-readable path used by previews and dry-run commands."""
    return ' / '.join(
        level.name for level in build_generated_folder_path(*args, **kwargs)
    )


def _ensure_level(level, parent):
    defaults = {
        'name': level.name,
        'parent': parent,
        'order': level.order,
        'project': level.project,
        'client_user': level.client_user,
    }
    folder, _created = DocumentFolder.objects.get_or_create(
        system_key=level.system_key,
        defaults=defaults,
    )
    changes = []
    for field, value in defaults.items():
        current = getattr(folder, f'{field}_id', None) if field in {
            'parent', 'project', 'client_user',
        } else getattr(folder, field)
        desired = getattr(value, 'pk', None) if field in {
            'parent', 'project', 'client_user',
        } else value
        if current != desired:
            setattr(folder, field, value)
            changes.append(field)
    if folder.is_archived:
        folder.is_archived = False
        folder.archived_at = None
        folder.archived_via_folder = None
        changes.extend(('is_archived', 'archived_at', 'archived_via_folder'))
    if changes:
        folder.save(update_fields=[*changes, 'updated_at'])
    return folder


@transaction.atomic
def ensure_generated_folder_path(*args, **kwargs):
    parent = None
    for level in build_generated_folder_path(*args, **kwargs):
        parent = _ensure_level(level, parent)
    return parent


def collection_account_concept(document):
    extension = getattr(document, 'collection_account', None)
    concept = getattr(extension, 'billing_concept', '') if extension else ''
    if not concept:
        # ``items`` already has the canonical position/id ordering. Iterating
        # through ``all()`` also reuses the backfill's prefetch cache instead
        # of issuing one query per historical account.
        first_item = next(iter(document.items.all()), None)
        concept = first_item.description if first_item else ''
    return ' '.join((concept or 'Cuenta de cobro').split())


def collection_account_title(document):
    if not document.issue_date or not document.public_number:
        return document.title
    prefix = f'{document.issue_date.isoformat()} · {document.public_number} · '
    available = max(0, Document._meta.get_field('title').max_length - len(prefix))
    return f'{prefix}{collection_account_concept(document)[:available]}'.rstrip()


def proposal_snapshot_title(proposal, business_date, version):
    suffix = f' · v{version:02d}'
    prefix = f'{business_date.isoformat()} · Propuesta comercial · '
    available = max(
        0,
        Document._meta.get_field('title').max_length - len(prefix) - len(suffix),
    )
    proposal_title = ' '.join((proposal.title or 'Sin título').split())[:available]
    return f'{prefix}{proposal_title}{suffix}'


@transaction.atomic
def file_collection_account(document):
    """Place an account according to its issue/cancellation state."""
    cancelled = document.commercial_status == Document.CommercialStatus.CANCELLED
    unissued = cancelled and not document.issue_date
    folder = ensure_generated_folder_path(
        COLLECTION_ACCOUNT,
        business_date=document.issue_date,
        project=document.project,
        client_user=document.client_user,
        cancelled=cancelled,
        unissued=unissued,
    )
    title = collection_account_title(document)
    changes = []
    if document.folder_id != folder.pk:
        document.folder = folder
        changes.append('folder')
    if document.title != title:
        document.title = title
        changes.append('title')
    if changes:
        document.save(update_fields=[*changes, 'updated_at'])
    return folder


@transaction.atomic
def file_proposal_snapshot(document):
    if not document.source_proposal_id or not document.source_version:
        raise ValueError('The document is not a proposal snapshot.')
    folder = ensure_generated_folder_path(
        COMMERCIAL_PROPOSAL,
        business_date=document.issue_date,
        project=document.project,
        client_user=document.client_user,
    )
    if document.folder_id != folder.pk:
        document.folder = folder
        document.save(update_fields=['folder', 'updated_at'])
    return folder


@transaction.atomic
def move_proposal_snapshots_to_project(proposal, project, *, acting_user=None):
    """Move every immutable version when acceptance creates its project."""
    from content.services import accounting_service

    documents = list(
        Document.objects.select_for_update()
        .select_related('document_type', 'folder', 'client_user')
        .filter(source_proposal=proposal)
        .order_by('source_version'),
    )
    moved = []
    for document in documents:
        old_values = accounting_service.snapshot_values(
            document, accounting_service.EntityType.DOCUMENT,
        )
        folder = ensure_generated_folder_path(
            COMMERCIAL_PROPOSAL,
            business_date=document.issue_date,
            project=project,
            client_user=project.client,
        )
        document.project = project
        document.client_user = project.client
        document.folder = folder
        document.updated_by = acting_user
        document.save(update_fields=[
            'project', 'client_user', 'folder', 'updated_by', 'updated_at',
        ])
        accounting_service.log_entity_diff(
            accounting_service.EntityType.DOCUMENT,
            document,
            old_values,
            acting_user,
        )
        moved.append(document)
    return moved
